### ISSUE TITLE
이거 이상해요

### ISSUE THREAD

**Issue by bonu1004** [onebone/EconomyS#100]
EconomyProperties에서 /property pos1, /property pos2 다 하고
/property make 150000 해서 표지판 만들고 테스트로 사봤는데 사려고 하는 땅이 다른
땅과 겹쳐져 있다고 뜨는데, 분명 /land list하면 아무 땅도 없거든요; 이거 이상해요

**Comment by onebone** [comment]
중복되는 이슈입니다.
