### ISSUE TITLE
Do the plugins database connection ?

### ISSUE THREAD

**Issue by clodeacc** [onebone/EconomyS#103]
I do create private office, think how to fasten Economy ^-^

**Comment by onebone** [comment]
I cannot understand what you're saying.

For MySQL, I am going to support but not in progress yet.

**Comment by Bamuel** [comment]
I hope MySQL gets added soon :+1:

**Comment by onebone** [comment]
:+1:

**Comment by Pub4Game** [comment]
@onebone As soon as you add a MySQL?

**Comment by onebone** [comment]
@Pub4Game It will be available in the near future.

**Comment by Pub4Game** [comment]
@onebone Now you started to do the plugin? Just you were gone so long....

**Comment by Driesboy** [comment]
i need to have this

**Comment by jasonwynn10** [comment]
https://github.com/LostTeam/EconomySMySQL

**Comment by jasonwynn10** [comment]
look at #332 for sql work
