### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by GAalexandres** [onebone/EconomyS#106]
If a player type /jackpot 0  or /casino gamble 1 the server crash, it works with all amount of money.
It works in economycasino 2.0.1 but not in economycasino 2.0.0

**Comment by ChalkPE** [comment]
Can you show me a crash dump?

**Comment by GAalexandres** [comment]
http://pastebin.com/gFqnpMP0

**Comment by onebone** [comment]
Why are you using older version?

**Comment by GAalexandres** [comment]
Older version of what?

**Comment by 64FF00** [comment]
@GAalexandres the plugin of course, Heheh

**Comment by GAalexandres** [comment]
Is the latest O.o

**Comment by 64FF00** [comment]
@GAalexandres Oh sorry, I mean the Casino one. The latest version of it is v2.0.2

**Comment by GAalexandres** [comment]
Oh, where can I download it? on pocketmine there is only the 2.0.1

**Comment by GAalexandres** [comment]
Hey?

**Comment by onebone** [comment]
I think you have old EconomyAPI.
