### ISSUE TITLE
Please fix sell in creative mode!!!

### ISSUE THREAD

**Issue by qwefqwfqwefqwef** [onebone/EconomyS#108]
Please fix sell in creative mode!!!

**Comment by Bamuel** [comment]
You should just get an output message saying
You are in creative mode

MCPE in creative you don't have an inventory you just have a list of blocks to use. This is why its impossible for now to sell in creative

**Comment by qwefqwfqwefqwef** [comment]
Yes? Why I can take for example a diamond block in your hand and sell it and so pavrotti many times. Sorry i translate google :D

**Comment by onebone** [comment]
Oh sorry. It was mistake.

**Comment by qwefqwfqwefqwef** [comment]
When You correct?)

**Comment by onebone** [comment]
Exam period :(
End by 4 days.

**Comment by qwefqwfqwefqwef** [comment]
:ok:
