### ISSUE TITLE
EconomyProperty 

### ISSUE THREAD

**Issue by Bamuel** [onebone/EconomyS#110]
I have having troubles getting EconomyProperty to work
I have install EconomyLand 

but when i make /property pos1 / pos2 
then /property make

nothing really happens *should there be a sign

**Comment by onebone** [comment]
/property make <price>
I think you didn't specify the price.

**Comment by Bamuel** [comment]
Ok i have manage it to work

soz for the problems

Because of my map the alignment of coords is abit messed up
so can you do what other plugins do by 
Break/Place block for pos1
and pos2

**Comment by onebone** [comment]
It is available using /property touchpos
