### ISSUE TITLE
ECONOMY LAND오류 심각

### ISSUE THREAD

**Issue by junknight** [onebone/EconomyS#111]
분명히 땅을 생성을 끝내놓고 리부팅이나 리로드를 하면 생성해놓은 모든땅이 사라집니다. .
버전이나 그런것들은 모두 최신인데요.....

**Comment by junknight** [comment]
stop도 해보고reload도 해보았습니다 마찬가지입니다

**Comment by onebone** [comment]
저에겐 발생하지 않습니다. 혹시 서버가 꺼질 때 콘솔 같은 곳에 메세지가 뜨나요?

**Comment by 64FF00** [comment]
@onebone 디버그 기능 같은거 만들어 놓으시면 좋을것 같은데 ㅜ
