### ISSUE TITLE
Payment Message Problem

### ISSUE THREAD

**Issue by SeangJemmy** [onebone/EconomyS#112]
Dear OneBone,
    Someone who recieves Money from other player need to see message that says "<PlayerName> paid you $<money>"! Please add the code to EconomyPayment! Thanks!

**Comment by SeangJemmy** [comment]
"(Name) paid you $(money)"

**Comment by onebone** [comment]
No player shown??
Maybe you can modify in language.properties :)

**Comment by onebone** [comment]
Oh, misunderstood. I will add in that feature in the next version.
