### ISSUE TITLE
add hide tap-again

### ISSUE THREAD

**Issue by qwefqwfqwefqwef** [onebone/EconomyS#114]
Please add hide:

"tap-again" => "Are you sure to sell %1 (%MONETARY_UNIT%%2)? Tap again to confirm",

**Comment by 64FF00** [comment]
What about just doing it like adding a config option like "disable-shop-confirm-message?"

**Comment by qwefqwfqwefqwef** [comment]
Yes. Sorry, I can't properly describe what I need, I badly know English

**Comment by 64FF00** [comment]
@qwefqwfqwefqwef Anyways :+1:
