### ISSUE TITLE
EcoProperty People can edit area's before they are bought

### ISSUE THREAD

**Issue by Bamuel** [onebone/EconomyS#118]
People can edit area's before they are bought.

This will make people fill in the area with random block

But once bought they have full control like normal

**Comment by onebone** [comment]
Refer to this video:
https://youtu.be/p3aJDOQfiLM

**Comment by onebone** [comment]
You mean property's protection is not working?

**Comment by Bamuel** [comment]
um

Protection works only after when the land gets bought

But before when the land get bought theirs just a sign where people can build around it
I need too have protection before the property is bought
(after works fine)

**Comment by onebone** [comment]
It works on my server fine, maybe you have set permission wrong.
