### ISSUE TITLE
EconomyAPI

### ISSUE THREAD

**Issue by qwefqwfqwefqwef** [onebone/EconomyS#122]
"# EconomyS configuration resource
monetary-unit: "$"
once-debt-limit: 100
debt-limit: 500
add-op-at-rank: false
default-money: 1000
default-debt: 0
max-money: 9999999999
time-for-increase-debt: 10
percent-of-increase-debt: 5
default-bank-money: 0
time-for-increase-money: 10
bank-increase-money-rate: 5
debug: true
default-lang: user-define
auto-save-interval: 10
check-update: true"

Unless the debt is not removed?
Why then these lines in your configuration? I'm sorry if something I do not understand:3
"default-debt: 0
once-debt-limit: 100
debt-limit: 500
time-for-increase-debt: 10
percent-of-increase-debt: 5"

**Comment by ChalkPE** [comment]
configs of the bank system should also be removed!
