### ISSUE TITLE
What about the encoding?

### ISSUE THREAD

**Issue by qwefqwfqwefqwef** [onebone/EconomyS#123]
![zyelby5vzqs](https://cloud.githubusercontent.com/assets/11244874/8649700/5cff8502-2975-11e5-86e9-ff4a9b13bce3.jpg)

Used the latest version from github

**Comment by onebone** [comment]
What the... I have checked that it was UTF-8!

**Comment by qwefqwfqwefqwef** [comment]
@onebone How soon can You fix this probley?

**Comment by onebone** [comment]
I think you have set encoding wrong.
