### ISSUE TITLE
EconomyAPI

### ISSUE THREAD

**Issue by Matunserver** [onebone/EconomyS#128]
이코노미 API 문제입니다.
1.돈순위에 오피가들어갑니다( op를 랭크에 표시하지않는다고 설정했음)
2. 돈순위가 이상하게나옵니다
예) 1)op1 : 89000
      2)op2 : 200
      3)player1 : 8000

**Comment by Matunserver** [comment]
예시는 사진으로 톡 보내겟습니다

**Comment by qwefqwfqwefqwef** [comment]
@onebone How soon will release plugins for the forum?
