### ISSUE TITLE
Shop funktioniert nicht

### ISSUE THREAD

**Issue by kempen2016** [onebone/EconomyS#129]
Hallo mein shop funktioniert nicht ich gebe folgendes ein

[SHOP]
$50
chest 
Amount : 1
Aber es geht nicht kann mir da wer helfen?
Und wie kann man Immobilien verkaufen wie geh das?

**Comment by qwefqwfqwefqwef** [comment]
Text Sign

Shop
50
ID
1

**Comment by onebone** [comment]
I can't understand your language.

**Comment by 64FF00** [comment]
Maybe a germany guy heheheh

**Comment by kempen2016** [comment]
I'm from germany

**Comment by kempen2016** [comment]
Hello my shop does not work I will give the following

[SHOP]
$ 50
chest
Amount: 1
But it is not there who can help me?
And how can you sell real estate as the go?
