### ISSUE TITLE
How to make "Money.yml" data into the database?

### ISSUE THREAD

**Issue by xxddff** [onebone/EconomyS#134]
I want to in more than one server synchronization

**Comment by onebone** [comment]
MySQL will be supported some day.

**Comment by xxddff** [comment]
External plugin?Which?
My  purpose is to synchronize the data across multiple servers, my servers are on the same hard drive, even without MySQLmy problem may also be solved; however the mechanism of saving and reading Economy plugin  seems to be different from what I thought.I can not synchronize the data using hard link of  Linux.  There is an  automatic saving time in Economy plugin, before saving it , type / mymoney and other command which seemed to read and write data from memory, while  hard links just synchronized the data of files. I do not know how to  synchronize my data.

**Comment by onebone** [comment]
There is no known plugin for me which can meet your request since this is the first case of asking to synchronize money data.
You must make your custom plugin, for now. I'm sorry about inconvenience.

**Comment by 64FF00** [comment]
Guess you just need to add MySQL support to EconomyS asap eheheheheh

**Comment by jasonwynn10** [comment]
https://github.com/LostTeam/EconomySMySQL
