### ISSUE TITLE
EconomyLand land invite 땅번호 r:닉네임

### ISSUE THREAD

**Issue by Matunserver** [onebone/EconomyS#137]
이코노미랜드에서 오피는 초대해제가 가능하지만 일반유저는 권한이없다라 뜨며 초대해제가 불가능합니다 plugin.yml 에서는 true 로 적혀있지만요.

**Comment by onebone** [comment]
정상 작동합니다. 땅의 아이디를 제대로 설정하셨는지 확인해주세요.
