### ISSUE TITLE
Incorrect work givemoney-must-be-number; takemoney-must-be-number

### ISSUE THREAD

**Issue by Pub4Game** [onebone/EconomyS#138]
Incorrect work givemoney-must-be-number; takemoney-must-be-number

It gives the message " Use: /takemoney,/givemoney not "Amount must be numeric"

**Comment by Pub4Game** [comment]
@onebone When you will have time to fix this bug?

**Comment by onebone** [comment]
*-invalid-number does not mean it is not a number, but means it is smaller than 0.
