### ISSUE TITLE
economy shop bug

### ISSUE THREAD

**Issue by Tolo0** [onebone/EconomyS#141]
I tried changing the shop text. Then made a sign on my server. 2min later my server forced closed when I when back to where i made the new sign. A big chunck was missing from the ground up. I had to reinstall my world back up and remove and replace the shop plugin

**Comment by onebone** [comment]
Chunk missing is not the bug of EconomyShop.

**Comment by Tolo0** [comment]
I configured the shop text wrong so when I made a sign it forced closed the server and removed chunks.  I tried removing the § symbol. But it's ok now I just did §r and it works fine :)
