### ISSUE TITLE
Economy Property 에서 에러가 발생합니다 (ERROR)

### ISSUE THREAD

**Issue by kim-min** [onebone/EconomyS#147]
이 플러그인을 적용하고 pmmp를 실행시키면 알 수 없는 의존 플러그인이라고 하면서 로드가 되지 않습니다. 저만 그러는건지요... 해결방법 부탁드립니다.
IF, I apply this plugin and open to pmmp, pmmp can't load and said Unknown Dependence plugin. Plese anser to how I can solution this problom.

**Comment by onebone** [comment]
EconomyProperty 는 EconomyLand 를 필요로 합니다.
