### ISSUE TITLE
Economy Property의 표지판 방향을 바꾸고 싶습니다.

### ISSUE THREAD

**Issue by kim-min** [onebone/EconomyS#149]
제목과 같습니다. 토지 방향이 북쪽인데 표지판은 서쪽을 보고 있으니... 표지판을 잘 볼 수 없습니다. 표지판 방향 바꾸는 명령어가 추가된 config.yml 이나 이외에 바꿀 수 있는 방법을 알려주십시요

**Comment by onebone** [comment]
수정하겠습니다
