### ISSUE TITLE
Economy PShop dependency error please help

### ISSUE THREAD

**Issue by Hahejo** [onebone/EconomyS#151]

**Comment by ChalkPE** [comment]
[EconomyPShop](https://github.com/onebone/EconomyS/tree/master/EconomyPShop) requires [EconomyAPI](https://github.com/onebone/EconomyS/tree/master/EconomyAPI) and [ItemCloud](https://github.com/onebone/ItemCloud).

**Comment by Hahejo** [comment]
[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] [11:26:18] [Server thread/WARNING]: Timezone could not be automatically determined. An incorrect timezone will result in incorrect timestamps on console logs. It has been set to "UTC" by default. You can change it on the php.ini file.
[Server] [11:26:18] [Server thread/INFO]: Loading pocketmine.yml...
[Server] [11:26:18] [Server thread/INFO]: Loading server properties...
[Server] [11:26:18] [Server thread/INFO]: Selected English (eng) as the base language
[Server] [11:26:18] [Server thread/INFO]: Starting Minecraft: PE server version v0.11.0 alpha
[Server] [11:26:18] [Server thread/INFO]: Starting remote control listener
[Server] [11:26:19] [Server thread/INFO]: RCON running on 0.0.0.0:19132
[Server] [11:26:19] [Server thread/INFO]: Opening server on 0.0.0.0:19132
[Server] [11:26:19] [Server thread/INFO]: This server is running PocketMine-MP version 1.5dev-1258 "活発(Kappatsu)フグ(Fugu)" (API 1.12.0)
[Server] [11:26:19] [Server thread/INFO]: PocketMine-MP is distributed under the LGPL License
[Server] [11:26:21] [Server thread/INFO]: Loading SimpleAuth v1.7.1
[Server] [11:26:21] [Server thread/INFO]: Loading EconomyAPI v2.0.8
[Server] [11:26:21] [Server thread/INFO]: Loading EconomyAuction v2.0.2
[Server] [11:26:21] [Server thread/INFO]: Loading EconomyCasino v2.0.2
[Server] [11:26:21] [Server thread/INFO]: Loading EconomyJob v2.0.4
[Server] [11:26:22] [Server thread/INFO]: Loading EconomyLand v2.0.8
[Server] [11:26:22] [Server thread/INFO]: Loading EconomyProperty v2.0.5
[Server] [11:26:22] [Server thread/CRITICAL]: Could not load plugin 'EconomyPShop': Unknown dependency
[Server] [11:26:22] [Server thread/INFO]: Loading EconomySell v2.0.6
[Server] [11:26:22] [Server thread/INFO]: Loading EconomyShop v2.0.6
[Server] [11:26:22] [Server thread/INFO]: Loading EconomyTax v2.0.3
[Server] [11:26:22] [Server thread/INFO]: Loading EssentialsPE v1.1.2
[Server] [11:26:22] [Server thread/INFO]: Loading EconomyUsury v1.0.1
[Server] [11:26:22] [Server thread/INFO]: Loading PocketDockConsole v0.0.14
[Server] [11:26:22] [Server thread/INFO]: [PDC] Loaded
[Server] [11:26:22] [Server thread/INFO]: Loading AdminJoin v1.3.1
[Server] [11:26:22] [Server thread/INFO]: Loading GodMode v2.3
[Server] [11:26:22] [Server thread/INFO]: Loading BanItem v2.1
[Server] [11:26:22] [Server thread/INFO]: Loading Alias v1.2.0
[Server] [11:26:22] [Server thread/INFO]: Loading AdvertisingKick v1.0.0
[Server] [11:26:22] [Server thread/INFO]: Loading Pundler v1.4.3
[Server] [11:26:22] [Server thread/INFO]: Loading EconomyAirport v2.0.4
[Server] [11:26:22] [Server thread/CRITICAL]: Could not load plugin 'EconomyPShop': Unknown dependency
[Server] [11:26:22] [Server thread/CRITICAL]: Could not load plugin 'EconomyPShop': Unknown dependency
[Server] [11:26:22] [Server thread/INFO]: Loading SimpleWarp v2.0.3
[Server] [11:26:22] [Server thread/CRITICAL]: Could not load plugin 'EconomyPShop': Unknown dependency
[Server] [11:26:22] [Server thread/CRITICAL]: Could not load plugin 'EconomyPShop': Circular dependency detected
[Server] [11:26:27] [Server thread/INFO]: ----- PocketMine-MP Auto Updater -----
[Server] [11:26:27] [Server thread/INFO]: It appears you're running a Beta build, when you've specified that you prefer to run Stable builds.
[Server] [11:26:27] [Server thread/INFO]: If you would like to be kept informed about new Beta or Development builds, it is recommended that you change 'preferred-channel' in your pocketmine.yml to 'beta' or 'development'.
[Server] [11:26:27] [Server thread/INFO]: ----- -------------------------- -----
[Server] [11:26:27] [Server thread/INFO]: Enabling SimpleAuth v1.7.1
[Server] [11:26:27] [Server thread/INFO]: [SimpleAuth] Everything loaded!
[Server] [11:26:27] [Server thread/INFO]: Preparing level "Hahejo's WORLD"
[Server] [11:26:28] [Server thread/INFO]: Enabling EconomyAPI v2.0.8
[Server] [11:26:28] [Server thread/NOTICE]: [EconomyAPI] Auto save has been set to interval : 10 min(s)
[Server] [11:26:28] [Server thread/INFO]: [EconomyAPI] Checking for updates... It may be take some while.
[Server] [11:26:33] [Server thread/NOTICE]: [EconomyAPI] 
[Server] [11:26:33] [Server thread/INFO]: Enabling EconomyAuction v2.0.2
[Server] [11:26:33] [Server thread/INFO]: Enabling EconomyCasino v2.0.2
[Server] [11:26:33] [Server thread/INFO]: Enabling EconomyJob v2.0.4
[Server] [11:26:33] [Server thread/INFO]: Enabling EconomyLand v2.0.8
[Server] [11:26:33] [Server thread/INFO]: Enabling EconomyProperty v2.0.5
[Server] [11:26:33] [Server thread/INFO]: Enabling EconomySell v2.0.6
[Server] [11:26:33] [Server thread/INFO]: Enabling EconomyShop v2.0.6
[Server] [11:26:34] [Server thread/INFO]: Enabling EconomyTax v2.0.3
[Server] [11:26:34] [Server thread/INFO]: Enabling EssentialsPE v1.1.2
[Server] [11:26:34] [Server thread/INFO]: [EssentialsPE] Loading...
[Server] [11:26:34] [Server thread/INFO]: Enabling EconomyUsury v1.0.1
[Server] [11:26:34] [Server thread/INFO]: Enabling PocketDockConsole v0.0.14
[Server] [11:26:34] [Server thread/INFO]: [PDC] Enabled
[Server] [11:26:34] [Server thread/INFO]: [PDC] Started SocksServer on 0.0.0.0:9090
[Server] [11:26:34] [Server thread/INFO]: Enabling AdminJoin v1.3.1
[Server] [11:26:34] [Server thread/INFO]: Enabling GodMode v2.3
[Server] [11:26:34] [Server thread/INFO]: Enabling BanItem v2.1
[Server] [11:26:34] [Server thread/INFO]: Enabling Alias v1.2.0
[Server] [11:26:34] [Server thread/INFO]: Enabling AdvertisingKick v1.0.0
[Server] [11:26:34] [Server thread/INFO]: [AdvertisingKick] AdvertisingKick Starterd
[Server] [11:26:34] [Server thread/INFO]: Enabling Pundler v1.4.3
[Server] [11:26:34] [Server thread/INFO]: Enabling EconomyAirport v2.0.4
[Server] [11:26:34] [Server thread/INFO]: Enabling SimpleWarp v2.0.3
[Server] [11:26:37] [Server thread/INFO]: Starting GS4 status listener
[Server] [11:26:37] [Server thread/INFO]: Setting query port to 19132
[Server] [11:26:37] [Server thread/INFO]: Query running on 0.0.0.0:19132
[Server] [11:26:37] [Server thread/INFO]: Default game type: Survival Mode
[Server] [11:26:37] [Server thread/INFO]: Done (24.347s)! For help, type "help" or "?"
[Server] [11:26:39] [Server thread/INFO]: [EssentialsPE] No new version found, you're using the latest version of EssentialsPE

**Comment by ChalkPE** [comment]
@Hahejo [ItemCloud](https://github.com/onebone/ItemCloud) is missing. Download the [ItemCloud phar](https://github.com/onebone/ItemCloud/releases/tag/1.3) and put it to your plugins directory!

**Comment by Hahejo** [comment]
Thank you so much
Vào 25-08-2015 19:32, "Chalk" <notifications@github.com> đã viết:
