### ISSUE TITLE
EconomyShop

### ISSUE THREAD

**Issue by Bidou0418** [onebone/EconomyS#154]
Problem with EconomyShop and EconomySell files: Shops.yml and Sell.yml.
The problem with the created shop signs and sell signs is that they kind of stay in buffer and never get saved.
They function as long as you don't restart the server.
As soon as you restart the server the info is lost and signs no longer work.
I tried this on 2 different servers with same results.

Btw I noticed another small thing, monetary unit not shown on default setting for shop sign.
It is shown on the sell sign.

Could you please update
Currently running 5.6
please advise if you know of any other plugin that could conflict with Economy so I can remove it.

**Comment by Bidou0418** [comment]
Yup that's it, problem with the created shop signs, they stay in buffer and never get saved.
As soon as you restart the server the info is lost and signs no longer work

**Comment by Bidou0418** [comment]
Has anyone else experienced this?

**Comment by onebone** [comment]
I thought that was fixed a long ago, maybe you should check if you closed your server forcely, for example, using Ctrl + C.

**Comment by Bidou0418** [comment]
Nope
I run the server on hostingitall.com
All I do is click the restart button

**Comment by Bidou0418** [comment]
When can you fix this onebone?
It's probably minor

**Comment by onebone** [comment]
Do you get any message in MCPE when the server being closed?

**Comment by Bidou0418** [comment]
No

**Comment by Bidou0418** [comment]
If I restart server, I get nothing at all when I click the sign.
I need to create a new sign and it works until I restart server.

**Comment by Bidou0418** [comment]
Try to create a shop sign, restart your server and try to use the sign.

**Comment by Bidou0418** [comment]
Just says server closed before mcpe closes

**Comment by Bidou0418** [comment]
Onebone? Am I wrong or not?
It might be due to my plugins or something else.
Let me know

**Comment by Bidou0418** [comment]
Any news?

**Comment by onebone** [comment]
I cannot know what is happening on your server since it works perfectly on my server.
