### ISSUE TITLE
Messages

### ISSUE THREAD

**Issue by Pub4Game** [onebone/EconomyS#156]
Can make the output messages in the console when you use the /givemoney,/setmoney
[Steve gave out 1200$ player - Steve2]

I already created a similar request.....

**Comment by onebone** [comment]
I have closed the issue since it is sending message:

https://github.com/onebone/EconomyS/blob/master/EconomyAPI/src/onebone/economyapi/commands/GiveMoneyCommand.php#L72
https://github.com/onebone/EconomyS/blob/master/EconomyAPI/src/onebone/economyapi/commands/SetMoneyCommand.php#L69

**Comment by Pub4Game** [comment]
switch($result){
			case -2: // CANCELLED
			$output .= "Your request have been cancelled";
			break;
			case -1: // NOT_FOUND
			$output .= $this->getPlugin()->getMessage("player-never-connected", $sender->getName(), array($player, "%2", "%3", "%4"));
			break;
			// INVALID is already checked
			case 1: // SUCCESS
			$output .= $this->getPlugin()->getMessage("givemoney-gave-money", $sender->getName(), array($amount, $player, "%3", "%4"));
			$server->getLogger()->info("Player ".$sender->getName()." give player $player $amount$");
			if($p instanceof Player){
				$p->sendMessage($this->getPlugin()->getMessage("givemoney-money-given", $sender->getName(), array($amount, "%2", "%3", "%4")));
			}
			break;
		}


I wanted it displayed in the console

**Comment by Bidou0418** [comment]
Yes
