### ISSUE TITLE
Money.yml resetting randomly

### ISSUE THREAD

**Issue by peepzandmeepz** [onebone/EconomyS#158]
Hey there! Been having this issue for awhile now regarding EconomyAPI.

This pops up in console when the .yml file "resets" or corrupts.
07.09 19:46:09 [Server] Server thread/WARNING RuntimeException: "yaml_parse(): end of stream reached without finding document 0" (E_WARNING) in "/src/pocketmine/utils/Config" at line 143

This disables EconomyAPI (both .7 and .8). The money.yml file registers no data inside/player accounts.

**Comment by onebone** [comment]
I will take a look at that bug some day.

**Comment by onebone** [comment]
Cannot reproduce the issue.
