### ISSUE TITLE
EConomyCasino 오류

### ISSUE THREAD

**Issue by cloud9350** [onebone/EconomyS#16]
/casino join <플레이어 이름> 을 하면 무조건 팅기네요.
확률로 팅기네요. 크러시 덤프파일 없이 바로 프로세스가 죽어버립니다. 왜그럴까요...

**Comment by cloud9350** [comment]
추가오류 - 서버 켜자마자 발생
환경은 윈도우8 Professional K 64bit

PocketMine-MP Crash Dump Fri Jan 16 15:53:11 CST 2015

Error: Call to a member function close() on null
File: /EconomyProperty_v2.0.1.phar/src/onebone/economyproperty/EconomyProperty
Line: 82
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: EconomyProperty v2.0.1

Code:
[73] 				++$cnt;
[74] 			}
[75] 			$property->close();
[76] 			$this->getLogger()->info("Parsed $cnt of old data to new format database.");
[77] 			@unlink($this->getDataFolder()."Properties.sqlite3");
[78] 		}
[79] 	}
[80] 
[81] 	public function onDisable(){
[82] 		$this->property->close();
[83] 	}
[84] 
[85] 	public function onBlockTouch(PlayerInteractEvent $event){
[86] 		$block = $event->getBlock();
[87] 		$player = $event->getPlayer();
[88] 
[89] 		if(isset($this->touch[$player->getName()])){
[90] 		//	$mergeData[$player->getName()][0] = [(int)$block->getX(), (int)$block->getZ(), $block->getLevel()->getName()];
[91] 			$this->command->mergePosition($player->getName(), 0, [(int)$block->getX(), (int)$block->getZ(), $block->getLevel()->getFolderName()]);
[92] 			$player->sendMessage("[EconomyProperty] First position has been saved.");

Backtrace:
#0 /src/pocketmine/Server(0): pocketmine\Server->crashDump()
#1 /src/pocketmine/plugin/PluginBase(88): onebone\economyproperty\EconomyProperty->onDisable()
#2 /src/pocketmine/plugin/PharPluginLoader(138): pocketmine\plugin\PluginBase->setEnabled()
#3 /src/pocketmine/plugin/PluginManager(633): pocketmine\plugin\PharPluginLoader->disablePlugin()
#4 /src/pocketmine/plugin/PluginManager(565): pocketmine\plugin\PluginManager->disablePlugin()
#5 /src/pocketmine/Server(1778): pocketmine\plugin\PluginManager->enablePlugin()
#6 /src/pocketmine/Server(1764): pocketmine\Server->enablePlugin()
#7 /src/pocketmine/Server(1694): pocketmine\Server->enablePlugins()
#8 /src/pocketmine/PocketMine(442): pocketmine\Server->__construct()
#9 (1): ()
#10 (0): {main}()

PocketMine-MP version: 1.4.1dev #945 [Protocol 20; API 1.11.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT ADMIN-PC 6.3 build 9200 (Windows 8.1 Business Edition) i586
PHP Version: 5.6.4
Zend version: 2.6.0
OS : WINNT, win

Loaded plugins:
AlwaysSpawn 2.1.3 by Comedyman937 for API(s) 1.0.0
AreaProtect 1.0.1 by Comedyman937 for API(s) 1.2.0
ArmorSpawn 2.0 by LDX for API(s) 1.0.0
BanItem 2.1 by LDX for API(s) 1.0.0
ChestRefill 1 by Falk for API(s) 1.0.0
ColorText 1.3.0 by Heromine for API(s) 1.4.0
EconomyAPI 2.0.3 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyAuction 2.0.0 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1
EconomyCasino 2.0.0 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1
EconomyJob 2.0.1 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyLand 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyProperty 2.0.1 by onebone for API(s) 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomySell 2.0.2 by onebone for API(s) 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyShop 2.0.2 by onebone for API(s) 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyTax 2.0.1 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
Farms 1.0-non-alpha by hm for API(s) 1.4.1
Gills 2.0.0 by Falkirks for API(s) 1.7.0
iControlU 1.3 by Falkirks for API(s) 1.6.0
iProtector 2.0 by LDX for API(s) 1.6.0
JoinCommands 1.1 by PixelGuy75 for API(s) 1.0.0
KeepInventory 1.2.0 by boybook for API(s) 1.0.0
KillMoney 1.1.0 by Topic for API(s) 1.9.0
LevelChat 0.0.1 by iJoshuaHD for API(s) 1.9.0
mcg76_PrivatePlot 1.0.2 by minecraftgenius76 for API(s) 1.0.0
MoreHealth 1.0.3 by iksaku for API(s) 1.9.0
NightPVP 2.0.1 by Falk for API(s) 1.0.0
OreFinder 1 by Falk for API(s) 1.0.0
PeacefulSpawn 2.4 by LDX for API(s) 1.3.1, 1.4.0
PerWorldChat 1.2 by EvolSoft for API(s) 1.10.0
RealTime 2.1 by Guillaume351 for API(s) 1.0.0
SignShop 0.9.2 by xionbig, xionbig for API(s) 1.10.0
SignStatus 1.1.2 by xpyctum for API(s) 1.0.0
SimpleAuth 1.6.0 by PocketMine Team, shoghicp for API(s) 1.8.0
SubnetBan 1.0.0 by  for API(s) 1.0.0
TapToDo 2.0.0 by Falk for API(s) 1.0.0
TimeCapsule 1.1.1 by Falk for API(s) 1.0.0
TimerBan 2.0 by onebone for API(s) 1.2.0, 1.2.1
Universe 1.0.0 by Comedyman937 for API(s) 1.9.0
WorldEditArt 1.0.0_beta_dev_#045 by PEMapModder for API(s) 1.0.0
WorldMonitor 2.0.0.000.0 by Steven for API(s) 1.2.0
xyz 1.0.1 by unerds for API(s) 1.0.0
EconomyAirport 2.0.1 by onebone for API(s) 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
HealthBar 1.0.0 by LegendOfMCPE for API(s) 1.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNoDAAAAAAE=
===END CRASH DUMP===

**Comment by onebone** [comment]
한 문제점 당 하나씩 쓰레드를 만들어주시기 바랍니다.

그리고 플러그인이 최신버젼인지 확인해주세요.

**Comment by cloud9350** [comment]
[CRITICAL] Unhandled exception executing command 'casino gamble 45' in casino: Undefined offset: 0
11:47:31 [NOTICE] ArrayOutOfBoundsException: "Undefined offset: 0" (E_NOTICE) in "/EconomyCasino_v2.0.0.phar/src/onebone/economycasino/EconomyCasino" at line 227

/casino gamble 45 입력시 일어나는 문제입니다.
