### ISSUE TITLE
Claimed Land Crashes Server [0.12.1]

### ISSUE THREAD

**Issue by McDrakon123** [onebone/EconomyS#168]
When someone who is not added to a claimed land area and tries to break a block or place a block the server will crash.

>Fatal error: Call to undefined method pocketmine\item\ItemBlock::isPlaceable() in phar:///home/tcagame/elitecra/728/plugins/EconomyLand_v2.0.8.phar/src/onebone/economyland/EconomyLand.php on line 613

>PocketMine-MP Crash Dump Tue Sep 15 17:27:39 UTC 2015

>Error: Call to undefined method pocketmine\item\IronSword::isPlaceable()
File: /EconomyLand_v2.0.8.phar/src/onebone/economyland/EconomyLand
Line: 613
Type: E_ERROR

>THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: EconomyLand v2.0.8

>Code:
>[604] 						$this->placeQueue[$player->getName()] = true;
>[605] 					}
>[606] 					return false;
>[607] 				}
>[608] 			}
>[609] 		}elseif($info !== true){
>[610] 			$player->sendMessage($this->getMessage("no-permission", array($info["owner"], "", "")));
>[611] 			$event->setCancelled();
[612] 			if($event instanceof PlayerInteractEvent){
[613] 				if($event->getItem()->isPlaceable()){
[614] 					$this->placeQueue[$player->getName()] = true;
[615] 				}
[616] 			}
[617] 			return false;
[618] 		}
[619] 		return true;
[620] 	}
[621] 
[622] 	public function addLand($player, $startX, $startZ, $endX, $endZ, $level, $expires = null){
[623] 		if($level instanceof Level){

>Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

>PocketMine-MP version: 1.6dev #29 [Protocol 34; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux Zulu.HostingItAll.com 3.10.23-xxxx-std-ipv6-64 #1 SMP Tue Mar 18 14:48:24 CET 2014 x86_64
PHP Version: 5.6.10
Zend version: 2.6.0
OS : Linux, linux

>Loaded plugins:
PureGIS 1.0.0 by 64FF00 for API(s) 1.12.0
PocketGuard 2.1.1 by MinecrafterJPN for API(s) 1.10.0
ManyWorlds 2.0.2 by aliuly for API(s) 1.10.0
Pundler 1.4.3 by MinecrafterJPN for API(s) 1.10.0
EconomyAPI 2.0.8 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
PurePerms 1.1.12 by 64FF00 for API(s) 1.13.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
WorldEditArt 1.0.0_beta_dev_#048 by PEMapModder for API(s) 1.0.0
EconomyLand 2.0.8 by onebone for API(s) 1.12.0
EconomyShop 2.0.6 by onebone for API(s) 1.12.0
MagicTelePortal 1.3.2 by aliuly for API(s) 1.10.0
EconomySell 2.0.6 by onebone for API(s) 1.12.0
EconomyProperty 2.0.5 by onebone for API(s) 1.12.0
EssentialsPE 1.1.2 by LegendsOfMCPE Team for API(s) 1.12.0
WorldProtect 2.2.0 by aliuly for API(s) 1.10.0, 1.12.0
PureChat 1.3.0 by 64FF00 for API(s) 1.11.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0

>----------------------REPORT THE DATA BELOW THIS LINE-----------------------

>===BEGIN CRASH DUMP===
eNrNWolv20bW/1dmlQBrfxB1W3ZUuIDhON0s7EYbu8iiYWGMyKHEmlc5pGWlyP/+/d6b4SW7zdFg
d91DnDczb959DPl7rwhj1VuMZ7PJdHoyOnrR76k8T/Pe4vdescsw1bu4vXj79s3bXr8XK63lmmDn
MopEkYoy8VUQJsoXsSo2qS+y1LtTRQyQ64aFil33dZ4m19s09xeLUC8j6Sm5itTBIfAFYUTIhhde
mqTx7lIm/u39ZDAanAyyjcyHOveGaaJW+G+ozJoIa9rrgSXCYb3FfDz92O9lUbkOEyK6s8RLfUUc
zUczzLlF88/zYhNq5/uM6PpXqUr1/jmedyp3vl+r4kcZg9JfxKko8lJ9B0zz0VEHw0eGzTuwXBVl
nohARtruOW7Nmx0nNcSMX9jxR4VNYXDwPEyCVPzt1Jx8+DstGo/qTTWRWiX+lVHLgeUFdFcQt5ek
TqbyONQ6TBO31xcyz+XOoH/v9tJtonK390tfuD2apf8fHh4y1eNxc5y6V0lBpxXnMvFUFCn/wK6a
1KuIbF4owkQXtC4NxJIJfZ0UKpdecUHTlptpSyj1Vib/NQzn4ND5vmMvdldXgV+svvHRvirG864q
xo2yHilyXKnNrKyUZtfVh0yMonjRhKTID0ZQWbmKQk8EZeIVUImQvk9GemDp7ovnEF1e/Lt6+BkP
0PG/zQ+NIggqouFDFuZKg7ukjCIjnkklVBIoL2zr4pIAWAhHKaANuMT73rORODhcdPz2WuX3JEEv
l3rzsoyzg1WaRkomhzCU3lrBZGRE7oRVZFY4cjyY++oeFKzKMPJ7iwniSJanReqlWDmd9XsyC3nd
eDoYYd06LDAcfeYfNuTyLgpXtGdwzBjKRFLk6l2GSfkgfi6jcvCPVBdhsn5dnEXRwEtjMR2MR4PJ
1HnAn6ML3wmz+7kzn4lnY3F9tRQ3pRJXMhfjEzGeLWYni8lMnF/ciMloPBMPJ/Pb+QwnZZsM5xwN
5sCG4QfoAeMJxiMze5vqihAAeBDxoI5ImsS1LHP1w+trerS0V5B+R5QjxitLBNRck47ms1evIIRf
rBTfkxgRJgmgEvIO0EPG1+/5KgN1tAlzOg2Kl21ALDk23hp8rmuPrx8omKaSmLu+OXt789MSgK1a
aQRywDZFkenFcAjVbcoVyXdI+5aGwWGFAzwv2Zh+KGXut5ltQdsMTwZgp8vwFewQ1hcgaPxz+WOX
8dHXM95FC7Y7FFnWl2+ub969eXv58lPMd7ENW8iGJIQrmezepXnk65YMWsCuCGCmXRHIKCyj3Tdj
3aBz3RgEbJkA172iqT/nmyILKRR5PlJ5x3INpGu5s8H0P6JIezoZbkXGZ3Bha4Kz5esWIy3gvkZO
urzYSqTDhHFVMGN/J/XvmH+ndjy145kdzzD+St4tGa5rKyLQ4rodLj5LoXBc1AV6LxgZWFepFGw+
HY+m3ygeMQWtx78ckwwW8PxS3d8gj7VZrkF7HD+KwMa5yZrFjZJxh/Xp1+uyOt91W5R8Ibs1ZcMa
B5jlIHPhh8VZXrQY7oAfZZ3blSrkLRL57bPRbM/6lxdXMrtKfR/etu8BX8l9pmKZxYzSdTkoKVCG
msd19+j80tDcInZ4HaNXcX4+dyqjQLmmhrHUiEnDzjlNiOC24VGMsM3EFweJT+bqdhD6As+nXqh2
/aoZ+uwweL1Js8c8MnSfx/l/j0cNemoeLXGfweOVXIfejYrUMs0LU6zWGbg703WC6X8qDRfZl+Tf
in80Xk+ojKD/SyoDPY3KDHGfz+MyT9GwFrvHfNYz+7wefUNerRt9HeeZpbDmvkXy50hAo5svQnSb
y4s2+23wfmreM9dLtSYq3wRX58uLx6nqr3QNbTJc9xLsfLLueio0GwoNgcMOa1XWgtAK5T3KWhW4
q/3Jfqb+I4ft/0X2K8/lPJUZWvZd+DNTtozUrzCzPAXKYdN4O9kfJaiKdVu4nW9ksVe3MWg/lH1G
Fzn+lFs0FdQj2fReSb7C0CCv9wfVHNHVPP3lWo6RQArXYZxF6gy8teTQAnYlcbzfXu5Xc+Bsk643
oZd9M29piHHdDmFfXd21sHykewWZg22YSEUIX9oMbAgKFV1CPFvWI3GeJkG4FnTl6uZu8oyuPq5V
JsZHYny8mBwtRiPx0805XX0c0QKDzyHZnl5EIPDctHEfWpMZUujp+MV4OiFgrOI03zlRGIeA0rUN
QdeS4L46NWvkg2MuuvTp1JyTyW3iWIeCxk7HcwJvNzgSuHRxymiMDpzfSpXvTtOkBcoRak/TICAQ
PQ8yqTXdN5/+H//h0LTwT91yNJLHkflJzc+KGTPPss2fTJK0TDxlaXWktwnVvYoRrLQ9/T5UW8cP
zd3a6QnviqJ06wRRuN4UFUWGPZmEqEKrrQYWp6sKEKQ5zqolZbduZO57aV6Ps/vMrvfDIAi9Mip2
p2OWMV/JFWnuaFXQDZg+JTDf/xkNwp4aiFbKby2ga/7TIIKjEg9lkTpa3it7FF1w1RFqsIsjMitB
YU94bFElDqZ7TDIsAUZEY7LO1RKGJm42SitRUSZkrkSxUQKJU+NBFsIjcRdipUSYeFGJLgAP4pFB
E67rNMbOgBDs49QyUH2RYibXhFKsciXvxC4tc4tLhIGAgMMg5BMg2xw2h6AOxD+qbY1u6KtAQrpa
bNPk74WQWaZkLkg0MZj1oOcdyBd092z43m5UIspsnUsfCAZuQi5ikC3cRDy72SCkOxFAoAJl+7qU
ayXorQSLzLqTDjGOUuAPP7BQaev5RnmWi+5GEFAFDJUMtuFdmKF9koM0Xw9pNLyEcd6mwe3r6ze3
8+kLZ3JL+yDGGtFCuAhua7dHB73bKJIdvdWhlwqC3vDoImf5FrlMNCwEcuNpliZTCjrwpApWKTrH
0FNiI+lShiAxEBvjbo7k23TA9aYs/JQcwbysIGLMzbPwolQr35B1Rk4lKBCAEmFTpLgPpfgXxQIs
4ZhQJc8F38LTRjQLWyHJSnUKauwpRlXSIhKlhhEioMMQmDsUfPZNFsmpmXBA1gpENegvOPpUeMCx
IF8VMFdYBJG62glrR1huY1U924jh2bsQgk4TmJT0fZErbSyPyISt3YEcqZH6Yn6vouElJA8IXf1W
Sn4Htw7vsfZeRojoB/ZIhPFDIDfnIUYqCtUOtLleq3yBWTr5xzJeQdpwpzO9S7wbqe9g8fkdHGhA
8z9BCWyfFZO0apOjsi1hElit+4LLIWEDEEy2DzHEkBq/b2KxIL8RLC4TeA4tYdzXbDLgB86Vpw8I
j4WCCMAOm3pSk0ZSNeS8DshDaQl5Yl+Exd/pJWTOu3xF+YOtcG+vOAAH0LOYkESYB8dyuWBM5K0m
d7Gv/hClKwiWErswYMEpjWJSrNZytStAkLg2pIz48FCTeo2ng6dtyISxsAXlBJsaLUizXIIQ5oIw
Zd6YAUuAGFGdaNQPZko22nUKPlJyDZIZzlkzkSbXLsTI5VDBUblAqJH+/zj5VCT9CfGU+f4S8bpI
Mz7fhqqaHotNC7gU1QmIMpYaOrMiaTyazAxVKH3DlNMR+aKmAz0OyJa62t/GOAqhxicb4xUO/EEZ
T+MwnqLPSeChkBtFhz8SqxEnqp+IIzz5ulnmcsIlHPC+xpNNOKIT3lAIoQzHywePFxPbtpSFCDPl
USLULBai1cjY7K0ZgCRVphs2pyPLpz58kiDL9dRwvZb5Cvp3vDSKTHVHHvakVNmciBS7R9g98N1Y
JiWn3DYVKEdK2MJhv4oJe8ZgrcHE1SCoYkPcWNlAvDH5jkewiE1aRn5NSIgIsk1EQzrZrciYcjA4
p/I24YNesSc8io1sK2Z3zVSQp3EVYmmvnXfaUamlUzBhVbdvCk/YT2sfVdnepkzutJH3JVs9BUQG
EmXUhhA3onrtTO6ZowDRZpFDNQDVMg0uQlWp2TrKi7ml82Vqtu2rj5IAVUpmWxuDOcUu+wY8cyJy
PFTqynBtbaE6iCbq7P2nqNwkUQXpoi7dYBqRyYQrWaAVoEJEUpWLBAh7slGJHdAUpnbWBKOVqnMi
h5tn7fBVzZDj57uCcPeFM24ZM+U+PtYpKlIQVo7mJqo0uda87S8pZ3O4swo0ewG0NA3EP9CfQLyn
qIVhuOfLn/rYCwpWiD/b0C82Jmqzf9foHUa/EMe2MGhKBs2CaS0diDMf/rSRUUBf75gqxlewM3sQ
jjT2lyZth6yzcwtXq066eCDnozJIRn3j2HTwuzBBFQm2YDaKTZty/U/LZFlVCk3NTkUQbdoi1rtU
sCeZY4ftmgwNllqV64UtOr4XYyo2bGahqpKnq4pScxzbqKrSdK0qkEaaOlGLITrFooTBDNeeES3i
mq9bh1bNWadvUFURSXSDE9Mx8VJrXsQuK9yDEAu2MLvFMVsWIsbU2vYTYIivMYhcmByMlIOS7OBH
5KSOrGgdD2EWj6lhH2XVPfvxzc3FQnDUxb9eieYqQXPFiPjqglTH5NmTa/JqFZ91tOWhj0Aksbyy
FXFKAiVkNQVZzmRkUwiFMpOZyIyoiSW4TUfW67vgKoaZWvia3JUYXEmtWocdjOEoT5zSFxNMjJ+a
UIU3OGSn1apNBZvDDWGm1sreggiFwGTOo9RvNMlNbNPdUiDgLoiqJwoHMtrKnTa4LZ6WHXXiN5vR
WZyWSTsBaFuzVUQQ+YSNWgbEZnpciNkfb5U5oL6h3eDoZh0xfjF5cjdbV6JMH7lSBttKBRSJ+FqE
IhapocZqLktaoc9Evmt5j6RL9V1I7bKi9ivb2asBm4vqgoYDRcAXqlVYtGEsKCNelmqYqkMuGnom
lXALllM/DsMA2kpUv6bUCRnf0DImW4k5VlKCqfnfUwYJtFLGlXwQcl8u6IE8zg+NPXR1wUb6Vvph
qVvbrB6kpY6d1Gy1dkfrUa1QTKJbKafMfNhiQyBabSXNIXzZ1mRBQ3jT2FW0Dx4Tb+PfVobco/9G
3+FZ/dr97PYMdzSUtRAnX4UtS7MystjsM6WmPcRuwj5J3z0S0ebuzWE70iRJEmWMWF3QlYuFjm14
oJuvhTDFXaVS+vKtzFDsmIrPGCQHD1NoWFzAcky77IGE9IiGW0kH1UCGyXgVwvLNEnvpZnr0hQlG
dJ1AX98JAzU51hqJsV5bydfBjezaoQueLqROJx1otsnoA9DGDDYp6Z6PHLTu+1AIMX1JmuxiKvPZ
QzTkq2tCqW+x06KZZoJha1LI9RrZx14O1NcuVCPSN4h3T3Nj6CF0+il6SF7GlFnF+7thE2Z2YRSQ
J45Nzk0FyNA0a10YndOdIV9iqSjNKFv1BX0QQZctoMSWYqhMAlTKCsJGfkooz9Mim1pL0g78sYVE
2FcRrRqiRMGpC5PgqoBnsZGGzHSFX+8JZbvdPiWSKES6MVq5eJCUb82AChbgt0QsKmp4CsZOnfJC
vKdHB0mmz63zL4TRRMGqDGnftjITVb9gmrbqApq7sacub7m55SymuWIgtmMUEiEItSm+RTqfygTw
k6Aba3JdTknNaQvx6vLsZjH57rh/9OJh3J8+TPuT78bf+cjEJmod0Ls0jyLM6clIrGHf2oxmR4d8
ua0eCpWQQPizoHPkofannmRD7TESwrq3YKfp9zKPFtuB/o1eJUzN96mO+Rb2g/lg1byiXHmobDb1
ero6TXyZNwDztX01KvOoHgRhVNDHd0A9Nh+aBUVWz6795jFuwBu4svmuB+t/1fZVmPkuLV6Zi916
MQrEXVY0zBSSaPPbrF8vL5kCeuGceajsms07MM+fxNoncTQgSkkKwqEXSpPR0WiKx+evqXX25icn
q/lq5U1H/nQug6n0prPA92er49XR6vjkOFBH+BPPcdJyQyKqv4/MUh0+NAqwrbtdMCbW3qrA9p2A
8nkqCE5Wvjc/Wo1WSgYnwUz6ah6M5sHJ7ETN/dnUD/yTyZzP05s4bWSo2c10l9PQKAKLi/ROJcg6
eQ15p+Qd4oMRFH+DsZP8ymRsv3H9EGZmNBkc9T5+/H8sKeNE
===END CRASH DUMP===

**Comment by onebone** [comment]
This bug is already fixed in 'php7' branch.
