### ISSUE TITLE
Shop plugins causing crashes.

### ISSUE THREAD

**Issue by tehkyy** [onebone/EconomyS#169]
PocketMine-MP Crash Dump Fri Sep 18 19:59:02 UTC 2015

Error: Call to undefined method pocketmine\item\DiamondSword::isPlaceable()
File: /EconomyShop_v2.0.6.phar/src/onebone/economyshop/EconomyShop
Line: 257
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: EconomyShop v2.0.6

Code:
[248] 				$player->sendMessage($this->getMessage("no-permission-buy"));
[249] 				$event->setCancelled();
[250] 				return;
[251] 			}
[252] 
[253] 			$money = EconomyAPI::getInstance()->myMoney($player);
[254] 			if($shop["price"] > $money){
[255] 				$player->sendMessage($this->getMessage("no-money-buy", [$shop["item"].":".$shop["meta"], $shop["price"], "%3"]));
[256] 				$event->setCancelled(true);
[257] 				if($event->getItem()->isPlaceable()){
[258] 					$this->placeQueue[$player->getName()] = true;
[259] 				}
[260] 				return;
[261] 			}else{
[262] 				if(!isset($shop["itemName"])){
[263] 					$item = $this->getItem($shop["item"], $shop["meta"], $shop["amount"]);
[264] 					if($item === false){
[265] 						$item = $shop["item"].":".$shop["meta"];
[266] 					}else{
[267] 						$item = $item[0];

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #0 [Protocol 34; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Darwin XXXXX.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
PHP Version: 5.6.10
Zend version: 2.6.0
OS : Darwin, mac

Loaded plugins:
AdvancedKits 4.0.1 by luca28pet for API(s) 1.12.0
EconomyAPI 2.0.8 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyAuction 2.0.2 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyCasino 2.0.2 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyLand 2.0.8 by onebone for API(s) 1.12.0
EconomyProperty 2.0.5 by onebone for API(s) 1.12.0
EconomySell 2.0.6 by onebone for API(s) 1.12.0
EconomyShop 2.0.6 by onebone for API(s) 1.12.0
EconomyTax 2.0.3 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyUsury 1.0.1 by onebone for API(s) 1.12.0
ItemCloud 1.3 by onebone for API(s) 1.4.0
SpeedBoots 0.1 by  for API(s) 1.11.0
EconomyAirport 2.0.4 by onebone for API(s) 1.12.0
EconomyPShop 2.0.1 by onebone for API(s) 1.12.0
SimpleWarp 2.1.0 by Falkirks for API(s) 1.12.0
SimplePortals 0.0.2 by Falkirks for API(s) 1.10.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrVWwtz3DaS/iu4ka9WuhqO5i2ZLvlKJ8u33rVjrSWfr8qTcmFIcIYRSTAEqdEklfvt93UDfMxI
SRRv7nbjdcrDBtD4+t0AuT/2yjhVPX80nY7nw/lkOu73VFHoouf/2Cu3OYZ6l18uP3x4/6HX76XK
GLki2oVMElFqUWWhiuJMhSJV5VqHItfBrSpTkBaLuFTpYvEqlqnOwuuNLkLfj81VIgMll4k6PALL
KE6I3/FloDOdbq/XOv9yNx4MB/NBvpbFsSmCY52pJf47VnaOwZzufHBJsF/PH89Ofur38qRaxRnh
3pkS6FCRUOPpKcYWpf3fszyRW1V4L43KwndWvMNn5To23suVKmvKopdpL1dFGhsT68xbVttF7+jo
BfiOp8+7/NSdykpiV17ILFBJosJDO2827MwrVFkVmaWPGvpP/DzGM/+YNAPPoEG1FWfCyXR+9cb3
ge9NZkra5vDIe5lu39GkQyeS23Ta8Iijw2ekus+LXl7EgVr0vhUvheV89CNPnn2lZpiHVUpffK53
YfP3vh0sev6iN6ip8BMJal/sg+mLRe9fJ/jh9Dqb/5pey6JSbu5JZy4J6qaTioCC1LPjeE7eridg
DytcTtP+VqlKfW50AD7fyBQLv4UNaFu7a9fybLv5z9h43rGxSozi7efjXdD/AudS5WFXfbQpa8Qu
mOzipRnA0xqFZd1Tf6voB5pHXFZZSfwtyOkOe1Kj3eHsTEQSqB2K2c60Do6n2N3uNN9h0VHJyc/x
pn8/D7EcEV4WsFDP/9w7GIrDI38n51yr4o4sFhTSrF9VaX641DpRMjuC5L2VylQhE8oDmEWhjP1G
g3mo7rD9soqTsOcPkUMKXepAY+Jk2u/JPOZpo8lgiGmruMTj8Il/sKCQt0m8pDWDE+ZQZZKSbu+V
LDZxJv6qtjIz3jsZ/IfWt95VoQeJDmQiRtPBbDAUzbQiU4n4LwvcDfriE5LvX6pEjJ+L4dgfz/3Z
RFy9uhHj4Wj2QhRal/59Vnnjk9PxYDocPP+f0fGHy7eX59eXX/77dP5lPhX3/A9w5escqGbIvSOC
+QMiH89jPA/t6BdtGtig8FMqg16Tdg2p9jy8oxgN/xqX/Oyk3SH3OwaYIt2PQJEVSkhhyLJJFcjx
aa5Kshrr/zMZAIWBCCqjMAY2CsV+L1Q5kNI6jBkdla+6hFRyNejuvli8kyxAoiVJePX++ubT+w9v
X4G0UUsDZwN1XZa58Y+PYe91tRwEOj1uYB3vCAPx28TckbhD7MpL5e10V15X4nakHbLWIbX7d9z8
O+J/J+554p6n7nmK569UkoOxWLhSCyyLxY4Uv6SxrEqSjiqqoGR5H6jDDeyrZPyPU0nXUr9FPVaS
VkWNZE9X04U0caYfasnR//hKCliQRkeNXE9X0V/08qF+iLivnOkfIqi+08tGG1aKp6viraSUvK8L
pn5FhvnVfPqVJk+ApxHRgXu6jKh/aLXL7UM5m5F9WWe/o6wO79dJnjuEjfQdyE/XwDX624fSM3Vf
8vk/zsoGeBo5HbjfICMdyx7KaA9r/zwyAk8roztsPlnGG3n/UEQi7ks4+cNl9VLeN3qxEj1dLR9N
VTwS3Zbc3+nMHzSG/5/GrwhQI2UN7wly0jnsItFVN1W3tF0Jn2D66dd3vY1IdH4KaHvb+14k0pin
NMDofx2PQaqOXZN//O/2x1nDlVrg61ypECeYnaa/Q+zIDbN2pd4x5ujrpW03e1KHv9evxkWui/KR
ftUNfEW38X/lmdJCahvPBuJvKLOPZ+CrR1Pw7x2F3Rj5LeV1Jx9fPT0hX8dpnqhPsuhK3CHuymtz
bEfe1zK5jYtb83eeRsHHlDcFDvuRKrDDdaI3ncdLY1RWxjIxV5e9VgmR23yxMAx4A8CLxQ74J2vg
Cl4C/g+UUNO7ehg+PG48rofhrxm+g/UXjL0vZ24x1aK2EH9VWrqOkAXkK1WdXwzfCw1cfxYrurk4
uGqexIXOongl6Dp6USyyg9dFLK5VLkan+OuP8fdEfLy54FsVmmD5eaTEsz/rVHl08dQZIPBno+ej
yZiIK0xLdajOhvSUynvP3iyaszFTTC43mUe3TopPkGfeiMibNWTyktiUZzqKiGJ17H1fqWJ7hpNn
SyoQE/WsVJfh2bs4U0Eho9IXV5fC3ovRoMwyXWWBchA8GaxjdadSuJ5xLGUCx/SiJF6tm50tRJnF
KYzg5llaqpcgpESIdAHGjbRu6VoWYaCL5jm/y+ufYRxFcVAl5fZsworiC7pSF55RZRlnK3NG5AQA
E6vsjS6SsKUZZPzOFHplcfbq8vX5x7c3RCWtDHLUOnr7cPZv/AfyVaX2jLxTTg663GruEAfbNCHn
EFRBRMB+UQET3bmRewgIKa54OqnYe3cFdxE3a2WUqEELWShRrpVA8jL4IUsRkN5LsVQizoKkClWI
H+KBWxKva/iT0BEx2OdpZKT6QmOkMMRSLAslb8VWV4XjJeJIQPlxFPMO0HsBn0q2xPgbtWnYHYcq
klC8ERud/akUMs+VLASpJoWwAXxgC/iCLpet3Ju1ykSVrwoZgsFgkZGzW2b+IhMHN+tCwVtBAgoc
AVeVXClB711YZS4wTIxnvt6Mf2Cl0tKLtQqcFLsLAaC+hlPZYBPfxrkKYznQxeqYno7fIji+6OjL
m+v3X+aT5974C62DGhtGvlggNa0WPdro01qR7ujVFb3XEPQay5QF67ekTJzIEnrjYdYmIwUO/FIl
mzRUd3GgxBrHxISNnIKxdfx2S74vB92sqzLUFCT2fQmBsaEo0DcZFVpY5xRwggIdSITrssRdLMXf
KNIxhSPecyM+v4OghaiAGyHJS40GGreLNZV0jERl4IRIx3AElg4F2L2uIz21Ax5gLQGqZX/JuaXm
A4kFxbGAu8IjCOpyK5wfYbrLRM1oq4aDTzEUrTO4lAxDUShjPY9gwtduAUeiveYkJOBvS0X6gNLV
95XkF42r+A5z72RSKXHotkQyPgJzux8yIFcMD9ZcrVThY5R2/qZKl9A2wuncbLPgRppbeHxxiwAa
0PhHGIH9sxaSZq0LNBgVXAKzTV9wzhEuN8Fl+1BDCq3xy0BWC+oP0dIqQ+TQFOZ9zS4DeRBchb5H
6iwVVABx2NWzBhpp1cJ5E1GE0hSKxL6Iyz/Rm9aCV4WK6gN74d5acQgJYGcxJo2wDJ6T0mdOFK2U
lYstx+p/JnoJxVIpFpYM70vjknJSqlZyuS0BSFxbKEPePDZkXhvpkGkTMzBWtqB6YfnU+jeslyiG
uyBN8fs44hIhR9Q7WvNDmIqddqUhh6bQIJ1hnxWD9BiYL4YLThWclUukGhn+k8OntuYXwFNV/LvA
m1LnvL9LVQ0ex80IhBTVPmQZh4b2rCGNhuOpRXWlilhzOaJYNLRhwAnZoWvibYStkGpC8jGe4SEe
lI00TuMa7WuGCIXeKDv8nFqtOtHdJJzhKdbttAUXXOKB6Gsj2aYj2uE9pRCqcDx98HAyie0aUagw
VwEVQsNqIaxWx3ZtIwA0qXLTijkZOjnN0aOAnNQTK/VKFkvY3wt0ktjujSLsUa2yOxEUt0a4NYjd
VGYVl9wuCrQjFXzhqF/nhD1ncN5g82oU1bkhbb1sIN7besdP8Ii1rpKwARIjg2wy0UInvxU5I4eA
8+HQyigOXnMkPMiN7Ct2dSNUVOi0TrG01o173azUsSmEcKbbd4VH/KezjrroYF1lt8bq+y17PSVE
JhIyOiiQNMK2un0OzwINiLGTPOoBqJdpeRGr2swuUJ7PHc5X2i7bNx8VAeqU7LIuB7uLm/Y7yMyF
yAvQsisrtfOFeiMaaKr3L7JaZJkqyRZN6wbXSGwlXMoSZwJqRCR1uSiA8CeXlTgAbWPqRm0yWqqm
JnK6Oeimr3qEAr/YlsS7L7xRx5mp9vG2XllDQVqZzW1WaWstd/lU6EKb7pwB7VoQHaaB+DPOLlDv
GXphOO7F1cc+1gLBEvlnE4fl2mZtju+GvcfsfXHiGoO2ZTCsmM7UgTgPEU9rmUR0QWa7mFDBz9xG
2NL6n866AdlU5w6vTp90eU/BR22QTPo2sGnjT3GGLhJiwW0UuzbV+o9X2VXdKbQ9OzVBtGiDXL+g
hj3LPffY7clw9lLLauW7puOlGFGz4SoLdZU8XHeUhvPYWtWd5sKZAmWk7RONODalLCs4zPEqsKpF
XgtNZ9P61LZzblB1E0m4IYk9MfFU514kLhs8gBJL9jC3xLNLfJFiaOXOExCILyEILlwOTspJSe7w
R+akE1nZ2R7KLB+i4Rhl0x188/7m0hecdfE3qHC4ynC4YkZ8S0GmY3hu5wZeY+LzHWsFOEcgkzhZ
2Yu4JAEJeU1JnjMeuhJCqcxWJnIjOsQS3ZUjF/W75DqH2V74msKVBFxKozqbHY4QKI/s0hdjDIwe
G1BlMDjioDWqi4Ld4YY409HK3XIIhcRk96PSby3Jh9j2dEuJgE9B1D1ROpDJRm6N5e34dPxoJ3+z
G53z10ydAmBcz1aDIPjEjY4MyM300xfTn18qC1BDi93y2K06YvR8/Ohq9q5M2XPkUlluSxVRJuIr
E8pYZIaGq71I6aQ+m/mu5R2KLvV3MR2XFR2/8q27GnC1qGloOFFE0pSsVdaLS2NRlfA0beCqHoVo
HNhSwkewgs7jcAywrVX1naaTkI0NI1PylZRzJRWYRv49Y5BCa2O8k/dC7usFZ6CA60PrD7u2YCf9
IMO4Mp1lzg7SoeMgtUud39F8dCuUk+jGyqvyEL7YAsRRW0m7CV+mtVXQAm8PdjX2wUPwLv9tZMxn
9O/pA0FnX7eew57pnoGxfHH6VdxynVeJ4+Z+U2naY7zIOCbpo1QCbe/lPPYjQ5okVabI1SVduTjq
yKUHuvnyhW3uapPSJ3JVjmbHdnzWITl52EbD8QKXE1rlNiSmM3rcSNqoITJNpssYnm+nuEs3e0b3
bTKi6wT6TE9Yqq2xzkms97pOvklu5NceXfDsUppyskPN13mcRbp1g7Um2/OWg859HxohxpfpbJtS
m88RYqBf0wClc4sbFu0wA4avSSFXK1QfdznQXLtQj0gfK94+Lo3FQ+zMY3hIX9aV2cT7q+ETdtS3
BigyzxXntgNkqs47F0YXdGfIl1gq0TlVqz6eIQHd0JV1K4bOJEKnrKBs1KeM6jxNcqW1IusgHjtM
hHtt0OkhKjScprQFrk54jhtZyA7X/M2eUjabzWMqSWKUG2uVy3tJ9dY+UMMC/g6EX6PhITg7nZR9
8Zl+eigyfT46f0scbRas25DubSsLUZ8X7KGtvpvm09hjl7d8uOUqZrhjILFTNBIxgLoS34HOuzIA
32ZjhqvIxOPnEw7Og3ZTX7x+e37jj1+c9GfP70f9yf2kP34xehGiINvkdVgWCg9INGenQ7GCmxv7
NJ0d8R23ui9VRnrh9z8XKEfdrz3JlbrPqAurns+x0+/lAU12D+b7JC7VxH7Q6tlvZ3+wX7jarxKW
ARqcdTOfblCzUBYtwf4/C+qnqkiahyhO4O/MemRfw0Vl3oyuwvZn2pLXiGj7uQDmf2fcm3X7ZUS6
tPe7zWT0idu8bIUpJWELu6JfX71lBPT2Kw/Q4LWLtxCev4p1v8SM3o6OSAvCo7dD4+FsOMHPZ2/o
BB3MT0+X8+UymAzDyVxGExlMplEYTpcny9ny5PQkUjP8Ec+w09WaVNR85ZdrE9+3BnAn+Pp9LIn2
QUXu+Akq76ei6HQZBvPZcrhUMjqNpjJU82g4j06np2oeTidhFJ6O57yfWae61aHhaDO7ksbWEJhc
6luVofgUDeWTkrdIE1ZR/I3OVvKbE/pGhSb8EOf2aTyY9X766X8BLIcZMg==
===END CRASH DUMP===

**Comment by onebone** [comment]
You are using PocketMine-MP for 0.12.1. And your plugin is for 0.11.0. You will have to get the plugin from 'php7' branch and it will be fixed.

**Comment by tehkyy** [comment]
Thanks for the help.
