### ISSUE TITLE
EConomyProperty 오류

### ISSUE THREAD

**Issue by cloud9350** [onebone/EconomyS#17]
EconomyProperty 플러그인 오류부터 설명하자면
콘솔창에서 help 명령어를 입력하면 10번중 10번으로 이 오류가 발생합니다.

16:31:42 [CRITICAL] Unhandled exception executing command 'help' in help: Object of class onebone\economyproperty\EconomyProperty could not be converted to string
16:31:42 [NOTICE] ClassCastException: "Object of class onebone\economyproperty\EconomyProperty could not be converted to string" (E_RECOVERABLE_ERROR) in "/src/pocketmine/command/defaults/HelpCommand" at line 83
16:31:42 [DEBUG] #0 /src/pocketmine/command/SimpleCommandMap(183): pocketmine\command\defaults\HelpCommand->execute(pocketmine\command\ConsoleCommandSender object, string help, array Array())
16:31:42 [DEBUG] #1 /src/pocketmine/Server(1820): pocketmine\command\SimpleCommandMap->dispatch(pocketmine\command\ConsoleCommandSender object, string help)
16:31:42 [DEBUG] #2 /src/pocketmine/Server(1799): pocketmine\Server->dispatchCommand(pocketmine\command\ConsoleCommandSender object, string help)
16:31:42 [DEBUG] #3 /src/pocketmine/Server(2205): pocketmine\Server->checkConsole()
16:31:42 [DEBUG] #4 /src/pocketmine/Server(2103): pocketmine\Server->tick()
16:31:42 [DEBUG] #5 /src/pocketmine/Server(1979): pocketmine\Server->tickProcessor()
16:31:42 [DEBUG] #6 /src/pocketmine/Server(1696): pocketmine\Server->start()
16:31:42 [DEBUG] #7 /src/pocketmine/PocketMine(442): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/cloud9350/pmmp/PocketMine-MP/PocketMine-MP.phar/, string /home/cloud9350/pmmp/PocketMine-MP/, string /home/cloud9350/pmmp/PocketMine-MP/plugins/)
16:31:42 [DEBUG] #8 (1): require_once(string phar:///home/cloud9350/pmmp/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php)
그리고 명령어 목록이 뜨지 않습니다.

-- 이건 추가 크러시 덤프
PocketMine-MP Crash Dump Fri Jan 16 15:53:11 CST 2015

Error: Call to a member function close() on null
File: /EconomyProperty_v2.0.1.phar/src/onebone/economyproperty/EconomyProperty
Line: 82
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: EconomyProperty v2.0.1

Code:
[73] 				++$cnt;
[74] 			}
[75] 			$property->close();
[76] 			$this->getLogger()->info("Parsed $cnt of old data to new format database.");
[77] 			@unlink($this->getDataFolder()."Properties.sqlite3");
[78] 		}
[79] 	}
[80] 
[81] 	public function onDisable(){
[82] 		$this->property->close();
[83] 	}
[84] 
[85] 	public function onBlockTouch(PlayerInteractEvent $event){
[86] 		$block = $event->getBlock();
[87] 		$player = $event->getPlayer();
[88] 
[89] 		if(isset($this->touch[$player->getName()])){
[90] 		//	$mergeData[$player->getName()][0] = [(int)$block->getX(), (int)$block->getZ(), $block->getLevel()->getName()];
[91] 			$this->command->mergePosition($player->getName(), 0, [(int)$block->getX(), (int)$block->getZ(), $block->getLevel()->getFolderName()]);
[92] 			$player->sendMessage("[EconomyProperty] First position has been saved.");

Backtrace:
#0 /src/pocketmine/Server(0): pocketmine\Server->crashDump()
#1 /src/pocketmine/plugin/PluginBase(88): onebone\economyproperty\EconomyProperty->onDisable()
#2 /src/pocketmine/plugin/PharPluginLoader(138): pocketmine\plugin\PluginBase->setEnabled()
#3 /src/pocketmine/plugin/PluginManager(633): pocketmine\plugin\PharPluginLoader->disablePlugin()
#4 /src/pocketmine/plugin/PluginManager(565): pocketmine\plugin\PluginManager->disablePlugin()
#5 /src/pocketmine/Server(1778): pocketmine\plugin\PluginManager->enablePlugin()
#6 /src/pocketmine/Server(1764): pocketmine\Server->enablePlugin()
#7 /src/pocketmine/Server(1694): pocketmine\Server->enablePlugins()
#8 /src/pocketmine/PocketMine(442): pocketmine\Server->__construct()
#9 (1): ()
#10 (0): {main}()

PocketMine-MP version: 1.4.1dev #945 [Protocol 20; API 1.11.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT ADMIN-PC 6.3 build 9200 (Windows 8.1 Business Edition) i586
PHP Version: 5.6.4
Zend version: 2.6.0
OS : WINNT, win

Loaded plugins:
AlwaysSpawn 2.1.3 by Comedyman937 for API(s) 1.0.0
AreaProtect 1.0.1 by Comedyman937 for API(s) 1.2.0
ArmorSpawn 2.0 by LDX for API(s) 1.0.0
BanItem 2.1 by LDX for API(s) 1.0.0
ChestRefill 1 by Falk for API(s) 1.0.0
ColorText 1.3.0 by Heromine for API(s) 1.4.0
EconomyAPI 2.0.3 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyAuction 2.0.0 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1
EconomyCasino 2.0.0 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1
EconomyJob 2.0.1 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyLand 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyProperty 2.0.1 by onebone for API(s) 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomySell 2.0.2 by onebone for API(s) 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyShop 2.0.2 by onebone for API(s) 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyTax 2.0.1 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
Farms 1.0-non-alpha by hm for API(s) 1.4.1
Gills 2.0.0 by Falkirks for API(s) 1.7.0
iControlU 1.3 by Falkirks for API(s) 1.6.0
iProtector 2.0 by LDX for API(s) 1.6.0
JoinCommands 1.1 by PixelGuy75 for API(s) 1.0.0
KeepInventory 1.2.0 by boybook for API(s) 1.0.0
KillMoney 1.1.0 by Topic for API(s) 1.9.0
LevelChat 0.0.1 by iJoshuaHD for API(s) 1.9.0
mcg76_PrivatePlot 1.0.2 by minecraftgenius76 for API(s) 1.0.0
MoreHealth 1.0.3 by iksaku for API(s) 1.9.0
NightPVP 2.0.1 by Falk for API(s) 1.0.0
OreFinder 1 by Falk for API(s) 1.0.0
PeacefulSpawn 2.4 by LDX for API(s) 1.3.1, 1.4.0
PerWorldChat 1.2 by EvolSoft for API(s) 1.10.0
RealTime 2.1 by Guillaume351 for API(s) 1.0.0
SignShop 0.9.2 by xionbig, xionbig for API(s) 1.10.0
SignStatus 1.1.2 by xpyctum for API(s) 1.0.0
SimpleAuth 1.6.0 by PocketMine Team, shoghicp for API(s) 1.8.0
SubnetBan 1.0.0 by  for API(s) 1.0.0
TapToDo 2.0.0 by Falk for API(s) 1.0.0
TimeCapsule 1.1.1 by Falk for API(s) 1.0.0
TimerBan 2.0 by onebone for API(s) 1.2.0, 1.2.1
Universe 1.0.0 by Comedyman937 for API(s) 1.9.0
WorldEditArt 1.0.0_beta_dev_#045 by PEMapModder for API(s) 1.0.0
WorldMonitor 2.0.0.000.0 by Steven for API(s) 1.2.0
xyz 1.0.1 by unerds for API(s) 1.0.0
EconomyAirport 2.0.1 by onebone for API(s) 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
HealthBar 1.0.0 by LegendOfMCPE for API(s) 1.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNoDAAAAAAE=
===END CRASH DUMP===

**Comment by onebone** [comment]
5.2 버젼 다시 다운로드 받아서 시도해보시고 안되시면 이슈를 다시 열어주세요.

**Comment by cloud9350** [comment]
@onebone 재다운로드후 서버실행했는데 크러시가 났습니다..
http://crash.pocketmine.net/view/780594

서버 환경은 Windows 8.1
아, 그리고 이슈 어떻게 여는지 모릅니다...

**Comment by cloud9350** [comment]
@onebone 
![default](https://cloud.githubusercontent.com/assets/5405019/5871210/fc633312-a31c-11e4-8e8c-a4b5e7c9465e.png)
