### ISSUE TITLE
Help massive error 

### ISSUE THREAD

**Issue by RobogamerFTW** [onebone/EconomyS#171]
this is the log of pocketmine-mp 1.4.1

14:22:23 [INFO] Starting Minecraft: PE server version v0.10.5 alpha
14:22:23 [INFO] Loading pocketmine.yml...
14:22:23 [INFO] Loading server properties...
14:22:23 [INFO] Starting remote control listener
14:22:23 [INFO] RCON running on 0.0.0.0:19132
14:22:23 [INFO] Starting Minecraft PE server on 0.0.0.0:19132
14:22:23 [INFO] This server is running PocketMine-MP version 1.4.1-980 "絶好(Zekkou)ケーキ(Cake)" (API 1.11.0)
14:22:23 [INFO] PocketMine-MP is distributed under the LGPL License
14:22:23 [ERROR] Could not load plugin 'EconomyPShop': API version not compatible
14:22:23 [ERROR] Could not load plugin 'EconomySell': API version not compatible
14:22:23 [ERROR] Could not load plugin 'EconomyShop': API version not compatible
14:22:23 [INFO] Loading EconomyAPI v2.0.8
14:22:23 [INFO] Loading EconomyAuction v2.0.2
14:22:27 [INFO] Preparing level "world"
14:22:27 [INFO] Enabling EconomyAPI v2.0.8
14:22:27 [NOTICE] [EconomyAPI] Auto save has been set to interval : 10 min(s)
14:22:27 [INFO] [EconomyAPI] Checking for updates... It may be take some while.

Fatal error: Call to undefined method pocketmine\Server::getLanguage() in phar://C:/Users/clare/Desktop/PE server/PocketMine-MP/plugins/EconomyAPI_v2.0.8.phar/src/onebone/economyapi/EconomyAPI.php on line 216

Call Stack:
    0.0151     342856   1. {main}() C:\Users\clare\Desktop\PE server\PocketMine-MP\PocketMine-MP.phar:0
    0.0184     337680   2. require('phar://C:/Users/clare/Desktop/PE server/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php') C:\Users\clare\Desktop\PE server\PocketMine-MP\PocketMine-MP.phar:1
    0.1473     456184   3. pocketmine\Server->__construct() phar://C:/Users/clare/Desktop/PE server/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php:442
    4.4582   10898936   4. pocketmine\Server->enablePlugins() phar://C:/Users/clare/Desktop/PE server/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server.php:1701
    4.4583   10898960   5. pocketmine\Server->enablePlugin() phar://C:/Users/clare/Desktop/PE server/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server.php:1771
    4.4583   10899056   6. pocketmine\plugin\PluginManager->enablePlugin() phar://C:/Users/clare/Desktop/PE server/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server.php:1785
    4.4592   10901728   7. pocketmine\plugin\PharPluginLoader->enablePlugin() phar://C:/Users/clare/Desktop/PE server/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/PluginManager.php:559
    4.4594   10901792   8. pocketmine\plugin\PluginBase->setEnabled() phar://C:/Users/clare/Desktop/PE server/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/PharPluginLoader.php:123
    4.4594   10902136   9. onebone\economyapi\EconomyAPI->onEnable() phar://C:/Users/clare/Desktop/PE server/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/PluginBase.php:86

14:22:27 [EMERGENCY] An unrecoverable error has occurred and the server has crashed. Creating a crash dump
14:22:27 [EMERGENCY] Please submit the "C:\Users\clare\Desktop\PE server\PocketMine-MP\CrashDump_Sat_Sep_26-14.22.27-UTC_2015.log" file to the Bug Reporting page. Give as much info as you can.
14:22:34 [INFO] Disabling EconomyAPI v2.0.8
14:22:34 [INFO] Unloading level "world"
bin\php\php.exe: Exit 1

**Comment by onebone** [comment]
You are using the old version of PocketMine.
