### ISSUE TITLE
Suddenly Crashed Because of this :/

### ISSUE THREAD

**Issue by ClanEmo** [onebone/EconomyS#172]
When I make a property and I accidentally add a wool above the sign it crashes my server. And also the sign is Blank

PocketMine-MP Crash Dump Sat Sep 26 17:28:23 UTC 2015

Error: Call to undefined method pocketmine\item\ItemBlock::isPlaceable()
File: /EconomyProperty_v2.0.5.phar/src/onebone/economyproperty/EconomyProperty
Line: 172
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: EconomyProperty v2.0.5

Code:
[163] 					}
[164] 				}
[165] 				$tile->close();
[166] 				$level->setBlock($block, new Air());
[167] 				unset($this->tap[$player->getName()]);
[168] 			}else{
[169] 				$this->tap[$player->getName()] = array($block->x.":".$block->y.":".$block->z, $now);
[170] 				$player->sendMessage("[EconomyProperty] Are you sure to buy here? Tap again to confirm.");
[171] 				$event->setCancelled(true);
[172] 				if($event->getItem()->isPlaceable()){
[173] 					$this->placeQueue[$player->getName()] = true;
[174] 				}
[175] 			}
[176] 		}
[177] 	}
[178] 
[179] 	public function onBlockPlace(BlockPlaceEvent $event){
[180] 		$username = $event->getPlayer()->getName();
[181] 		if(isset($this->placeQueue[$username])){
[182] 			$event->setCancelled(true);

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #28 [Protocol 34; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux 04cc676ef0c3 3.19.0-28-generic #30-Ubuntu SMP Mon Aug 31 15:52:51 UTC 2015 x86_64
PHP Version: 5.6.9
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
Alias 1.2.0 by ZacHack for API(s) 1.12.0
LeetAuth 1.1.0 by ProjectInfinity for API(s) 1.12.0
EconomyAPI 2.0.8 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
VoteReward 2.1 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0
FastTransfer 1.0.2 by shoghicp for API(s) 1.12.0
EconomyLand 2.0.8 by onebone for API(s) 1.12.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
EconomyTax 2.0.3 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
BanItem 2.1 by LDX for API(s) 1.0.0
HelpOp 1.0.4 by hoyinm for API(s) 1.9.0
AlwaysSpawn 2.2.2 by Philip Shilling for API(s) 1.12.0
PeacefulSpawn 2.4 by LDX for API(s) 1.3.1, 1.4.0
GrabBag 2.2.7 by aliuly for API(s) 1.10.0, 1.11.0, 1.12.0
BuyCraft 1.2.1 by Falkirks for API(s) 1.0.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
VIPSlots 0.0.4 by iJoshuaHD for API(s) 1.12.0
Slapper 1.1.3 by jojoe77777 for API(s) 1.10.0
PurePerms 1.1.12 by 64FF00 for API(s) 1.13.0
EconomyProperty 2.0.5 by onebone for API(s) 1.12.0
FactionsPro 1.3.2 by Tethered_ for API(s) 1.12.0
GoogleAnalytics 1.0.0 by  for API(s) 1.0.0
PocketDockConsole 0.0.14 by humerusj for API(s) 1.0.0
PureChat 1.3.0 by 64FF00 for API(s) 1.11.0
SimpleWarp 2.1.0 by Falkirks for API(s) 1.12.0
SimplePortals 0.0.2 by Falkirks for API(s) 1.10.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNO4lu3Diyv0J0Aqy9aLX7dqcHzoPHcXbykKM3djaLjQYBJVEtxZKoESm3ewb591dVpE47iZMY
2Oc5LJbIui+S8l8DHadisJ7M57PparUYz4YDURSyGKz/Guh9Dq8G5x/P375983YwHKRCKb5F2BlP
EqYlK7NAhHEmApYKHcmA5dK/EjoFkOvGWqSu+wL+/2sC4PU6VpuE+4J7iTg4BHxhnCCyo3NfZjLd
bwqZi0LvP15PR+PRYpRHvDhShX8kM+HBf0fCzMvtvP46wJgAYZDmePp5OMiTchtnKMCtab4MBEo4
Wc7gvaurfz7Du8ly3oIZyKIFeayBa+epn0gFUvxC75ft94m4FonzVAlNYh889vDXkGVix07j4uDQ
LjpuLSozmH7wWEexcp5qnn94nCd8Lwrn6Vbo1zwFSr/bZat62WeRKPEXAZ90GPwaFnbCeFHwvWXL
eXozcgdrdzCqxvve+M8he5zJnaF+PG4TqrArkQWvjG8cuIMPPX3/zk4LwfayZKqEB/Aar9yzSBTi
f9glzxnf8jhDMCwL4yIF+pbYpE0MtJppUusZz3yRJCI40EUp7Nxpa24cHlTTQXB0wIND52nH+w5J
b8dd81vN5Tjtn6UoxRcUiGQN1Vuucty4ihlXrmFGxubmGQ1JD8Z4eeklsc/CMvN1LDMmM3If4vmg
eTxHuZgRzwixqmzyuFSiyIBLYLEl/4ZEQA3UQhDzq0q9oK5YtfyvLX+F8nersVWj569ZBMJPF4Bl
sP4weDRmB4frTma4EMU1atUvuIqelWl+4EmZCJ4dDn4fDrYiEwVPMEBhlgJlAM3JaBmIa2DBK+Mk
GKynK4jwQmrpS5g5mw8HPI9p3mQ2GsO8baxhOL7nDywo+FUSe7hmdEwYShQcxi/jrLxh47nvL4+X
Ihz7MzYbTZ6Mxs505RCzYLdHs7HzziszXbKLVxv2Cix4Wm7ZbMImi/Viul5M2LvLMzYdTxbsZrX8
CFkGBIhywL8YLUdPYPQnhBEMpzAcm5cfparoA4AGCQ3q9KZQS6dJzOnBMmzGw472poSTl5ClC4Vm
+Q/3f+P+FSqcNPcBVYezACAyjBJgBs05HAQiB9ZwFbxTMtTP2oCUU5Yloq77CkZnCVdIP5EcBdq8
ubh8/+bty2cA2glPQV0YrLMySUCKl0LoU2CqxX0N6gow6QsA+eWT8PULSBpZDGn9oQRB+q5bcdE8
3U8gm/xONy9aIrWAbaGwzK26QtlS1xFmTJJXGqhMib8n9HtmxzM7ntvxHMY/qAPLhuvakgu8uG5H
inuo4l9Si7dix4ugpYoWsKUKEKWjhpfP/n0vFcx+wszP/u26DTfGc+8n2HOu9GXBMxWKoiVaB9x1
3vFo2rWziuQ2iv38wby2Qui6bTa6o0a6i8vTt5fvNm3ZBpHWuVofHUHijEpv5Mv0qEJ61MHSePlL
ngW33ZygP+Dn3xS/HUff4bwJ8FN7r2XuHlZ+Jq4voSq1E2sN6qWm8a3cRMXuFRQ7dil42hFz9uNh
WdF33RYn32fShrOjGkdj0Et+c9ueCOybc/bfS1s/6AWa39ROYCS6hw/8yjNsH1s6qSBdhUwG30xf
P5OmLNHvyVG/iSR/k7cYt4B+Xpp3OY/kPs66/vrkx5k32FzX0K5+f0MA8lpw2t1uN/L3nij80hNO
dIXui656muz4Xl3kfJd1ep4G2rXNtJ97N1GcxDm7gF/QTW0fLAXnhFdZtK7LiSWFLEEXARJ/IwNb
y20ENM5hmfQl7MI7xXP+Ve9rB9jPeGGHge/xxX8U3PuVb1uyVJC+pY67luJJXCa9zq5OK1Ve+RmT
GQKuuwV+PL69l1B3ZVWeiE9QWAoJ+I6anY5jm/QjXQhxlEIRFcVRJTuml3J/VvBQt/NLBeq3770U
85wnV3FxpR4qz8Ce3Ee6kGwaDu6TIQuY45NkbSla0F6tXHblOL+WyQXw9GBR2CLdN+eXSqRNNgJY
QawjfYXG+deLzUUidbv+16C2TOPbWTT+X6mikv/27MGkqjFCz9ow8X2lP/5EOKLgqEYBYl4kPM87
xqsg/f1Xr+Z/kp+kOMaf2wH6o02soey66b1zy6YsxEYUadtMDawvwqRXCpbz58/H4y7/P7Gn+Gjw
QaqsOGg9fn+rhittAmmwNM1afaB5q2NrHXV227bFA3bhtpP+sW6sOsOtW7L2Ie59dmB0SKZgVWcD
1kC7lp/1e4BLofEEMvj4YBHaIo67Lhp8R4mUcpuI04wnex37bWfuv+k3cN2dxwNVg2e8uHo9U+C+
PfK3APeMUiqJz+D/Z6AimYh2tN5618+uk36TWqaiKNWnh6p9tzj44T7gFqbbkIFNWmcR172cRaC+
446/nbEm34rYJnvc0kInaL6QyZCv5umn8xghwcoTp3ki3vOivU1pAXtbrL4m7uyAvj+C+8c2UBh3
reG5UiLTMU/U5ryln9ASd11FDO+AYdftMH+PsDDzN7LQvHPO0IX3w2F6Hz18Kxzaiv5KaPTlzA1P
lagNi9+UFo+seQHyQWNWGYKuAUa2FsQCz7cfbeoRO8MLoS3Da0K3cLNHz4uYXYicTRdsvFzPj9fT
cX2ojhNSqYOTlyV03rKE1YXgOr6mpYaSg9yfzKfz+TECdxFw5ySx0icyDBHCM1iZ+di307UP96NY
XIsUPECdyIww4ebHwZsHQXFzMpmuiDa/savUyXQMkYPoEvAlJ0zibVSTMOt5Fqegtw7OVHoVYAtq
SmUgTghNKAtgqYZZRBEvAl8W9Ti/zu3qIA7D2C8TvT+ZEDa6T9GycJTQGram6gTB5p4SPe5kJ4sk
aGBKiKA1Be+BT56/PL1EkHEo549SFHtLD3xROopfCzu+jsXOCUCteCt0MmutKqDW20n4OMq5UkA7
OPk7/VRQtNJ0OT4mK+FNSL2hGu3TBJ2EYX42F4bbEmTDCzN0Ewa6Ys0Rl/NqA27DLiOhBKuEZxxv
ISPBoB9R8MA189HwmnmCxZmflIEI4IHdck/EdSFTWBkigj5OxUMxZBIbC4UomQceeIU3n4XFxeKQ
gQ3jMCYKYL4CvAg2oID4tdjV6I4CEXIwoGI7mf1NM+yKecFQ0SkI64Nj7YF9hvd1Ru5dJDJW5rCP
DQDByM3Q5w2ytZuxR5cR7ECdBEDARcKzbcm3guE9OKnMxoeKYZxIwB//SUrFpWeR8K0U3YXAQJXt
RTbaxVdxLoKYj2SxPcLR0UvwgY8y/Pji4s3H5eyJM/2I60CNNaI1cyFFbd0BEnofUVOGV8F4o8zw
GwOlC9KvxoyccA16o9ekTeIU+IAnocmkgbiOfcEiaE0TMnIKiE38NCQhpykBcNgM6UBi5Jm7a2TG
3Ewyut0PDFunGMUM0wRwwuyOnl3HnP0TgwCmUDBUe/01XQ/jwosI1nH0Uqz7zFIxpuIWESsVOCGk
ZXAEkg76aPstBeqpeeEAWx4w1aA/p5iq8IDEDNMBA3cFj0BWvT2zfgTTbQTWbxs1PHofg6JlBi7F
g4AVQhnPQzbB166AHY4395gFGfibJ1AfoHTxR8npK5AtZNmMXfOkFOzAkoSkfAjIDT2IfKocDlhz
uxXFGt4i5ddl6oG2IZxO1T7zL7m6Ao8vriCARvj+HRiB/LMSEmdFhaT8rmG2GjLKXczmOHDZIagh
Ba0prJikFqhDCEvLDCIHpxDuC3IZkAeCq5A3kI+1ABWAOOTqWc0aatWw8yLECMUpGIlDFuu/4Wcw
Ba0KBFYE8sLeWnYAEoCd2RQ1QjI4Vso1YcJoxeRe7ClW/5FIDxSLJZkZMHhfGmvMSanYcm+vgSF2
YVgZE/FYoXlNpINMu5gYI2UzLEIGT6V/RXoJY3AXSFN0j49YQsgRFUVjfhCmJKfdSpBDYmigzoDO
lph0iLE1G7uUKigra0g1PPh/zj62N19hHovrTzGvtMyJvk1VNT8Wm8KPYbD8QZax3CDNiqXJeDo3
XEHbHksqRxiLir6ToYRsuavjbQKkINUE6GM0w4F4ECbSKI1LaGMziFDQG2aHL6nVqBN6o4QyPMa6
meZSwUUcEH1NJJt0hBTeYArBCkfTR7cno9i2IQUV5sLHQqhILcir0bFZWwsAmhS5asScja2c6vBO
hqzUMyP1lhce2N/xZZKYfg0j7E6tkjshK3YNs2sgdlOelVRy21xAO1KCLxwOq5zQcwbrDSavhmGV
G9LGy0bsjal3NAKPiGSZBDUjMWSQXcYa1tFvWU6cg4BLbDIzIvScIuFWbjTfVNHqWqiwkGmVYnGt
fe+0s1LLpiCENV3fFe7wn9Y67Ib9qMyulNH3S/J6TIgERM5ww4DSMNM1Dyk8C2hAlJnkYA+AvUyD
C1FVZraB8mRp+XwmzbK++cynVNWyNgZDxU57AJmpEDk+7BmEkdr6QkUIX9TV+6uo3CwTGm1Rt27g
GomphB7XsCnBRoRjlwsFEPzJZiUKQNOY2rcmGXmiromUbh6101f1BgO/2GvEPWTOpOXMWPuIrKMr
ViCtLJYmqzS1lnYLWOgCk+6sAc1aAFqeRuw32BCBek+gFwbHPdu8G8Ja4MCD/LOLAx2ZrE3xXaN3
CP2aHdvGoGkZFCmmNXXETgOIp4gnIX47arqYQICfWUJA0vifzNoBWVfnFq5Wn3R+g8GHbRBPhiaw
kfD7OIMuEsQCtxHk2ljr322yTdUpND07NkG4iL44wYY9yx07bPdksIcTXrld26bjKZtgs2ErC3aV
9LrqKBXlsUhUnaZrTQFlpOkTFTuCDZkuwWGOtr5RLeS1QLWIVru/zr5BVE0k8g2SmB0TTbXuheKS
wX3ccZOH2SWOWbJmKbza2v0ECESHEcguuBw4KSUl3sEPmRN3ZLpFHpSpb3NDMUqme/T6zeX5mlHW
hX/9EjZXGWyuCBGdVqDpiD1LuWavNvFpx1o+7CMgk1hZyYuoJAEn6DUaPWc6tiUEU5mpTOhGuCVG
uC1HNuq74CqHmV74AsMVBfS4Ei1iBxMIlDuoDNkUXkzueiG0PzqkoFWizQW5wyVixq2VPa1gAhKT
oYel31iSNrHN7hYTAe2CsHvCdGCutg1ui6flR538TW50msoyaxcAZXu2iglkH7HhlgFyMz6u2fzL
S3kB0MDwbnB0qw6bPJneuZq8KxNmH+kJg80TIWYiOofBjIVmqLGa05lW6jOZ74JfQ9HF/i7G7bLA
7Ve+t0cDthbVDQ0lipAuJau0aNNYWCY0TSpwVQdDNPZNKaEtWIH7cXAMQFup6pPEnZCJDYVf++In
/OjUWGBq+XvGQIVWxnjFbxjv6wX2QD7Vh8YfurYgJ33Lg7hUrWXWDtxyR0Fqllq/w/nQrWBOwmMw
p8wD8MWGQdhqC26I0FFcUwUN483GruJ9dJt5m/92PKY9+h/47bK1r11PYU9wR4Gx1mz1Q9hymZeJ
xWafsTT1ELsZxaQD2kOmzWGfQ36kUJOoyhRytcYjFwud2PSA52hrZpq7yqT4ZXSZQ7NjOj7jkJQ8
TKNhcQGWY1xlCSLSBQ53HAnVQILx1IvB880Ue4Rn9uhrk4zwOAG/zmYGamqsdRLjvbaTr5Mb+rWD
BzxdSF1OOtA8yuMslI0bRBJtTyRHrfM+aISIv0xm+xTbfIoQhTdPNaO4b7GvWfOaGAZf44xvt1B9
7OFAfeyCPSJ+o351tzSGH0Sn7uIH9WVcmUzcXw0+Yd6ujQGKzLHFuekACSrz1oHRGZ4Z0iGWSGSO
1WoIY5AAT+h01YpBZxJCpyxA2VCfMqzzOMmW1hKtA/HYQsLs9UGrhyih4VTaFLgq4VlsaCHzusKv
ekrBbyXuUAl+/206X+iUONZbM8CGBfBbJtYVN/QKnB13ymv2AR8dKDJD2jr/jhhNFqzakPZpKwlR
7RfMpq0646bd2F2Ht7S5pSqmqGNAsVNoJGJg1Jb4FutElRigJ4ZH4hi6VJIaamuG5+Lr6S/Hw8WT
m8lwdjMbTn+Z/BJAJTZZ6wA//fExw5ysxmwL/q3MaL44pMNtcaNFhgqhC6AzqEOtPwlAF2oNoRxs
B2sKmeEg93GqHag/kliLmfnrBcf8pcSf5s8ZzHeXng99TVTPx4PTLOBFAzB/7VWNyiKpB2Gc0Nc9
gNp+dBXqvH67DZrHtAFHEMjmhhrmf1Kdz5hI24H5U4vJaGHZTT1z2FujgKZxn+tGRM2R46Clj4vN
S0KCN2K5D81es3YPGqE/p7BPbIEXyROkxRy8MZqOF+MZPD5+gbtpf7laeUvP82fjYLbk4Yz7s3kY
BHPv2Ft4x6vjUCzghz0GSpsI9UbfUxBhqeKbxip2N28nTFDetyK0W1GAEj0Rhisv8JcLb+wJHq7C
OQ/EMhwvw9V8JZbBfBaEwWq6JHoqSmWjWEWRp7qSxkaXMFnLK5FBISpqyHvBryBlGEWN8POrPadb
FPogBv0kzs1oOloMPn/+P00r9XM=
===END CRASH DUMP===

**Comment by onebone** [comment]
Please use 'php7' branch.
