### ISSUE TITLE
Add multiple blocks

### ISSUE THREAD

**Issue by Pub4Game** [onebone/EconomyS#174]
Please add to Sell and Shop all of the missing blocks. For Example, 17:3

**Comment by onebone** [comment]
I will remove items.properties and use PocketMine's item list soon!

**Comment by Pub4Game** [comment]
When will it be?

**Comment by onebone** [comment]
When I turn on my PC. I don't when it will be.
Why don't you modify item.properties for temporary solution? :D

**Comment by Pub4Game** [comment]
@onebone I'm too lazy to do it

**Comment by onebone** [comment]
@Pub4Game Me too :P

**Comment by Pub4Game** [comment]
^_^ Thanks
