### ISSUE TITLE
Add buying things command

### ISSUE THREAD

**Issue by Pub4Game** [onebone/EconomyS#175]
Can you add it?

**Comment by onebone** [comment]
:D

**Comment by 64FF00** [comment]
@Pub4Game He says "No" :laughing:

**Comment by Pub4Game** [comment]
@64FF00 ? :D

**Comment by 64FF00** [comment]
@Pub4Game Jk heheheheh

**Comment by chroniclemcpe** [comment]
please dont add buying things, whats the point of the sign shop..
