### ISSUE TITLE
EconomyLand crush when nonOwner of a land try edit owned land

### ISSUE THREAD

**Issue by tompok76** [onebone/EconomyS#176]
Hello,
first thank you, your plugin is awesome, i have tried manytimes on version 0.11.1 MCPE.
Now I have mcpe (s15.minespan.com 26223) 0.12.1 version 35 Bleeding and when somebody who dont own a land try edit land which istn his/her, server crush down. Its a pitty because this plugins is realy cool. I attached server report. If you wish to try it by yourself, tell me for access via ftp or by game (WhiteListed).
Thank you very much and have a nice day,
Tom

Sorry but attachment (txt neither pdf doens work)
PocketMine-MP Crash Dump Wed Sep 30 07:46:03 MDT 2015

Error: Call to undefined method pocketmine\item\Sign::isPlaceable()
File: /EconomyLand_v2.0.8.phar/src/onebone/economyland/EconomyLand
Line: 613
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: EconomyLand v2.0.8

Code:
[604] 						$this->placeQueue[$player->getName()] = true;
[605] 					}
[606] 					return false;
[607] 				}
[608] 			}
[609] 		}elseif($info !== true){
[610] 			$player->sendMessage($this->getMessage("no-permission", array($info["owner"], "", "")));
[611] 			$event->setCancelled();
[612] 			if($event instanceof PlayerInteractEvent){
[613] 				if($event->getItem()->isPlaceable()){
[614] 					$this->placeQueue[$player->getName()] = true;
[615] 				}
[616] 			}
[617] 			return false;
[618] 		}
[619] 		return true;
[620] 	}
[621] 
[622] 	public function addLand($player, $startX, $startZ, $endX, $endZ, $level, $expires = null){
[623] 		if($level instanceof Level){

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #35 [Protocol 34; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux s15.minespan.com 2.6.32-573.3.1.el6.x86_64 #1 SMP Thu Aug 13 22:55:16 UTC 2015 x86_64
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
essentialsTP 1.1.0 by  for API(s) 1.12.0
VoteReward 2.1 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0
EconomyAPI 2.0.8 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomySell 2.0.6 by onebone for API(s) 1.12.0
SimpleAuth 1.6.0 by PocketMine Team, shoghicp for API(s) 1.8.0
WorldEditArt 1.0.0_beta_dev_#048 by PEMapModder for API(s) 1.0.0
EconomyShop 2.0.6 by onebone for API(s) 1.12.0
EconomyLand 2.0.8 by onebone for API(s) 1.12.0
EconomyProperty 2.0.5 by onebone for API(s) 1.12.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNWgtv20YS/it7coCzD6Is6mVHhQsYiXsXwG50ttMUFxXGilxKPJNclktaVov89/tmdvmQ7WvT
3B1w6SPkPma/ec+s+GuvjFPVm/uTyXg2Gp7Mxv2eKgpd9Oa/9spdjqnexd3F9fX7616/lypj5JrG
3sgkEaUWVRaqKM5UKFJVbnQoch3cqzLF0HIZlypdLm/idTafx2aRyEDJVaIOj0AqihOic3wR6Eyn
u0uZhXcPo8FwcDrIN7I4NkVwrDO1wn/Hyq5JsKa7HlQSnNObz/zx534vT6p1nBHevSWBDhUxMxtO
MLcs239elZvYeN/mhOvvlarUp1d43qnC+3atyu9lCqQ/iTNRFpX6BpRmw+kehc88NtsbK1RZFZmI
ZGLcnpPOvN1x2ozY99fu/bPCpjg6fBVnkRZ/OrMnH/1Ki/xhs6kBaVQWXlmNHDpegLseWfYy7eWq
SGNjYp0te30hi0LuLPlPy57eZqpY9n7qi2WPZun/R0dHjNr32+PUg8pKOq18I7NAJYkKD92qUbOK
YPNCEWempHU6EgsG+i4rVSGD8oKmHTfjjlCarQz/HWzm8Mj7ds9e3K59Bf5h9fnTp6rwZ/uq8Ftl
PVOkX6vNrqyV5tY1h4ysonjRiKTID1ZQebVK4kBEVRaUUImQYUhGeuhw98UriK4of6wf/oEH6PhH
+xe9JRBUQq+PeVwoA+6yKkmseEa1UEmgvLCri0sawEI4SgltwCU+9Q6G4vBovueyN6p4IAkGhTSb
t1WaH660TpTMjmAovbWCyciE3AmryKxwpD+YheoBCFZVnIS9+XgKXyx0qQONleNJvyfzmNf548EQ
69ZxidfhF/7BhkLeJ/GK9gxOmEKVSQpavcs4qx6F8acDQm9ymQ0CnYrRYDYYj7zpyXgwHvgDlcwG
j6ezu9lEHPji5mohbjeVOK/Wwh+L0Wg+nc79mfhw+0aMhv5U2KU4Jd/kOGMKYiO8/QIV4JVoD+3k
nTY1BgzwS8IvTTAyJCn4I4w7hiHdLujdYd8b7u/J0+cTZIWAWoDEp5+cCD/RHGIkqUJl5BpARJbX
74UqBz632OiofNsdSCUHxu6Ry+UTAImWxN/i/c3tx/fXl28xtFUrgxjem5ORgakfdKmu1VYWYYeP
zmCHi9HA73LQu3z7Y6/LxpBZrFn1ByP39/jrucMRy2WLZrm8ovEvYsxljPPFuw5jncGuejhH7amn
5/LUFzEIwTSM2r/t+8S9T/D+lQJwMKBZixxYlss9Lr5cFDeI889lwaNPhTH7fWH8rtF2hf0HODTA
07DowH0BjzdxmifqHJg7LHYG971x9sQbewuOl1eIOOJWyRSTZqPXmzjI95g+/XpTbrFQ+dTB5Zi7
uT2/vv2w6LLW25RlbubHx4ium2pFcfC4BXrcoQIBfNRFEl6EcXlelB0R7A3vCwHmfLdSpbxDqL87
GE6eeMDi4krmVzoMVfHMC75SBrlKZZ4yyeVyS8gUkCErLpdPcP6Wxl8USwv2+CZFIev94423sAH7
GAldHafSoGY53jun4xsbnb/gGzT6/+QbwNP6hgX35f7PxfMzHl1J/YeD4f+KR+oIGh7rluCLeVwU
GvVxuXvOZzPzlNfpf5FXh/frOM8dwob7DuTflQDVJ7IAxzDy2gu57hs4srGiYuZg0byJNzqL4rWg
rm1ZLLODj+j4blQuxkMxPJlPpvOhL67e3nIFRQtSXYZnNx+uf3j3w/mlkOZeRLoQMghQddD8dgM4
XhKb8gy9CQZklmnUxcpzNbwMNjFK1hQlinFLUN9tM49KS8X185k/451JordelMTrTbm3UmYxvBu7
o6gdTPWqGVlDBIgw6mxIbwCI45sxSwmtaBjoQtVb8oe8fgzjKIqDKil3ZyOmxsVxqQsPrVIZZ2tz
RsNciWNIhZ1X6qzP3l58d/7h8pZGrbF4P1eq2LmT3VAB9dYn0vMgl8YgHIZnf+E/4L8qtWfkQw3Z
qtKL87OnhXFnNtdFeTZCYzJmbclHJ3dzNhq2MMkrzjj20hhVvU2rMNilCdmIoCpLBGweFdinvoas
hPXdJiDvagGrQeGtjBK1fNCQKlFulIBlGzzIUgRkB6VYKfQuQVIh5uNBPLNOonWjU+yMiMBTmkZG
qi80ZgpDJMWqUPJe7HRVOFoijgTUHEcxnwAVFzCqZEeEv1fbhtxxqCIJHRux1dmfSyHzXEkYMmSe
gtkAxrcDfEG9qOV7u1GZqPJ1IUMQGCwzkrklNl9m4uB2gwzjJRgCCgSwdYVuXdAtBYvM6cfEeE80
6Me/sFBp65uNChwX+xsBoM5zKhts4/s4R7KUA12sj+nt+BKOdqeju3c37+9m49fe6I72QYwNoTn6
f5Wtlz066ONGkezogocuGQRd9piyYPmie8xMIkvIjadZmowUOPCkSlYp6oQ4UGKDIJewklMQti7W
HsndNcbNpipDTd5pLy8IjO1ERZBoo0IL65w8XVDQABLhWizxEEvxd3IcLGEH8tzMnLty2oj0txWS
rNSgmRXuFKsq6QiJysAIEaZhCMwdIrK71CI5tRMeYK0AqiV/wa5a0wHHgkKGgLnCIgjqaiecHWG5
c+xmthXDwccYgtYZTEqGoUCDby2PYMLW7gFHmqrgoChgbytF8oDQ1c+V5Ou4dfyAtQ8yqZQ4dEci
Jh+BuD0PAUWR73vQ5nqtijlm6eTvq3QFacOdzs0uC24pYsPx7+FAA5r/ACWwfdZM0qpNgdRTwSSw
2vQFBwrhwiBMtg8xpJAa3z+xWJCGaCytMngOLWHaN2wy4AfOVehHBO1SQQRgh009a6CRVC2cdxF5
KC0hT+yLuPwz3UcWvCtUlCDYCp/sFYfgAHoWI5II8+A5LudMibyV4n+xY1/9a6JXECwlZWGHYX1p
TJdceF/L1a4EIHFjoQz58NiQeq2ng6dtzMBY2IISlaVTy9+wXKIY5oIwZW/QQCVCjKhPtOoHMxUb
7VqDD02uQTLDOWsG6TGwuRguOVRwVC4RamT4fw6fCpzfAE8J+D8Cb0qd8/kuVDV4HDUj4FKUVBFl
HBo6s4bkD0cTi2qhilhzOiJfNHRgwAHZoWv8zcdRCDUh2Riv8OAPynoah3GdIYDBQyE3ig7/TqxW
nKiUEo7w5Ot22ZITLtGA97WebMMRnfCeQghlOF4+eL6Y2HYFKkSYq4ASoWGxEFYrY7u3YQCSVLlp
2UTpZ/k0Ry8CclyPLddrWaygfy/QSWLLN/KwF6XK5kRQ3B7h9sB3U5lVnHK7KFCOVLCFo34dE54Y
g7MGG1ejqI4NaWtlA/He5jt+g0VsdJWEDZAYEWSbiRY62a3IGTkYnA2Hlkdx8B17wrPYyLZidzdM
RYVO6xBLe928141KHZ2CCae6p6bwgv109lFpF2yq7N5YeV+y1VNA5EFCRv0CcSPqa2hyzwIFiLGL
PKoBqJZpaRGpWs3OUV7PHM632m57qj5KAlQp2W1dCvYUt+y/wDMnIi9AC6Es184W6oNoosnev0lq
mWWqJF00pRtMI7GZcCVL9ChUiEiqcpEAYU8uKrED2sLUzdpgtFJNTuRwc9ANX/UMOX6xK4l2X3h+
x5gp9/GxXllDQViZzmxUaXOtvf2vKGdzuHMKtHsx6DANxN/QNEG8Z6iFYbhvFh/62AsEK8SfbRyW
Gxu12b8b8h6Tn4sTVxi0JYNhwXSWDsR5CH/ayCSiX/NsFRMq2Jk7CEda+9NZ1yGb7Nyh1amTLh7J
+agMkknfOjYd/DHOUEWCLZiNYtOmXP9hkS3qSqGt2akIok18VUwFe5Z77rVbk6HNU6tqPXdFx7fC
p2LDZRaqKnm6rigNx7GNqivNpVMF0khbJxpxbEpZVjCY43VgRYu4FprOoXXTuNc3qLqIJNzgxHZM
vNSZF7HLCg8gxJItzG3x7Ja5SDG1dv0EGOLLCYILk4ORclCSe/QROakjKzvHQ5jlczTso6y6g+/f
317MBUdd/BtUaK4yNFdMiC8iSXUMz53cwGtUfL6nrQB9BCKJ45WtiFMSkJDVlGQ5o6FLIRTKbGYi
M6LumMZdOnJevz9cxzBbC9+QuxKDK2lU57BDH47ywil9McKE/9KEKoPBETutUV0UbA63RJlaK9d6
C4XAZM+j1G81yU1s291SIOAuiKonCgcy2cqdsbQdnY4d7cVvNqPzVFdZNwEYV7PVIAg+UaOWAbGZ
Hudi8u+3ygKjocVuaexnHeG/Hr24m60rU7aPXClLbaUiikR8V0MRi9TQULU3OJ3QZyPfjXxA0qX6
LqZ2WVH7le/c1YDLRU1Bw4Ei4vvdOiy6MBZVCS/TBqbqkYvGgU0l3IIV1I/DMEC2FtU/NXVC1jeM
TMlWUo6VlGAa/p8ogwRaK+NKPgr5VC7ogQLOD6097OuCjfRahnFlOtucHqRDx05qtzq7o/WoVigm
0VWZV+UhbLEFiFZbSXsIX8y1WdACbxu7GvvgOXgX/7Yy5h79Z/pd3unX7We353HPQFlzcfpV1HKd
V4mj5p4pNT0hvMzYJ+k7CAJtbwQ9tiNDkiRRpojVJV25uFHfhQe6UpsLW9zVKqVfwqscxY6t+KxB
cvCwhYajBSontMsdSESn9LqVdFAzyGMyXcWwfLvE3ebZHn1ugxFdJ9Cv8cKO2hzrjMRar6vkm+BG
du3RBc/+SJNO9kbzTU4fhLRmsNGkez5y0LnvQyHE+DKd7VIq89lDDORrGqDUt7hp0U4zYNiaFHK9
RvZxlwPNtQvViPRNwv3L3Fg8RM68hIfkZU2ZVfx0N2zCzs6tAorMc8m5rQB5VOedC6M3dGfIl1gq
0Tllq76gn7/osgVIXCmGyiRCpawgbOSnjPI8LXKptSLtwB87RIT7NaFTQ1QoOE1pE1wd8Bw10pCd
rumbJ0LZbrcviSSJkW6sVi4eJeVb+0IFC+g7EPMaDU/B2KlTnotP9OghyfS5df6JKNooWJch3dtW
ZqLuF2zTVl+Dczf20uUtN7ecxQxXDMR2ikIiBlCX4jvQ+VQGwE+CbtLJdTkltafNxXeX57fz0Tcn
/enrR78/fhz3R9/434TIxDZqHdJPewFFmLPToVjDvo19m0yP+HJbPZYqI4HwZxtvkIc6n3+QCXVe
kQ7WvTm7TL+XB7TUvZifk7hUY/u1ime/jPnFfr5ivwFYBahrNs16ujjNQlm0A/azu/qtKpLmJYoT
mDmT9u2HBVGZN7PrtH3ewHvtD7dY9E/jfsW1Hx+kK3uX2yxGTbjLy5aDUhKgsMPuzeKST6XnPEAt
1+7dgWH+MsY9iemA0BHnwqPfg0bD6XCMx1fvoLdofDJWchqG0+n49GTmT4YzeTocjeRkdSrHJ5OJ
f7oaTYZKvMJJiw2JhX9444O1iR9bobtm3S3widFrFblOE6N83qmaRoFEpTrBscPo5CQ4OT2dTac4
evx6NFbj4er1yesw5PPMJtWtCA07ltnnNLbCx+JS36sMeaZoRj4qeY+IYAXFPxXuJP9IQl+B0IJf
4ty+jQaT3ufP/wIO1Tzz
===END CRASH DUMP===

**Comment by Pub4Game** [comment]
https://github.com/onebone/EconomyS/tree/php7/EconomyLand

Download the plugin from the branches of "php7"

**Comment by tompok76** [comment]
I will try, thank you.
btw what does php7 mean?  I know update php is about 5.6.xxx ...... my server has only 5.6.2, it will work? thank you

**Comment by Pub4Game** [comment]
Yes, it will work

**Comment by tompok76** [comment]
I am sorry but doesnt load php7 plugins.
I put it in plugin folder like other and restart server, a console nor player know it.
My server has only php 5.6.2 and this is php7 like other Bleeding MCPE PocketMine-MP.phar, last stable is PocketMine-MP_1.6dev-35_mcpe-0.12_a7e5e33d_API-1.13.0.phar but i cant use PocketMine-MP_1.6dev-36_php7_f560d07c_API-2.0.0.phar	due to php7.
This is my problem, on my rent server is php only 5.6.2
Linux runs on my server, is there any option tu run this cool plugin?
Thank you very much for an advice, tom

**Comment by Pub4Game** [comment]
Do not worry into the account of versions of php, just install the plugin on your server)

**Comment by tompok76** [comment]
install means copy all of this https://github.com/onebone/EconomyS/tree/php7/EconomyLand into a plugnin folder?
Because i dont know what i have done wrong...
Thank you, you are so patient

**Comment by Pub4Game** [comment]
Just download the plugin and install it on you server

https://www.dropbox.com/s/c6pkag8le69irsj/EconomyLand_v2.0.8.phar?dl=0

**Comment by tompok76** [comment]
this is what did problems

**Comment by tompok76** [comment]
v208

**Comment by tompok76** [comment]
so simply question, what is php7 in the name of file?

**Comment by Pub4Game** [comment]
Pay no attention to the name of the branch development..... This plugin comes to 1.6 PM in PHP 5.6

**Comment by tompok76** [comment]
i copy your file (only this file) in plugin folder and a plugin doesnt work need API to work too, may i use "original" API?

**Comment by Pub4Game** [comment]
You have not set EconomyAPI? If so, download it and install

**Comment by tompok76** [comment]
I like your cat profile pict :)

**Comment by Pub4Game** [comment]
:+1: Subscribe to me :D

**Comment by tompok76** [comment]
I found this
http://jenkins.pocketmine.net/view/PHP/job/PHP-PocketMine-Linux/152/artifact/archive/linux/
php7 
is ti php7 for linux and good for minecraft?

**Comment by Pub4Game** [comment]
I'm sorry, but I can't go) My ISP has blocked this site

**Comment by tompok76** [comment]
after original API and your ecoland still same:
"30.09 12:55:50 [Disconnect] User test[/109.202.83.167:19132] has disconnected, reason: Server shutting down"

**Comment by tompok76** [comment]
my only hope is php7

**Comment by onebone** [comment]
I am not sure why your server is crashing even if you replaced Land. Could you try replacing Shop and Sell?

**Comment by tompok76** [comment]
Ive used only EconomyLand plus Api standalone, no shop.
By replace the Land you mean plugin not a word, do you?
Thank you very much for care, Tom

**Comment by onebone** [comment]
Did you try this version?
https://github.com/onebone/EconomyS/releases/download/v5.7/EconomyS_v5.7.zip
