### ISSUE TITLE
[EconomyShop] When someone buy an item with an shop sign the server crash

### ISSUE THREAD

**Issue by GreenNature-MC-Server** [onebone/EconomyS#179]
This is the crash report:
PocketMine-MP Crash Dump Tue Oct 6 15:12:45 UTC 2015

Error: Call to undefined method pocketmine\item\IronShovel::isPlaceable()
File: /EconomyShop_v2.0.6.phar/src/onebone/economyshop/EconomyShop
Line: 287
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: EconomyShop v2.0.6

Code:
[278] 					}else{
[279] 						unset($this->tap[$player->getName()]);
[280] 					}
[281] 				}
[282] 
[283] 				$player->getInventory()->addItem(new Item($shop["item"], $shop["meta"], $shop["amount"]));
[284] 				EconomyAPI::getInstance()->reduceMoney($player, $shop["price"], true, "EconomyShop");
[285] 				$player->sendMessage($this->getMessage("bought-item", [$shop["amount"], $shop["itemName"], $shop["price"]]));
[286] 				$event->setCancelled(true);
[287] 				if($event->getItem()->isPlaceable()){
[288] 					$this->placeQueue[$player->getName()] = true;
[289] 				}
[290] 			}
[291] 		}
[292] 	}
[293] 
[294] 	public function onBreakEvent(BlockBreakEvent $event){
[295] 		$block = $event->getBlock();
[296] 		if(isset($this->shop[$block->getX().":".$block->getY().":".$block->getZ().":".$block->getLevel()->getFolderName()])){
[297] 			$player = $event->getPlayer();

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #43 [Protocol 34; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux host13.adm24.de 2.6.32-37-pve #1 SMP Wed Mar 18 08:19:56 CET 2015 x86_64
PHP Version: 5.6.10
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
ServerAuth 2.11 by EvolSoft for API(s) 1.11.0
mcg76_SimplePortal 2.0.3 by minecraftgenius76 for API(s) 1.12.0
VIPSlots 0.0.4 by iJoshuaHD for API(s) 1.12.0
WorldEditArt 1.0.0_beta_dev_#048 by PEMapModder for API(s) 1.0.0
BanItem 2.1 by LDX for API(s) 1.0.0
EmptyWorld 1.0.0 by aliuly for API(s) 1.12.0
iProtector 3.1a by LDX for API(s) 1.9.0
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
PopupAlerts 1.3 by EvolSoft for API(s) 1.12.0
ManyWorlds 2.0.2 by aliuly for API(s) 1.10.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
PvPWorlds 1 by  for API(s) 1.0.0
PocketGuard 2.1.1 by MinecrafterJPN for API(s) 1.10.0
PeacefulSpawn 2.4 by LDX for API(s) 1.3.1, 1.4.0
MSpawns 1.5 by EvolSoft for API(s) 1.11.0
SimpleMessages 1.2 by Dutok for API(s) 1.0.0
EconomyAPI 2.0.8 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
PurePerms 1.1.12 by 64FF00 for API(s) 1.13.0
EconomyAirport 2.0.4 by onebone for API(s) 1.12.0
EconomyShop 2.0.6 by onebone for API(s) 1.12.0
PureChat 1.3.0 by 64FF00 for API(s) 1.11.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrVOw1v2ziWf4XnFtjkYPk7TuJDBsik6WwGTett0u3eVoOAkihbjSRqRCquZ9D/fu89UhLleGfS
j8XdpS0iPpLv+4uU+ntPJ5noLcaz2Qz+TedH/Z4oS1n2Fr/39LaAqd7l3eXbt2/e9vq9TCjFVwi7
4GnKtGRVHok4yUXEMqHXMmKFDO+FzgDk+4kWme9flTK/WcsHkS4WiVqmPBQ8SMXBISCMkxSxDS9D
mctsC8uKu4fJYDSYD4o1L4eqDIcyFwH8GwqzRsEadz1gSYFabzE5Of7c7xVptUpy5LqzJJSRQJEm
xycw5+v6z2eRKvE7LJgcn3YmfF3lSuiD53qdKO8HzYsPz4uUb0Xp/bAS+jXPQIJfDv8Lt56MujgJ
NnZgBjIBCD1MnSkX6VX+IHIty+3BofcDj6Ir0N9BLjaMHp6j5B/8Hmm190uf1QDQPO8AeCarXAPo
0PI3cwhavZwvrxYLoqk0z0OBJEsRVaG4BmVvDyxfLdKiTEJBZHRZiT7zXQ37PUvpaJ9oSuTRtXGd
Wp9AuYb4vUBWq7X2jGB99uGRHC0XuAZ13wHWrDXyzl0uBCoVmdAXKGiaiugARbBrj521SXxQL0fV
oNZBLR2nPSRnOel6kRWqwGV/q0Ql9vkKOyPNGaqnu95x2vqQGdf+Y0YTGpnnqfWjU2PWogrSJGRx
lYc6kTmT+Y+l4PeXKMfBjynEYztmRjwjxGltrOcBrgL+HOFp44HR0WmtT9BPopyoIP2b3bTpHweH
A7+38HsDB/jf+4D/3Ad8BeRT1Dg8v5RpJMo6zCzDra2sfrs8LwmGTEMi0CUYo7f40Hs2YgeHi05i
uhHlAxonLLlav6iy4iCQMhU8PwS36q1ELkqeYrqAVQp0CmTHg3kkHoCLoErSqLeYTSHXlFLLUMLK
6azf40VC68bTwQjWrRINw9ETf2BDye/TJMA9g2PCUOUcU3PvVZJXn9haKg2oeZRNZoNIsAnkyOnE
mx57xYNgz8bs5nrJ3kMivuYlG5+w0clifLo4mrOLy1s2GY2P2KeT+d18BoiLdQFojwDBGOn8BuEJ
Y0Q4MrN3UtV0AUCDlAZNglWoHaPG80qvcWS5dYB9R3+TwXgMAA5wWSq0y+WDTG9krFHlpLsPqLwx
8AAAkWO4AVuUbHqRKIBJ3AZzCja9cAEZp4zfUq4tbLlIJUcBb27P396+WwJgIwIFmQRga62LxXC4
2WwGAvhB1AN9j3Jm4ep4fneTZEUqlrLUxiGskHsmu8KOBtOutOh44G6xBu9KKnU874o9+XqxiRff
r3SSgtwOS93REux2lbfaWL65uX3/5u2rF64+8ipNQfa/Xy1vUqmVI3EDcuUcgZyzrpzJz1KtK/7X
F99Nvgaj7ztM/IlNFRgVInBdBYNQZsPkI+FYR8MGBYj5XpZpdBkl+rzUjqgdcL+TA0DguwDK7R3k
grtno9lJV/jl5TUvrmUEmasj/ujrpS9ExouMUPr+BjkTwBkvte/v8PlHdt2nE4fZ4U0G/Zz3zwtv
aaJ7qEshhhlXGiY7dEBtP/IcS6OjsRqyE/Bd5bx68Y/vpRRA5fuWqO9fI/BJfn2ZFXpL4jjMO8BH
xu5KwNOkSrffzbENOt8XyACZdleWJ3o3T8VHnkelBITDts55xR5jXr1+cfn3oSMzqCVZQiEToTZd
v1WLA3TVMh2M+R/b9fQb7doSfpJp9ykE8HjXF8vLoSMEmt80rD/LwDV/C9xN4TupzR5EHjlxH/3A
/p40v8f0e2rHUzue2fEMxl+pJMsG+I3h/KMMfL8jxRMiYSmLqjhPRdlJ8i60GwvTp9Tub4gFh/JT
g2B/2b7muXFsVy4HuGvjyZ+H+OjbQzwDBijC1Zekq4tKaZk9slIH3DXT/N9sJpe07+8w8lX2Wj4s
H5mrhTnSjV3JvlMdueFZJdKP67HvNzTRWE810JJy7U8VL6NOFLXQnYq4WxOv665QlD8vX383t+ui
BeE6HH1pNu1iGzrIhmRBAQetuEpvCr7JXTV04I4iJoPZHxYQN1d+SyHpMPAlcXdNOzoJxEK60Xb0
bz7QWKpf0hXsiTBzCLC3La5QOxNurA0mHcleVFref6/mrUu2PqQ4bDylkWsusR5XcgTuZvmT/xeV
HHhpKrmR4ik5qCrFUpRZJ4E2sK7DYvLvamI+e/lyNOp67PTrbXtn8EHs1Rw4j1/c19JO28O2WBzz
J2UhO0e3nYmvaOj+tDq6bvYltjUstfZtWHy6u9Nd9iNh7Q13V9L5/56keCnYiFnf0D/Njy/WXO+4
MYF2etHdc9k+J/6ztOvEyCPZei85XaUqOD30/oVzI1/t0ze7NiH5jNdrvAThodTWkUYXWYOilAW0
WQkm8N6zZTNiFzKPkxXDFyl+6efPbivB3oSazdl4ujg6XczG7N3tBV0A4rxB56GCz36CY2H+mmsg
z64vnFl0zLPx6Xg6QeAK1mYyEmc0yvgnz9y9qrPxiDZhkfIKc9ACrZ1NCbxZg/Bemih9RmNjCe/X
SpTbM5k7oBJcxULwcVBwpaBZjs7+k36AptTRHm55nssqD4Xlx+PhOhEPIhO5VmcyjmlNmsqNF6fJ
aq0tDcMvz5OMp6oDy2RQA2JZAuJGdIttDT1PKMtmXDwU9WOUxHESVqneno1Ja3SJDAdPTwmtk3yl
zhCc4hW3Uf8rGQTbFqaEiM5mo1kLwddvZ87lAIoDhdhT/EFYNvG6tjnvD7ZZit7BsF1gITlGBTzg
SwH0DwZCMdO9YUvnXS/BX9jtWijBaiYZB/XqtWAQ0QoeuGYh6lmzQLAkD9MqEhE8sEd+ibhuZAY7
Y0Swi1PxWPSZhJlSIUoW4EsJtpVVaXGxJGag7CROiALouQSHgtMTIH4tNg26YSRiDopWbCPzv2jG
i0LwkqFqMhA2BJNvgX2GryiM3Ju1yFlVrEoeAYKBn6OnG2QLP2fPbtfgW14KIOAi5fmqgk6E4StD
UpmNCpXAOJWAP/mNlIpbL9YitFJ0NwIDddiLfLBJ7pNCRAkfyHI1xNHwFUTGnYzvrm7e3M2np97k
DveBGhtEC+ZD/lr5PST0fi1Qd/jOFV+nMXz/qnRJ+tUlz1XKNeiNpkmbxCnwAU9Ck0kj8ZCEgq15
HqVk5AwQG0dvScYQFALgal3pSGJQmMYMmfGr0Ygfp+bXzFyxs1IovI4ERpAWqBwCwqgNnQHfLv+H
keAcQ5FhQsC19m6KPSSc/Q1zAiyh3FDfWi3obRluhBqyYRwdWklg3DJkrMotIlYp8FdI7+AzpAgo
WvaVNKq0nfCA50Aq0aK/pCxU4wHlMAxxBp4NzoOsBltmXQ6W25zVzLYae/Y+AZvIHLyPRxHqxTgp
sglueQ/scAXZC/MT6ikQqA9QlPi14vQyfZU8wNoHnkIOP7AkIXMfAnJDD3KlwOTsgeFXK1EuYBYp
v66yAEwBkXeutnl4y9U9BEd5D7E2wPl3CjSCNqmFxFXrEip0Bd4Dq1WfUY5hNm2Bd/dBDRloTWHd
JbVAQUNYVuUQZLiEcN+Qd4E8EIel/ARZVQtQAYhDUZE3rKFWDTtXMQYzLsGg7bNE/wW/JihpVySw
jpDD7uxlByAB2JlNUCMkg2elXBAmDGxM2OWWwvqnVAagWKztzIDB+7JEY/rKxIoHWw0MsRvDyoiI
JwrNa5ICyLRJiDFSNsNKYvDU+leklzgBd4GMRi8iEUsM6aSmaMwPwlTktCsJckiMG9QZ0FkRkx4x
tmBH44lPeYVSuIa8xKP/4wJgc/SH7GPR/Cb2lZYFcWAzW8ORxaYYhBU2DSKq+UGaj5iCbi+RVLww
HBXSCyl9W+aakBsDJcg2EboZrfAgJIQJNkr6MoccBkEKisME8a/0avQJjVBK9QDD3SzzqTwjDgjA
NphNRkIKbzCLYD2k5YPHi1Fq29uCBgsRYtlUpBXk1ajY7G0EAEWKQrViTkdWTnW4lyEr9dRIveJl
AA7ghTJNTaOHQbZXq+RPyIrdw+weCN+M5xUVaJcLaF4qcIXDfp0WdnzBOoNJrXFcp4esdbIBe2Oq
I43AIdaySqOGkQSSyCZnLevouKwgzkHA+WhkZGTPXlIoPEqP5CtmdyNUXMqszrK41857bmJybApC
WNPtusIe/3H2YcMdrqv8Xhl9vyKnx5xIQOQMjx4oDau/2cH4LKFdUWaRhx0Ddj4tLkRVm9nGyenc
8vlCmm275jMfl9TbXAyGil32HWSmWuSF0NALI7X1hZoQTjQF/A9R+XkuNNqiafTANVJTDAOu4cSA
vQjHnhhqIPiTTUoUgKaNtbMmFwWiKYuUbZ652auewcAvtxpx95k3dpwZyx+R9XTNCqSVo7nJKm25
pQMA1rrIZDtrQLMXgJanAfsrHGzoM5gMe5aL5bs+7AUOAsg/myTSa5O2Kb4b9B6hX7Bj2xu0XYMi
xThLB+w8gnha8zTGD/FMIxMJ8DNLCEga/5O5G5BNgXZwOa3S5ScMPuyEeNo3gY2E3yc59JwgFriN
INfGcv9umS/rZqHt8LEPwk0bSPU+tvd54dmh25bByUwE1Wph+44f2Bj7DVtYsLGk6bqpVJTH1qJu
Nn1rigUbt62iYkNoeXUFDjNchUa1kNci1bpdfaTrHDJE3UYi2yCIOV7RUutdKC3ZOwQdanIwu8Uz
WxYsg6mVPXyAPOZbPOD2AV/CmJzEO/ghceLxTTvkQZf6MTcUomS5Z6/f3F4uGCVd+BtWcBLL4SRG
iOi2Fi1H7FnKDXuNhc87xgrh0AGJxMpKTkQVCThBp9HoOJORrSCYyUxhQi/CEy/CbTWyQd8F1ynM
dMM3GK0oYMCVcIgdjCFO9lDpswlMjPdNCB0ODilmlXC5IG+4Rcx4DrP3IUxAXjL0sPIbS9KJtz0K
Yx6gcxB2T5gNeLrhW2VwWzyO73bSN7nROX0T6eR/ZXu2mglkH7HhoQFSMz5afvdv5SVAI8O7wdEt
OqCY0d7d5F25MIfOQBhsgYgxEdF9CiYsNEOD1dyyOJnPJL4b/gA1F7u7BM/WAg9gxdbeI9hS1PQz
lCdi+pahzoo2i8VVSsukAlf1MEKT0FQSOoSVeHjXeDxtVPVR4lnIxIbi9rSKTo31pZF/xxio0NoY
1/wT47t6gVNQSOWh9YeOLWakzrc8SirlbLN24JY7ClKz1fodrodmBVMS3mZ5VRGBL7YMsjAV3BCh
a7c2GxnG26NdzfvgMfM2/W14Qqf0X/FjVmtfu5/CnuCeAmMt2MlXYStkUaUWm33GyrSD2M8pJj3Q
HjJtLu088iOFmkRVZpCqNd7PWOjYpge8Jlsw09vVJsVvPKsCeh3T8BmHpORh+gyLC7Ac4y5LEJEe
4XDDkVADJBjPggQ83yyxN3TmlL4wyQgvFPA7U2agpsRaJzHeaxv5JrmhX3t4G9SFNOWkAy3WRZLH
snUD/FB0YUgOnMtB6IOIv1zm2wy7fIoQBfpVDaN4bLHTrJ0mhsHXOOOrFVQfez3QXLxgi4hf297v
l8bwg+jUPn5QX8aVycS7u8EnzOzCGKDMPVub2waQoLJwrowu8IKRbrxEKgusVn2G3+3hdQtwYjsx
aExiaJQFKBvqU45l3tlhK2yFRoKwdGaYfRvhdBIVtJ1KmzpX5z2LFA1lpmsyakc3+NJ2j2bSBKqO
Mc7lJ45l1wywbQH8lolFzQ1Ngc/jcXnBPuCjB7WmT+fnXxCjSYZ1N+Le0JIQ9anBHN3q+2s6k+27
8KUjLhUzRY0Dip1BP5EAo7bSO6wTVWKAnhhed2MEz2jUUFuwl6/ObxfH/emePxO68BaftMhRYHrj
eQHlxv2YGV3FHUPeX/UWFBv9XhHiYjtQv6aJFlPzwbVnPu7+zXyBbd79BiE0MOtmPV6n5hEvW4D5
/zH1qCrTZhAnKfgzoR6bF8qxLprZVdQ+Zi14DRFrPjyE9R+Vfdtl3j9ngbnsbRZDH7gtdCuM5shb
5Ip+s3xFHOAr3yKEBq7dvAXh6aNv+8SOBsgpaoF5+LJoMjoaTeHx+RUekMP5yUkwD4JwOoqmcx5P
eTidxVE0C46Do+D45DgWR/DDngOl5RpV1HxbVUiVfGoNYA/odgF9Ev5WxPZ0CVCiJ+L4JIjC+VEw
CgSPT+IZj8Q8Hs3jk9mJmEezaRRHJ5M50VPrTLY6VBRGqitpYgwBi7W8FzkUl7KBvBf8HtKAURS9
Nt1yeo0ytl/r/JYUZjQZHPU+f/4f95wMhg==
===END CRASH DUMP===

**Comment by Pub4Game** [comment]
Use a newer version of the plugin!

**Comment by GreenNature-MC-Server** [comment]
I'm using EconomyShop 2.0.6 and EconomyAPI 2.0.8!
Are there not the newest versions?

**Comment by Pub4Game** [comment]
Yea, https://github.com/onebone/EconomyS/releases/tag/v5.7

**Comment by GreenNature-MC-Server** [comment]
Ok! Thanks! forums.pocketmine.net don't updatet EconomyS yet! xD
