### ISSUE TITLE
Economy Shop/Sell 플러그인에 물건을 사거나 팔려고 하면 서버가 크래시 되며 꺼집니다.

### ISSUE THREAD

**Issue by kim-min** [onebone/EconomyS#180]
pmmp 1.6버젼 빌드 30을 쓰고있습니다. 이코노미 sell,shop 플러그인으로 표지판을 만들어 터치해보았더니 갑자기 크래시가 발생하며 꺼졌습니다. 

에러내용

PocketMine-MP Crash Dump Wed Oct 7 20:33:59 AWST 2015

Error: Call to undefined method pocketmine\item\Item::isPlaceable()
File: /EconomyShop_v2.0.6.phar/src/onebone/economyshop/EconomyShop
Line: 287
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: EconomyShop v2.0.6

Code:
[278] 					}else{
[279] 						unset($this->tap[$player->getName()]);
[280] 					}
[281] 				}
[282] 
[283] 				$player->getInventory()->addItem(new Item($shop["item"], $shop["meta"], $shop["amount"]));
[284] 				EconomyAPI::getInstance()->reduceMoney($player, $shop["price"], true, "EconomyShop");
[285] 				$player->sendMessage($this->getMessage("bought-item", [$shop["amount"], $shop["itemName"], $shop["price"]]));
[286] 				$event->setCancelled(true);
[287] 				if($event->getItem()->isPlaceable()){
[288] 					$this->placeQueue[$player->getName()] = true;
[289] 				}
[290] 			}
[291] 		}
[292] 	}
[293] 
[294] 	public function onBreakEvent(BlockBreakEvent $event){
[295] 		$block = $event->getBlock();
[296] 		if(isset($this->shop[$block->getX().":".$block->getY().":".$block->getZ().":".$block->getLevel()->getFolderName()])){
[297] 			$player = $event->getPlayer();

Backtrace:
#0 /src/pocketmine/Server__32bit(0): pocketmine\Server->crashDump(boolean)
#1 /src/pocketmine/plugin/MethodEventExecutor(36): onebone\economyshop\EconomyShop->onPlayerTouch(boolean)
#2 /src/pocketmine/plugin/RegisteredListener(96): pocketmine\plugin\MethodEventExecutor->execute(boolean)
#3 /src/pocketmine/plugin/PluginManager(673): pocketmine\plugin\RegisteredListener->callEvent(boolean)
#4 /src/pocketmine/level/Level__32bit(1669): pocketmine\plugin\PluginManager->callEvent(boolean)
#5 /src/pocketmine/Player__32bit(2002): pocketmine\level\Level->useItemOn(boolean)
#6 /src/pocketmine/network/RakLibInterface(140): pocketmine\Player->handleDataPacket(boolean)
#7 /src/raklib/server/ServerHandler__32bit(90): pocketmine\network\RakLibInterface->handleEncapsulated(boolean)
#8 /src/pocketmine/network/RakLibInterface(79): raklib\server\ServerHandler->handlePacket(boolean)
#9 /src/pocketmine/network/Network__32bit(159): pocketmine\network\RakLibInterface->process(boolean)
#10 /src/pocketmine/Server__32bit(2470): pocketmine\network\Network->processInterfaces(boolean)
#11 /src/pocketmine/Server__32bit(2222): pocketmine\Server->tick(boolean)
#12 /src/pocketmine/Server__32bit(2100): pocketmine\Server->tickProcessor(boolean)
#13 /src/pocketmine/Server__32bit(1701): pocketmine\Server->start(boolean)
#14 /src/pocketmine/PocketMine(464): pocketmine\Server->__construct(boolean)
#15 (1): (boolean)
#16 (0): {main}(boolean)

PocketMine-MP version: 1.6dev #30 [Protocol 34; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT DESKTOP-GH0ITHM 6.2 build 9200 (Windows 8 Business Edition) i586
PHP Version: 5.6.6
Zend version: 2.6.0
OS : WINNT, win

Loaded plugins:
CommandLogger 1.0 by cr0sh for API(s) 1.12.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
EconomyAPI 2.0.8 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyLand 2.0.8 by onebone for API(s) 1.12.0
EconomySell 2.0.6 by onebone for API(s) 1.12.0
EconomyShop 2.0.6 by onebone for API(s) 1.12.0
Fishing 1.0.0 by Akum for API(s) 1.5.1
GoodSPAWN 0.4-alpha by ifteam for API(s) 1.4.1
Jail 1 by Steven01 for API(s) 1.8.0
MyDearest 1.1-alpha by ifteam for API(s) 1.4.1
Portal 3.0.1 by ljyloo for API(s) 1.0.0
UselessTNT 1.0 by H2oLife for API(s) 1.12.0
ColorTag 1.0 by May for API(s) 1.4.1
AnnouncePro 1.1-alpha by hm for API(s) 1.4.1
CountryIntroduce 1.0 by JacobYun for API(s) 1.12.0
NPC 1.1 by onebone for API(s) 1.12.0
Login 1.0 by DeBe for API(s) 1.12.0
JQM 0.1 by Akum for API(s) 1.5.1
FixBiome 0.1-Alpha by hm for API(s) 1.12.0
InfiniteBlock 0.1-alpha by hm for API(s) 1.4.1
BlockElevator 1.0.2 by Mentha Haplocalyx Alcatraz_Du for API(s) 1.9.0
Farms 1.1-alpha by hm for API(s) 1.4.1
Boat 1.0 by onebone for API(s) 1.12.0
iProtector 3.1a by LDX for API(s) 1.9.0
FireWork 0.1 by Newtube for API(s) 1.12.0
OverTheServer 0.1-Alpha by ifteam for API(s) 1.12.0
SimpleArea 2.0.0.24-alpha by ifteam for API(s) 1.12.0
ItemCasePE 1.0.2 by aliuly for API(s) 1.10.0
viewcode 0.1.4 by oml for API(s) 1.4.0
InvenSave 1.0 by hm for API(s) 1.4.1
NameTagPlus 2.1 by Steven01 for API(s) 1.4.1
fixCreativeItem 1.0 by H2oLife for API(s) 1.12.0
EconomyPotionDispenser 0.0.1 alpha by Khinenw for API(s) 1.12.0
SProtect 0.2.0 by xionbig, xionbig for API(s) 1.10.0
SignCommand 1.1-alpha by hm for API(s) 1.4.1
iControlU 1.3 by Falkirks for API(s) 1.6.0
Sneak 1.1 by CrazedMiner for API(s) 1.12.0
ShowMoney 1.1 by DeBe for API(s) 1.12.0
SignWarp 1.5.1 by aliuly for API(s) 1.10.0, 1.12.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNPAtz2zbSfwWjZObkG1GmHpZtdZwZx3ba3NmxGjuT3pUdD0SCEmuSYAnSstrJf/92FyAJynai
pG6/811tYgHsC/sCCOaPThElojMdjMfj4XAwHB32OiLPZd6Z/tEp1hl0dc5uzt6/v3zf6XUSoRRf
IOyExzErJCvTQIRRKgKWiGIpA5ZJ/1YUCYA8LypE4nlv4fd0GqlZzH3B57Ho7gCqMIoRz+6ZL1OZ
rK+WMru5G/bd/qSfLXm+q3J/V6ZiDv/tCj1GwRh7PGCJgU5nOjzY/9TrZHG5iFLktzXEl4FAYYb7
B9DnFdX/PolYiT9gwHD/sNXhFWWqRNF9WSwj5bwqePbzyyzma5E7rxaieMcTkOCXne9w6oHbxkmw
gQXTkCFA6GFkddlI36Z3Ii1kvu7uOK94EKDOuqlYMXp4iZL/7HVIn51feqwCgM55C8ATWaYFgHYM
f2OLoNHL8eztdEo0VcFTXyDJXASlLy5A2euu4atBmuWRL4hMkZeixzxbw17HUNp7TDQl0uBCG02l
T6BcQbzOXJaLZeFowXrs5wdyNFzgGNR9C1ixVss7sbkQqFRkojhBQeNYBF0UwYzdt8ZGYbcajqpB
rYNaWka7Q8Zy0LYiI1SGw34sRSkesxV2RJrTVA83reOwsSHdruxHt4bU0s8jY0eHelmzch5HPgvL
1C8imTKZvs4Fvz1DObqvY/DEps20eFqIw2qxXs5xFPBnCU8Tu1pHh5U+QT+RsryC9K9n06Sfujt9
rzP1On0L+J/HgP99DHgO5GPUODy/kXEg8srNDMPNWhn9tnmeEQyZhkBQ5LAYnenPnRcuozjSxKTd
K5HfifzmZjScR0XX3Zm2ApbudV75OVfL0zLJunMpY8FTjFgvBg+w6ZCze0Ghj9R8di/8Ehy5O5oA
bhPAPM+KYJ5neY/zSqaa92tZ+ssWueFT5N6LRaQKAT57jn9TEPxwsiGJHup5j7DmvBL0JFrURk9R
m9GfC56Cx+bdyf7oCUoPuQI9QpbQ1miTGj8gFePy75IRVEszmEwOn6DU4ugpInsPiGg9V/iHrjvc
wE9ceB6x4bwqlcAwcJm20E4eoE1FsZL57e57fnsezd+moIIQ7K87GG9a18wEhiVPg1ic8oLPOPa2
COxrAjm/jaP5riKDNFb7A82rJTjcxG84gaVos1JRPEt9nqky5gXEQZvmwdZC7eOaaN48TzNXeY3h
riL2iGiHT5J5p//Wa793uLVoWS59SCdtR/2S3w/H+08qz/BSY65pbdAYfIkG/DwRXooIAmwL2fBL
yAau+xlkM80qhJ0W1tEXsA723cETWKE0yNurN3jotjN6vIDH7ngyfgLTzQ2EOwX5z9/At8e6SL0N
nDAKyn8kPEo/NV2/9DoLDCk8xlIO8CrId5ASBv1JIO5g5ryM4qAzHblQB+aykL6EkaNxr8OziMYN
Rn0Xxi2iAprulj8wQRs7zunvE4Yy5Vgwdz5GaSBXir27ZqdnV/++vpw53//gvr3+4YJN+kNGDLFD
CDOsWw09YK9LBcpRip0FEabsHRbtQc0CTC8zwLkH1S+2foeyCZpDaLq680YqpPn23btrAFBjBcVu
XfYq1MuJTBJwvnO5gMCIAMNqG95r6Q/x8xKSRK4wZfq5q5aobtLbz6g4KMoRIFIsg4AtKgI7gciA
SZwDfUqGxakNwOUD9D6E0wt8hEpdchRpdnl1/fHy/fkpgFZirqCq60zTMo5BklNxdw0LrizOa1Cb
6YG7yXdjiuxa8KQlwag/+FYBKvqeZ3FiRLm6Pn5//WFmC9JZFkWmpru7YGbLct73ZWI5yW6NA4Rt
inFLXAtoC4zbooO2vKayaMmplQLaMX+H9d8B/R2Z9si0x6Y9/nb9bBY4wEtd32gptlh3M/6co9Fv
6oKg36CML5qtreyvkDAGfmoRDXPby3gFm5CHMhJ0U8bJ/5+MCvhpylTN3FfIiPvuhzLq3fj/joyb
pfh2Mr6J1DJKF5Z8FWQjrG4GqOPbsh2V9r7d6xCX5xnC9cN2AnwvZXA1O/74zhKhgdlCuP2xw+Ns
yduCRGGxGWD/RADR2DyvZsF63E6gf/HIdilqWmIMWsxfFbhndAct9g++PcEhNc8zNLdg9mJ9Kngu
VGFx3MA2ktzfp/2aBetxO4FmMi+4rX8DsEWBvEMZxxIj/nUdS/kge32jGJombLDoLxYcJzFX6gsS
PJqs1zlPogBLiF2NbReT9QeIiFC1XUPx1UhqAT9bUv0wlOdRKJ6tqDL4PK/FwGcltSSsuAGpTmQs
82u+aFWKBvRZiS74+rkssCLoeRbpLezuOE1lmfoCdj4W+zZ0C2daPpsjWYQ9r83FFsKc4GFnvoad
Zi7xHLa1IBtdn12Yf3Ffzv9Tps9ma5vkcZkeMLSFhO9mJ5ZQ2NpYnmcoBLZJ/mnmf82OBHZMOL9m
XLc/uwSn4vXz8U30PK8i+7XRDHlxrQ2IMzN7RUybP17YWRNa7dw/+KvLFyBJv7atu+5fRzIRrcLL
gDYYd46/6Ol/Zk2qnFmRb562k+RtGkYpAOiY3RKnDd+U6S+NXi3SnrfJyRZC0dCzWNzxQtonD234
Zok83EgrIi2WnP3AM5jF4/U9O459XuT895vTsiXr4bcvX4sjz9tkcBtT5Hlin1Ho9t+abpZof0jW
/NlykSS3605qfjaW/WVheA6kvyYOR5BKC+G3bcsCtqvNwYbez09/ei7rAVSe1xDeSobHIjPgcS5O
Zme7lhAU5XLxUea3rShnQJaMEBBaAr4Tq6KcP986VTQxtNXUt1imS+Dwein0ya8lQxu+Rbh+ZJfz
HCG7xcdGczsJr6Iki8VxLrglngXcPOCAGLftJvo5BGw4sZ+3zEuFSE64ErMzOyk1wC8Ebx5HZdze
Fgz+xJZOo9NXSHxgIBNfEy/uIrGq7n0YSWrQhvn1xxsxL4k3ovQ3y1CR9DyL+FYVwp1Ir/idaFUH
FeyzEfs5awJDEOuBhvY2tT5wDPs4qDXtLGlDLRGG/S0OaP6EGBZZz2vzsIUoYXR/Ag5URHf0LtgS
Z7Pnbz0B2CDueQ+52fY4YDmUsTkOMGehM4kvpk4jBXRVK4w/MaDtUOBS7JGA9+8l7D/S1V9ytGtw
4/lPizPPs5ncJrqbZGzH9grUlnK4ucT30DOP8PCienquSFhxABG94eWL9QaUG4aRPo8LyHCRKnhf
5ovdGguls0VqXg628lkD/VvLWosw5i+bi22KxBOJhxLxB7tGrGH2kXB/1BLgDY9vo/xWtcSY/Ils
7GuiJaQvi/42BpgKbhd/ut1ivR0uT2BzJALc2+fPFl2I6Ndk26ulXNHVQZvzGvbZg55nPS2paYLx
WOSf89QEjfIjz7MNbyFQW9C9TVGfKpB63yQ1GK0qrnOeqpCiGxTpcVB59sMySgGTK2DymzcsPBa/
gieCKUeldQXEMbcPdotciN2E4wWw3Vojn/B6As9BTwCuxKBqu5/lMhN5EQm8yfBiVrcYOEwYLRhe
D/ZyL33xUQTs0i/YPhu609FoOtxjxx+vrqE12MMBGp+Di3GkgtACZTIvjgaHg9EQgYlIZL524iiJ
iqOx614gcMERHIgjl4bwe0dfLlRHQ4KojK9SJ9NqhZU9cgYIXi1BT4BKFUcyJJJ64ZzfSpGvj2Rq
gXIIBtWoRBbBkVe6Lt8fH89m52fs/O2bM/b68viavfBKf2/iemWw5/rwPBjA77l/MGZdaO3vH8Bv
Nwh6OGzfrxvBXhB4Jff33R79GUNPcLi3g+S4OYc2QjncX0ZQXSUiLZRhksexXDlhHC2WtSxaaJ5G
CY+rcRqWyHkFCGUOiGv9malLnge+zOt2dpeZ8UEUhpFfxsX6iFSob/PgbUQliiJKF+oIwXQFTy/m
Ci26gSkhAmsIXk0/Oj17c/zh/BqhqOZ+xpWCacHRP+kHxCsL6SioXA0XeJemtt3+Gkr9accrQxGG
Lxg6BvPJ+krgDO/TohEykJRZweBiBkbJYNuoBKtYZzwXrFgKvO+p4IEXzEflF2wuWJT6cRmAFQP6
B8aPuK5kAjNDRLCJU/FQ9JiEnlwhSjbH+7xsLcvc4GJRyGAFojAiCqD8HEwVXB4QvxOrGt1uIEIO
6ldsJdN/FIxnmeA5QwUlICzeoVwD+wxv92q5V0uRsjJb5DwABH0vRcfSyKZeyl5cL8HlnRhAwEXM
00XJF4LhLodUZpxQRdCm47zod1IqTj1ZCt9I0Z4IDFSxR6T9VXQbZSKIdN2CrV28Wnojw5u3V5c3
k9GhM7zBeaDGGtGUeZ1bmXsdJPRxKVB3+KEC3kRn+NGCKnLSb4HBk+5C6m7SJnEKfMCTKGhJA3EX
+YLpS40ISQCxtv6GZAieIgCulmURSPQUfcMdmbF9GV3UdRk6NAdX94eBrxvYHxyg94/cPXgeDw/h
99A/wN9izKZdLdAx+ivDyAMyMBN82V3E2Y8YemAIhaAqLE/p3jlOxITIONq3kiCH4U8vMjeIWKnA
fCHpgAmRXqDuNp91oIabDgdUNZfKEvzFGUW7ChEoi2EcYGDpYEzI63zNjAnCcBMb696Gz48RLJFM
wRh5ELBcKG2zyCZedAR2uCpzimEMLHUuUB+wXOK3ktMHKQvYA6XsjselYF1DEZLFDiDX5CAkC0wN
DtgB3oebQi9Sflcmc7AAcMRjtU79a65uGV4EBdfrY/8HBRpBy65kxFHLHDYoJRgTjFY9RjGLmdgG
xt4DLSSgNYVlAWkFkizCkjIFn8MhhPuKjA3kAbfM5T1E3kKACkAccpK0Zg2Vqtl5G6Jv4xD04R6L
in/gFzk5zQoEJiyy3425rAsSwDqzIWqEZHCMlFPChH6ucyV5+fexnINisfhgGswohWI0S8SCz9cF
MMSuNCsuEY8Urq6OESDTKiLGSNkM041JxQakSC9hBNYCAY6u9COWEKJLRVEvPwhTktEuJMgh0V1R
Z0BnQUzq3D5lo+H+5MCjQEMxvYBAxYP/cRGwXqsEmLiuq/mfiTySlDnQ+BUi9Sl2Gqy1gQ/AGMC3
A1xUGuGAAYJ/jhpcuBOJUvAK4BMd8ikxNPtQ4sQUj9G/9DCP0iPiAItvvMeEACRxiX6LCYnG9x+O
Rpc1NS4oPBM+5i1FekF+9YroubUQELBFphpRR66RVe08ylEluRZ7wfM5KNzxZRzrGg7N+lHN0voh
K2YOM3PAYWATWlKGtLmAGqIEy9npVY64YTrGdnQwC8PKIZPGJvvsUqcnailIH7KMg5qRCNx2lbKG
dTQUlhHn9tKyF2/I9B4EJLIXPbsWKsxlUsU1nGv6HTsUVOFYC2GWbtMWHjEg2xiwmPaXZXqrtMLP
yeUwDBEQWcM9CIrDqg/O0CFyKBiUHuRgzsbao8GFqKp1Nt5y0KjhVOqJmyuov42qJto4NB0zzGb/
m+WmFOD4UGsLLbkxiIoUdjR58/PIvNR8lVAXXGAhsc5Cc174SyoC6EMLSD5gViaUkR/qctL06gg2
F3U+EkGdd4zhVj0YAPJ1gbh7zBlYNo15h8g6RcXKFEbo4NKkOSrQMccEOuqZVdRTAWhY6rMfYNdB
H3IlWCqczD70GN5ngoFpsIqCYqmDJXl5jd4h9BVdSMpNulakGGtsnx0H4FZLHof4LamuIAIB1mYo
AU1thTK1/bLOjBaupkQ5u0cXxAqExz3t3kjXXPLvMzAcQfaNafbDLJ1VSboptLH+wEmwJUdiZZZm
jmlSNVRbQCDm5WJq8v0rNsA8r9dSYUFH3VUxpyiaLUVV5HlmKaDAaSo0xXZVwYsS7GV34WvV4hGb
any+2m+1an1RVW/INgiidzk01BgXSkvr7eNJNNmXmeLoKVOWQNfC7AFAHv01KXALBgcmSpGJt/BD
+MRdVGGRB10WD7khJ6WFe/Hu8vpsyij0wv/9EjZEKWyICBG9EsOVI/YM5Zq9upg9bi2WD7U/xBIj
K9kQ5SXgBG2mQLsZuiaPYDjT6QmNCLefCDc5qSLQhleBTJehV+itKOGcK2FR6w7AUR4h02ND6Bg8
1iEKv79DPquEzQZ5zjVixv2QOfFgAiKTpocVgF5K2nk2W1KMA7QBwaIFowGPV3ytNG6DxzLeVhAn
Ozqmz3qtLKBMqVQxgewjNqzWITzjo+H38ak8B2igedc42qmHjQ8enUzWlQq995sLjWwuQgxEdNaB
AQtXoUaqT0CswEdc4VsxsFnYPUa4wxW47cnWZjdvklFd1FCYCOmMrAqKJoaFZUzDpAJLddBBI19n
Etr75LiFBrMAtJWifpW4BdGuoXiClpJQpMT8UktfubReCdRmtRIX/J7xTa2YL95E0BhDayHIQN/z
ICqVNcusATe8kYfqmcbmcLyZvL1z0pGUU2YBmGxjVMyPBdfs0PnbA2tr9l6VmP2Hcpo4ueIRbaN/
w++2jSGY+cQCwR0Fy2pW+6uxZTLTn1uiGvUzprANxF5KvuuAopFpffLmkMGB5PuouAQ/ocPjFAMc
mCiCZ1vQcqkGqhYfP5krMyyBdWWkTZeijC5JDLYKuaGIaPewueJIqgYSjCfzCJZGDzEHa3ofPdVR
C3f8+NU001Cdi41BaUM3hb91WgKTHDy/qXMrQerM04JmyyxKQ9nMXkpcfqLZtw71oGIiBlOZrhPc
FpA3KdCwqjnFjY7pZk03cQzmxhlfLCBRmR18fTaCBSV+Wn67IY7hUvOD6NRj/KDCtDXTIj9QBpiF
7p7qJchTx+TxmoKGysw61jnBM0E6pBKxzNB5etAGEfAErqiKNqhhQqisBWgbclmKJQEOMmkYP0lc
gPtaSJh5k2GVGyXUpqrQybAKjgYbLpHurvCrDa2sVqvHdBJHkJn0spzdc3R/3cDaBvAbJqYVN9QF
Bq8KCdb9Mz46kI9g/wWAXxCjDplVyWKfppIQ1f5C7/KqE2javj12OEvbYUp4iqoLFDuBoiMCRk05
YLFOVIkBemJ4YA35xx1Tq6Y2ZW/Oj6+nw+/2e3uH94Pe6H7UG343+C6ApK0DVxffpfgYZI4OXLYA
A1e6Nd7Db2TFfSFSVIf55DMX1oejcx/qlmVnSlbV6+BhZhrwvAHof9LFtNDcrMmQZxZ1Xxjha2N9
R0ZfaAiLrO5dgtfVNx3wfedd3fWrMm/A9GeHUPOts6LuvZqd6xfo+BVrMPdrJJmfN4y9F6HZt0H/
y7egRxGGB/PAn+zN3bng4UE45oGYhO4kPBgfiEkwHgVhcDCcsJcdfMek9Hs4gw7/nRPQQmDJmqzV
bzF9ZGue2B5eXRg44AXMwbdLQ3fPHcEjkR/5k4OD+WQ+90duMJrwcMT90TgMgvF8f7433z/YD8Ue
/BD5Qt6KFIJ7Xl+k/j3K9NvPIV03+l1/UawvEcDzPb6IqNZEJtjluqPBYHgI/bPTS3Pjaqw/dZ4t
cUHpehlqUd/z+univKa2CoL7Gp+NG55xe2MxBpBVHhUW5KPgtxAuzC0HVBVk6QYFaSuqR2OjECP9
ebSj+VPk6KqZMtdH7jVgzenFC36oijgyc/xhZBq49I/2JDeBLCBQ1KQSbXMGx38x4VzOKOPBkH1U
D9J/gxfV7mlfRPhQhE+f/g/E94tl
===END CRASH DUMP===

**Comment by Pub4Game** [comment]
duplicate #179

**Comment by onebone** [comment]
php7 브랜치에 있는 플러그인을 사용하시거나
https://onebone.me/plugins/#economys 에서 5.7 버전을 다운 받아보세요.
