### ISSUE TITLE
[Question] Can we edit the EconomyS plugins for help and use these in my own server? (Please read the full text)

### ISSUE THREAD

**Issue by GreenNature-MC-Server** [onebone/EconomyS#186]
I want that the Co-Owner (An plugin developer) make a plugin for the city of my server, but it would need a very long time to make this plugin! 

Now the question: Can we edit the EconomyS plugins for help and use these in my own server? 

If that were allowed, I would place an sign conspicuously in front of the hall, where the rules are and write on this sign that the plugin for the city is originally from EconomyS and it was something edited by us! Is that OK?

**Comment by onebone** [comment]
Of course yes.
What I want you to follow is GPL license.
