### ISSUE TITLE
undefined method onebone\economyshop\EconomyShop::getItem()

### ISSUE THREAD

**Issue by jazzwhistle** [onebone/EconomyS#189]
Hi, just updated to latest Economy on PM 1.6dev48 and I'm getting an error on line 235, "undefined method onebone\economyshop\EconomyShop::getItem()". I've changed it to $event->getItem(... and then get:

Cannot use object of type pocketmine\item\DiamondSword as array
File: /EconomyShop_v2.0.7/src/onebone/economyshop/EconomyShop
Line: 239

So... //'d out line 239 $item = $item[0]; since maybe $event->getItem(... doesn't return an array... and it now seems to work. Or did I break everything else?!

Thanks.

    PocketMine-MP Crash Dump Wed Oct 21 10:59:49 UTC 2015

Error: Call to undefined method onebone\economyshop\EconomyShop::getItem()
File: /EconomyShop_v2.0.7.phar/src/onebone/economyshop/EconomyShop
Line: 235
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: EconomyShop v2.0.7

Code:
[226] 			if($shop["price"] > $money){
[227] 				$player->sendMessage($this->getMessage("no-money-buy", [$shop["item"].":".$shop["meta"], $shop["price"], "%3"]));
[228] 				$event->setCancelled(true);
[229] 				if($event->getItem()->canBePlaced()){
[230] 					$this->placeQueue[$player->getName()] = true;
[231] 				}
[232] 				return;
[233] 			}else{
[234] 				if(!isset($shop["itemName"])){
[235] 					$item = $this->getItem($shop["item"], $shop["meta"], $shop["amount"]);
[236] 					if($item === false){
[237] 						$item = $shop["item"].":".$shop["meta"];
[238] 					}else{
[239] 						$item = $item[0];
[240] 					}
[241] 					$this->shop[$loc]["itemName"] = $item;
[242] 					$shop["itemName"] = $item;
[243] 				}
[244] 				$now = microtime(true);
[245] 				if($this->getConfig()->get("enable-double-tap")){

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #48 [Protocol 34; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux Jdcraft 3.10.0-229.14.1.el7.x86_64 #1 SMP Tue Sep 15 15:05:51 UTC 2015 x86_64
PHP Version: 5.6.8
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
xRulesx 1.0.0 by xFlare for API(s) 1.8.0
PeacefulSpawn 2.4 by LDX for API(s) 1.3.1, 1.4.0
iProtector 2.0 by LDX for API(s) 1.6.0
VIPSlots 0.0.4 by iJoshuaHD for API(s) 1.12.0
AreaProtect 1.0.1 by Comedyman937 for API(s) 1.2.0
AlwaysSpawn 2.2.2 by Philip Shilling for API(s) 1.12.0
BanItem 2.1 by LDX for API(s) 1.0.0
MagicTelePortal 1.3.2 by aliuly for API(s) 1.10.0
GodMode 2.3 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0
SignPortal 1.1.2 by 99leonchang for API(s) 1.3.1
PopupAlerts 1.2 by EvolSoft for API(s) 1.12.0
WorldProtect 2.0.3 by aliuly for API(s) 1.10.0
xyz 1.0.1 by unerds for API(s) 1.0.0
FastTransfer 1.0.2 by shoghicp for API(s) 1.12.0
VoteReward 2.2 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0
PocketGuard 2.1.1 by MinecrafterJPN for API(s) 1.10.0
IPLogger 1.3 by PEMapModder for API(s) 1.0.0
ItemCasePE 1.0.5 by aliuly for API(s) 1.10.0
Alias 1.1.1 by ZacHack for API(s) 1.1.0
CustomAlerts 1.5 by EvolSoft for API(s) 1.12.0
NoExplode 1 by  for API(s) 1.0.0
PurePerms 1.1.12c by 64FF00 for API(s) 1.13.0
ChatCensor 1.4 by EvolSoft for API(s) 1.9.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
essentialsTP 1.1.0 by  for API(s) 1.12.0
FactionsPro 1.3.2 by Tethered_ for API(s) 1.12.0
PureChat 1.3.0 by 64FF00 for API(s) 1.11.0
BuyCraft 1.2.1 by Falkirks for API(s) 1.0.0
SimpleAuthHelper 2.0.2 by aliuly for API(s) 1.12.0
MCG76_WorldEdit 0.5.2 by minecraftgenius76 for API(s) 1.8.0
CapsLimit 1.0.0 by deot for API(s) 1.12.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyLand 2.0.9 by onebone for API(s) 1.12.0
EconomyShop 2.0.7 by onebone for API(s) 1.12.0
EconomySell 2.0.7 by onebone for API(s) 1.12.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrVXI1z27aS/1dwcm6efaPvL9vquDOu46TpsxO9yL3cvLDjgUhQYkwSLEFaVjr93293AZIg5dQf
8b27i5NaWAKL/e0udhcg1D9aWRCJ1mwwHk/Gw8ng6LjdEmkq09bsj1a2TeBR6/z6/OPHDx9b7VYk
lOIrpJ3xMGSZZHnsCT+Ihccika2lx2QslvDPcYQrYxlt1VomjnOuGwtozGYrkb3LRLR/ABz9IER2
PavD9e2w2+8edpM1T3sqdXuGZc/iaPcHLiFI0JoNR5M/260kzFdBjGLXurjSE4hpOJzCMyfDn8Df
f4XcPjutJA1c4bR+Yz+yVxFMtj34AwYNh4dlZyd7lYR8K9LOj0rE3qVWxf6rbB2ozo+AqaA4rVh2
iEdnmW+dVpt9LmYJADZM0nVaM6fVLaigOQ7UNmsK02ZO699H8OHg4AeS5siWRtyKOENhsjMeuyIM
hbefpbkwfY+tvgjUdC+V3/nR5fFPYh5yFwYeaLyjvjUK5tDgEuzzj1zk4nOpA+Dznkdi/+A3dsJw
Wpp1NLDG/0mUoUVJRZanse45Kul/ilAJPf24LvS/BQrg7dvqw0lJI3rApC4v9gB5KqMQ1ob6K0Xv
aJ5HMo8z5K+FnNbYoxr1DCcnzOcgtZHisNbNkuMxdtczHdVYWCo5/hZv/P25r4eP63YjzY8H99mS
5n4VSve3ukILjprdsD50V//17qOm1ce2IV/FcgP9o8BNJUYby0vHk4aXloY7k7EfrNBNoQFrSsR8
GYqOJ3P8lfHEaaEPwILPUvDO1uxza6/P9g9mLJHujciiAIPQQqS36K1uytX6dR4l+0spQ8HjA7B6
ayVikfIQwwL0UoHEsDHoTj1xC8It8yD0WrPxEcQUEFy6EnqOxu0WTwLqNxh1+9BvFWTQ7D/yDwxI
+U0YLHEMRDkk5DHHGNy6COL8jv3igbR+xkbdQb/b78BK7g7G3UFXhIfdu6Pp9XTM9gZscTlnV7lg
C5GwwQT+zvqT2WTAfr06Y8M+UHRX4J6sE+A96U67R9D6CrELmkNo9vXDa6mKuYFAjZAaZTBVqKEz
UFt6wVcrbBiBK1q7psEB8eY5ZIRUoWkuBOja++Bfns3PUfOkws/QExBiW1sXBEPXaLc8kUB3HAnP
lPSz1zYh4hTfy8kd50JyT6SYCOADPJp/WFx9+vDx4jWQNmKpwFOBus6yRM16PTDYOl92XRn1bLl6
FRpA/lrcXoGrKAttSWqA7TfRzskDL8ED2ZXgUQ0wWPW5gIv5HceSxCBeXJ1+vPp1/hDeSrJeyQPA
3n3MQ6HuLKwFpQ51B+ndm5Cnogbw6PkW1dwcx0zuOJdI/2urxnkYAoK5gCDg5+Ei4ZvYwlGnW2iG
3XHdQ1//146d2vB7/Hw4wNJxagI8BVEwh6Aj3EyXYgaORbQtM9xZbw000+9EUc37FAj/+W6+CGVm
r6GSZIsPbtUd1wEEv0i1zvnPr2swBsPn4yg5Oo4lxNOWT/CFeKy9XskCYJ6mghv9WEhtanMVDepg
z2QkvG3E42OoJGy83wHXmv4pJjsNN3yrmqvIptb9Dn4asW8dhEHCFvALssjqxcyXEF9l2DoOJ5GU
XlXN+H+POQ2+n3iMJaGFraDUcQ3+ej31v3M9mUmfYplLvgrcKxGKuUwzXbQYBM0ndW8bNS3EwyAP
t3XDfAcezc5xoix5Cpy30rs0WzIDo6DUgvToQTO0y3pDr5c2Ye6/SPA2Ij0F1yJYxTsWsojNQqlh
nOPjUMjYXfPG0vmOsqFkeHwMBXEpyaNA3RcELRF7FjBMwjLJk9NQpLWQb1Pr6BvYz29luAAQLxYz
rJmbaL8V8AHqZrPpChAFuXazGwT2Saahtxvia+RGPu6O/iWrboMiJPfH+W9HwbvtV7vWg9YDGSqH
jRJI8EIhUHODOm/7lf7zkBNazmcEAQxvuMquUh4rX9gVUo3cRNVwONjWrtaBm7yYwxUMHccWo956
ctFRMO3VuGB5BVb/KDY89ewCqyLWAunw2YH0ewJoJc2TinnapbzN68hsaiNZN90VNzi0iRbpL/P3
L7bo6myhtq9J9NQ4WufWs5j10Lrv5hdytar5dklqZPhGBXZ+yRNIW1gRvdCCTUTEk4hYwl4gCUmK
ZycQS8DeIuJh2PnnWWeuTxp6WSpELwJPh4clXlQHlEtnXIn5ua2Qithc6pN/SfjFIzAXBEjE04rs
gKtaeY3tZmXQ8Ol/cvdn7t7UIXzH/gDn1EKfhVypx0l+lqtMRjspvkau45j8D+d4e2rHaQjyrGT/
Xp7fgYvXatOKZqEb2MheaKUteJSL8Mt64DjlnFBbPz505qmYizSqFWAlbcfFhm7dPNPxmzf9ft04
35EDrjU/iJSFCNbHpx9e4UgTJiou6JVrnp2JWNWOSixiHfb4ER55/B0OWc772JpT3e+HiyBKQnEK
ktZ2EiWxjuqwGS+ah5Dtly93KmFwY2EJ9uxDSYsLaEAoJeIs4KG6mls6qJH/+uD5pZDaUzpOQ4BH
LMs33M1ARgWbhVqtWlEf2LRfiWwtUuFdv5jxrMmxQKXG5ZPiDHp6I8wQqQml/3CMeSiRWTFsB1JN
jd+IPShX9em7Iw8xwdOkfHuGFZx9nFSQGlvd5vJ8w8ObIL15sT3VMt9SMek4lgSPOq8oVtzPIkxq
5ebOo+YW9xEHSw85qB3QHlFvrUmQZ1eePBRfeOylEtj1qveEneSe4nMHPZ7Bnb09nF7Ttv/cC2yz
N5/Uj7cnTVVFRe2/EnGQq8PpS71CidzV4dRxNCBzPCBAIMcpZUNHfvfIZX7GE3URRDWoFe2Bl0Oe
kC9Y5xWzQpFnCfAIDOYeyOn8nQXCIja9+riOwtw+edR2eWheGo3K7XP1Ekn/fvYpXvNeDchSXqvR
KB6vigsee7u6IOozlPHwGrfEfALCEOQpIRrhHo+Rrv3sYDSXgeoYD//3MO7cjnoaRhGG92BE6v8l
jCBPhVEL9yBGvHvAU8AFobhYGXSXo5ukEqJxFgi8qLA3L1tM3xhheKPMSZ1475Pw2Ac3Y8MBG/Rn
k+msf1jejsAOml8HlXfyy2tKmUiORCTTbSfEAHMyGQwvkbjiSPbESZ9G4lunjjl1BR1r6mYN4sM4
lem2ubHyey7S7YmMLVIKujiRvo8k/NxNYAMOodo7+Q/6A0LIzDspD4hmzJKPx7HMYxeTFt3E4u46
ELcigopUmWl4GMpNxw+D1Tor5tEy8ziIoGytEyO5LCm+TIF1CddQ1zz1XJmW7eQ2MVN5ge8Hbh5m
25MBKYqu1GQy7SiRZUG8UidIDkHCEEjCs5p4vfDkzcXpFcmcZ7Kj+K0wjI11guQE3w7Dj0VMZJqd
DI4HoyEZjN8ZXaiTSb9iT4bVLwiBhnddyoTf3UYheg/DOoK55Dg5iA22JP9hoAZWbUs6l3PyKHa1
FkqwAhnjqWBQluOdRwUfeMZctE7GloIFsRvmkHrhA9vxXM1tISMY6yOLJlfFfdFmEmt+hUzZMhX8
hm1lnhpuLPAZmCjwA5oDrJOCM0KNRKzfi03JsOcJn4OFFNvI+G8Z40kieMpQ4RFAdsFbtgCB4dUr
jX6zFjHLk1XKPWDQRZZa+5rhDBts72oN1VInBCJIA8F6lfOVYHjPktRnbKUCaIcSZgm+koL14LO1
cA2e+lAQpCjcRNzdBDdBAvUL78p01cNW7wIW2LX0r98tPlxPR8ed4TWOI5WWrGYML4ytnJae7NOa
dk94XxWvbjK8u6qylLSd4YF6yDPQIj0m3ZK8IAt8EhmZ2BO3gSvYGtJQSEaPiLVeLtW0dCmQnqh1
nnkSV5e+Fooi6dtozA2lEl4h3CkuVoZhA+RhphJltwFn/8DIQZ0ohhRV6oyuW+rBkDI2jKMHKwly
mbm0AblhxnIF7glhHByEcEL8Nrd1tdaqRx0QbwnC2VOcU8wqeAF+hpGAgTODr6DIyy0zHkYDTIwr
n9tK2VtgtgAmMt5GMldgBfAJQO4q1L4LTp4JkBcxpAKXuZYQrdbJtRoryd7n0RLUCSvoVG1j94qr
G3Dx9AbWTFf3+BX0TM5YSI/91ilkIpg7g/6qzahEZiZugX+2AV8EClGYPQkvZCakRXkMiwW7dAsw
mV40sKJSeQeRNROwlAAI+XVciocKK0R65+PCxE64ANssyP6GN6lTGucJzCjkcI3RbB9QgCHZ8ID4
EJKOQTtjR8Ua1dnLrNC3oVxycHVI1Ew/YJTWMCZFYsWX2wzkYgstT58kCBSar1jhAG4TkHwBHsQz
zCsmQRqSIhX5AbgEhCm6ZIx8fIgNxZzkjYhJG3YlAY7EhYDKo5lWJKjOuTMGSbeAw/YoQmcQarj3
/wAIlkAFjNGwX8GYizSQlAzA2W+0t1MINKz3zRJiA3APWM6eNjP16YBjguPb7KDWgXCRC5QX1+C3
4GgYUJmEFFkx0uhumrvmAouhGFUtLz3PhxgcGjMNDeruDmCgWFMwgv4T4WJCUqQklFobSI8tocCq
F4mqII/6BrM6+IZYRgOjSgMrni7BBh1XhqEuwrTP36tpMiqKZEYxMwqWVMTjnBKgLQ2UCDk41EG7
WKo7HmVcSqJ6uO8XizaqnLXLPuicQy2IdGuZh14pSgBLexOzSnztPywh6QHqtN+v0LK9N+SXO+GL
/EjzKMH5qYyKOKhHmx4dO2g0LA2AjEF33eQe72qMxhLMXefxjSqsQPtzil5ERjmx5kd8TBdrbVo6
KZQHSnfqYJTHeqPippkVTmDW1fHUkvq11IObpsXYjTWNHlrno2czHV9UD5RLOi6U5KLQhPGaYlJ8
ZOWwB1niv1hkaDOr7AJnCnViW/IM6n8sHDhWq5DPwANNOKTFq4tL81THwKUoUxyUIVUqM35ePMPg
kW4z5N5mnYG1BHQqo6k7WSEOBKjJtIhOVQKlWhwzl6fDpzGyHg1EI1mX/Qy7FVD7CVS14Opn81/b
MBakWEIc2wRettZR10SIcoIOTQBJo8z4VTWgSEVW5y479WAtrnno47eKKEJA0gV/NJPBtNpPZWwv
ZivlWtxqlc35HS5d3IXxsK0DA07+KYihCgR44FaClgEm8V/n8bwoAaoaHOsdHETXJZBpnsRJxxDq
lRRtvcQyX83KquJHNsBqQptYYV1IHYqaUFFEXIuiVtT1stbdwK70FOthVZarQtMQIj1V98piO9fY
D4iiEEQUgEvviaizcT0ET26gSz3P1J80qKMHzVgED1flTgGg0UEECn6L73V1gOO1OSAW474rs0QA
9Wa7EtGqNgbde//h6nzGKJLDXzeHLVQMWyhiRae/aE4jpJm9FNIy/WnNinQxThSoycMo6YE86FEZ
etWwb5IThkOd+7SL4SYYn5iEV8aJ+oMiEuqKgFavTrlLroQ15f4AltM9c7XZEB4M7nsgMrd7YJa3
ErYsxkmukDtuoMyWmwkIaXpOLDa0dWnjWu1oMWzQLgfrJB089PVdzd9warh3LScYFzulr2dZaUWZ
Kq0QBqEgT+oODZoAFPVXw3kKVE/j0HyaOc0UHvcwIOeLhd48LoVmuBQ+hjA6esBQh5axGOtDFytu
jkzsWvBbyPG4Bw1wtyxwp5VszQmBSXNlPUXRxadXFUVMLSOgn4fUUSrw5g7tsVydmxTaJ8UNOXgM
MC709kXi7kgvIMUjdKLIhFrMWKUi7CCgDYQKrgx0ye8YbyoJNkcu5ZrKVxr2GRv9fuRekCtrqLEN
N4LSoi6GG9/EEaDDp69oOh7r5IkH7m07H+zPBdeS0WnevX5Z7Rcr5N1d6CbmbnhAu/vf8TuUxlUM
ByMMPekosLrZzD2DYyKTPCw5mhamSJt5ubWitd8BG2gA+mSwQ86p0CLaJBFkiwyPcQx9UIYjPKub
saJMLfwEv1uXJ1CkVdWr9ncKWUVRZLgCv0M92kyPE+jFAABx2pJsqDxaBmDBolt5cKgPC2bVIQOj
b/wVhwj6DEC7YbFQzK7FCrJ0yoCHSU1amega9GSdBLEvbd9ZS3QYmrxrnTdCCVeTV3udUf2uJGAz
3WNWKCONOyZx29Uj0WVSOxI6w9NCOrASoUzQ39vQzjieZkEoKMs3qGJ8qL8FQIaMFWMdgN3KpJuj
pmDlWYyYeadg1Rk5lKwq00mviHWGn9aT7lDMYUuqVYUXX76hKLyhVtTRUF9xXL9FEwscmMsINCsk
Mw/BNVUmwQ0/48cOJB/YygHhN1Yw19GwqlzsA1hCVmxO9L6xONWmDeF9J7q026Ykp6jAQF1EUHcE
ILOpBWo4jGF/wu+Ygpi/6eYvry+DOHgLAZje1lYP/g78Pvgg5wXHa5PVg0We3ga3PBxUpGUqPX0D
oKKpGzo4LJr4RvsMI2F639xWx0tKMA1mV269HYvNpi4uLfmqmdwmZWNPd9WfGb4RwGAzNu1S0TOG
LwZmwx8O25Pju0F7dDdqD38Y/OBBnaLj7j6+rHcxOp4c9dkKVpzSrfHkwBz4i7tMxOgW+guskJSt
L8Li8rKakBVXrRkt5HYrcbGraajfwyATI/193Y7+bvBX/QVe/d536UL1ty7749Fx7PG0Iuj/j0LR
ytOwbPhBmOGdC2A90C+T/Swpn6686mNUkdcQXPQbd+j/RdVumJCrefrLxYPuxIgbLfVxd8kCSuxt
klUQM44Se5Y+FvMLYoIXFxIXkmg1dgsaoS8Rm09sgl8YGOBcrIOv14b9SX8EH1+9w+rGnR4dLafL
pTvqe6Mp90fcHY19zxsvD5eT5eHRoS8m8Ie9gpnma9RbebkkkSq4q6xizlJMhwHi/Sh8s90HKs0n
fP9o6bnTybK/FNw/8sfcE1O/P/WPxkdi6o1Hnu8dDac0n1pHslKsojik6kgDrUvonMkbEUMSTUvK
J8FvIIxqRXWnQNlyerNU3N/9GiS6NeyOW3/++d+sq7l2
===END CRASH DUMP===

**Comment by onebone** [comment]
Thank you for your report.

**Comment by CDFalcon** [comment]
Lol. I know how this happens, and I am assuming you do too? Anyways, YOU HAVE TO REMAKE ALL OF YOUR [sell] signs WHEN YOU UPDATE :P That is what is causing this error: faulty, old, sell signs :P
