### ISSUE TITLE
Please can you quit the tax because players dont like tax because the tax quit money and my players dont like with tax!

### ISSUE THREAD

**Issue by SoyPro** [onebone/EconomyS#191]
And please to the shop add $.with the tax show your $100 has been take by tax so why dont you quit the tax.please onebone this plugin its great

**Comment by dog194** [comment]
XD. it seems U cannot use EconomyPshop well. Please open the file "plugins\EconomyPShop\config.yml". Change "shop-tax: 100" to "shop-tax: 0“ and save. Then reboot your server.

**Comment by blah123454321** [comment]
How do I do that are u doing that on a computer

**Comment by dog194** [comment]
if is on a computer. U can just open is with notepad.exe. For Android, maybe you should use some app to edit it. For IOS. I don't know. XD

**Comment by SoyPro** [comment]
Thanks!
