### ISSUE TITLE
Not Up To Date

### ISSUE THREAD

**Issue by blah123454321** [onebone/EconomyS#193]
This is a great plugin and I want to use it to make my server even better then what it is. But this plugins says outdated when ever I try to install it. I am using Pocketmine on iOS and the version is 1.5 and the app was last updated on September 24,2015. Please contact me at christien0720@gmail.com on how to fix this problem or if it just a bug.

**Comment by dog194** [comment]
maybe U can try to download another version instead of "5.7". Here is the url: http://onebone.me/plugins/ . The version 5.7 is for PM1.6 I think. So for 1.5, maybe 5.6 is more suitable.

**Comment by blah123454321** [comment]
Well I am currently on an iOS device because I can't get my server to
update from 11.0 to 12.0 with android

**Comment by dog194** [comment]
just download the PocketMine-MP.phar from http://jenkins.pocketmine.net/job/PocketMine-MP-Bleeding/changes. The Bleeding version is for 0.12. And the latest version #48 do not request PHP7.0.So i think U can just replace the phar to update to 0.12.0(0.12.1 0.12.2 0.12.3)

**Comment by blah123454321** [comment]
Ok and then how do I do the things with the config.yml or is that on the
computer

**Comment by dog194** [comment]
For PC, U can just download the Phat and replace it. For Android, maybe U can download it to your PC. Then connect your phone to PC and replace. Or just download to your phone and use some app to find the phar and replace it .   ?config.yml? Are we talking about the same question?

**Comment by blah123454321** [comment]
Do u have a server if so what's the ip

**Comment by blah123454321** [comment]
And I am no longer going to try to make a server cause this is way to
confusing lol

**Comment by dog194** [comment]
lol . i am a chinese. So if you come to the server in China. Maybe it is another way to confuse you because of the Ping. Well it seems U problem has been done. So just close this issue.

**Comment by blah123454321** [comment]
sooo whats your server ip

**Comment by blah123454321** [comment]
and port
