### ISSUE TITLE
Error display for land whose.

### ISSUE THREAD

**Issue by dog194** [onebone/EconomyS#194]
If i have a land(startx=200 endx=300 startz=200 endz=200  ID=1 price=100 /* 100)
then i use the commond "land whose". i will get a list : a land ID=1  0 m^2  (it should be 100 m^2)
then i add the world to :"white-world-protection". and i can manage the block which are located at x=200 z=200
But! i use the commond "land here". and get a message "Anyone doesn't have this land",
then i use commond land whose to get the id and "landsell 1"
then i get  100 /*  100 //2

**Comment by blah123454321** [comment]
Did you do /startp the do /endp the do /landbuy?

**Comment by dog194** [comment]
Of course i did it....

**Comment by dog194** [comment]
weil!. Bug fixed! :D
