### ISSUE TITLE
Error display for  message "land-around-here" => "There are %1's land around here"

### ISSUE THREAD

**Issue by dog194** [onebone/EconomyS#198]
Player1 buy a land ID=1
Then Player2 want to buy a land but some area has already been bought by Player1
So Player2 get a message "There are 's land around here" (it should be "There are Player1's land around here")
BTW, Could you please add The Land ID into this message. For example "There are Player1's land around here, and the land num is 1."
Used EconomyLand V2.0.9

**Comment by dog194** [comment]
Also, it may be more stabilized if it can save the land data per hour or a lesser time automatic. Sometimes some unkonwn big problem will make a crush. Then some new land data will not be saved.

**Comment by Tolo0** [comment]
I'm having simular problem. All bought land gets reset after server reboot. It only saves if u do /reload. Is they a way to fix this so I don't have to do reload everytime someone buys land?

**Comment by dog194** [comment]
weil!. Bug fixed! :D
and enchantment done tooooo.

**Comment by dog194** [comment]
oh.....enchantment(data autosave) haven't benn done. I am sorry.

**Comment by dog194** [comment]
@Tolo0  Now land data can save per 10 mins automatically (You can change it in config.yml).

**Comment by Tolo0** [comment]
How do I do that?. I just checked the land.config and the api config. But don't see a option to do that.

**Comment by dog194** [comment]
@Tolo0  You need to download the latest version from Github (just download EconomyLand). And pack it to .phar. Onebone just merged Auto-save into the master several hours before. XD

**Comment by Tolo0** [comment]
Oh. I didn't know they was a new version.  Thanks for letting us know 😉

**Comment by dog194** [comment]
@onebone  Would you mind changing the version of EconomyLand to "2.0.10 build1" or "2.1.0 build1" (づ￣3￣)づ╭❤～

**Comment by dog194** [comment]
@Tolo0  In fact, it is not a new version. lol . a new verison should be out by onebone only.

**Comment by Tolo0** [comment]
I think I'll wait for onebone to bring out the new version. I have no idea how to pack it to the phar lol.

**Comment by Tolo0** [comment]
Dog194. Would you mind explaining how i can do it?. Iv just spent hours trying. And nothing i do seems to work. Its driving me insane 😨

**Comment by dog194** [comment]
1. download the plugins called "devtool.phar". 2add this plugins to your server 3 download the code resource.zip from github and unzip it. 4 change the name of EconomyLand to "EconomyLand_code" or other name. then only copy the Economyland folder into your server/plugins 5 delete the old version 6 reboot your server. now the plugin will work. But! if you wanna pack it to phar then continue.

**Comment by dog194** [comment]
1 open your server . input "makeplugin EconomyLand". then you will find phar in yourserver/plugins/devtool 2 move it our of the folder to yourserver/plugins 3 delete the folder "EconomyLand_code" 4 reboot again

**Comment by Tolo0** [comment]
Lol the only thing i missed was changing the name to EconomyLand_code 😅 thanks alot it worked now.

**Comment by dog194** [comment]
😁

**Comment by dog194** [comment]
bug fixed. enhancement done. Then it is time to close this issues.
