### ISSUE TITLE
Economy Shop/ Sell Wont Work?

### ISSUE THREAD

**Issue by chroniclemcpe** [onebone/EconomyS#204]
hey guys, not sure what issue is i also tried removing other plugins and running shop and api only, no luck.
the command things work but the sign doesn't weather shop or sell. it doesnt give a crash report or anything either.
1.6dev 0.12.1 (pocketmine version)

**Comment by dog194** [comment]
EconomyS include EconomyShop(For system shop, op use only). EconomySell(For system sell, op use only), EconomyPshop(All the palyer can use for a personal shop, and it must work with Item Cloud). Make sure U add the right plugins. For EconomyShop, the sign's first line should be "shop".  EconomySell is "sell". EconomyPshop is "pshop". Also U can modify the config.yml and signtext.yml in plugins' own folder.

**Comment by chroniclemcpe** [comment]
i was literally writing [SHOP] EVERY TIME?! thinking its broken, works fine, i just forgot the command line for some reason.. thanks though, do you know anyone who can help me create a plugin, just the files and stuff, i can code rest myself

**Comment by dog194** [comment]
it is “shop” instead of “[shop]”. :)  .and i donnot konw anyone who can help you.

**Comment by Driesboy** [comment]
Do you use the latest version

**Comment by onebone** [comment]
I think you wrote [shop] or [SHOP] and something like that.
Try writing 'shop' at the first line.
