### ISSUE TITLE
Command List -Money/ Other

### ISSUE THREAD

**Issue by chroniclemcpe** [onebone/EconomyS#206]
Hey guys, sort of an issue, pocketmine is down for me right now, i cant see the economy plugin page so i cant see the commands, i found a site but that was for dev 1.4 which the lines are switched around, can anyone provide me with the latest commands that are on the pocketmine plugins for economy

**Comment by dog194** [comment]
please input "/help <page num.>" to see the whole commond in game. Or just see the plugins.yml in each folder in github.
