### ISSUE TITLE
Land Buy/ Build

### ISSUE THREAD

**Issue by chroniclemcpe** [onebone/EconomyS#207]
hey guys, my server spawn protection is very big, and it covers the land area so doesnt let non ops break/ place blocks and not just that, even in general, i have land slots, lets say a player buys the hole area, how can he build when only inside the area? any ideas? help

**Comment by dog194** [comment]
.Do you mean U want to make palyers just can block/palce after buying some area.

**Comment by chroniclemcpe** [comment]
yes, if they enter the area they can build because its "their" area

**Comment by dog194** [comment]
Just add the world to :"white-world-protection". Then reboot your server.

**Comment by chroniclemcpe** [comment]
how do i do that?

**Comment by dog194** [comment]
Open the file "/plugin/EconomicLand/config.yml". Next add the world name into "white-world-protection" and save. Then reboot.

**Comment by chroniclemcpe** [comment]
i only added the world name onto whiteprotection
land[]

i still cant build.. i think spawn protection, but if i remove pawn protection, others can break anywhere..

**Comment by dog194** [comment]
can? or can't?
if you added the world name into white-world-protection: []. Then players cannot build no owner land. If you are op. You can still build anywhere. if you wanna protect somewhere, just buy then.

**Comment by chroniclemcpe** [comment]
i bought land, deopped myself to make sure i cant build with powers, but i cant build still, ill check if its my plugin

the file:

---
handler-priority: 10
white-world-protection: land[]
non-check-worlds: []
buying-disallowed-worlds: []
player-land-limit: NaN
price-per-y-axis: 100
database-type: yaml
...

**Comment by chroniclemcpe** [comment]
also got rid of all the world protect plugins, still no luck

**Comment by chroniclemcpe** [comment]
is there some sort of permission node i need to add?

**Comment by dog194** [comment]
it should be "white-world-protection: [land]" instead of "white-world-protection: land[]".
This option will make all the players cannot build anywhere except in their own land.
If you wanna to remove spawn protection, you may check the "server.properties“.

**Comment by chroniclemcpe** [comment]
no luck x.x it works if i remove spawn protect but then anyone can break blocks and so on, my server is big and sht load more detailed with effort and i cant afford to have it griefed, even though backups.

**Comment by dog194** [comment]
oh.dear. I think i really don't kown what do you really want.

**Comment by chroniclemcpe** [comment]
okay so i added the world, doesnt work. i just want players to be able to build when they are in their area. followed your steps for config but no luck, i remove the spawn protection then anyone can break blocks which is useless.. free griefing. i dont know how to make it where spawn protection doesnt affect and how to make it work correctly.

**Comment by dog194** [comment]
make sure the world's name is "land"? As usual if you just have one world and never change the world‘s name, the world's name is just "world". If it is, you should write white-world-protection: [world]

**Comment by chroniclemcpe** [comment]
its just land the folder/ world name. i did that with it inside the brackts but no luck.

here is the worlds i have:
land
mine
mines
MiniGames
world

this is the configure file how i did it/ setup:
---
handler-priority: 10
white-world-protection: [land]
non-check-worlds: []
buying-disallowed-worlds: []
player-land-limit: NaN
price-per-y-axis: 100
database-type: yaml
...

**Comment by dog194** [comment]
well it is really strange. I think you must reboot your server after changing setting, right? Soooooo, would you might tell me your server'ip and port?

**Comment by chroniclemcpe** [comment]
chronocraftmcpe.ddns.net
port: default
(19132)
website: chronocraftmcpe.blogspot.com

**Comment by chroniclemcpe** [comment]
all good, i fixed the land issue, the issue was land only protects from world spawn for land, 128 4 128, it works now, can i possible make the protection radius bigger?

**Comment by chroniclemcpe** [comment]
simple: THREAD CLOSED< fixed all the issues!

**Comment by dog194** [comment]
Well give me Your email address. I will give your two plugins.
In world "world" if you wanna other cannot build the spawn area. You can just buy the area as your land. So others cannot build.
In world "land" if you wanna players should buy a land then they can build. Just add "land" into white-world-protect.
In world "mine" if you don't want palyers to buy a land. Just add "mine" into buying-disallowed-worlds: []
BTW, i suggest you to change a plugins EconmicTax or just remove it. At the first time i join your server i got 1000, then mymoney has been tax 3 times. So now i just have 700. I think this is an unhappy things for players.
