### ISSUE TITLE
Economy Sell Issue

### ISSUE THREAD

**Issue by peepzandmeepz** [onebone/EconomyS#21]
This issue only involves EconomySell in its latest version. Many items do not register on the selling signs (emeralds,  many of the less known items). Unlike a working sell sign, the sell signs that do not work show this message..  [EconomySell] Sell center created (emerald:1) instead of how it normally shows the item ID. Many of the items do not work with the selling signs.

**Comment by onebone** [comment]
Working on my server, please give me more information.
