### ISSUE TITLE
Sorry I forget how to used github :P Traditional Chinese language

### ISSUE THREAD

**Issue by edwinyoo44** [onebone/EconomyS#214]
EconomyAPI/resources/lang_zh.json

This is "Traditional Chinese"

{
    "language": "zh",
    "language-set": "語言被設定為 %1",
    "request-cancelled": "您的請求已被取消
",
    "player-not-connected": "玩家 %1 目前不在伺服器上
",
    "player-never-connected": "伺服器中不存在玩家 %1",
    "topmoney-format": "[%1] %2: %3",
    "pay-failed": "付款失敗",
    "pay-success": "付款 %1 %MONETARY_UNIT% 給 %2
",
    "money-paid": "%1 付款給你 %2 %MONETARY_UNIT%",
    "takemoney-must-be-number": "金額必須是有效數字
",
    "takemoney-invalid-number": "無效的數字",
    "takemoney-player-lack-of-money": "%1 沒有 %2 %MONETARY_UNIT% . %1 剩餘金額: %3 %MONETARY_UNIT%",
    "takemoney-money-taken": "您的 %1 %MONETARY_UNIT% 已經被管理員拿走~ ",
    "takemoney-took-money": "已經拿走 %1 的 %2 %MONETARY_UNIT%",
    "takemoney-failed": "拿錢失敗",
    "givemoney-must-be-number": "金額必須是有效數字",
    "givemoney-invalid-number": "無效的數字",
    "givemoney-money-given": "有人給您了 %1 %MONETARY_UNIT%",
    "givemoney-gave-money": "已經給 %2 了%1 %MONETARY_UNIT%",
    "seemoney-seemoney": "玩家 %1 的金錢: %2",
    "setmoney-setmoney": "玩家 %1 的金錢已經被設定為 %2 %MONETARY_UNIT%",
    "setmoney-set": "您被設定成 %1 %MONETARY_UNIT%",
    "setmoney-failed": "設定失敗~未知錯誤~",
    "setmoney-invalid-number": "%1 %MONETARY_UNIT% 是無效的金額",
    "mymoney-mymoney": "您身上的錢: %1 %MONETARY_UNIT%
",
    "mystatus-show": "您錢的狀態 : %1%
"
}

**Comment by ChalkPE** [comment]
What's the native name of this language? It's needed for the language list.

e.g. "ch" => "中文"

**Comment by ChalkPE** [comment]
Oh, I checked PR just now. thanks!
