### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by dog194** [onebone/EconomyS#217]
i am coming again with another bug report.
Bug(EconomyS): use "/land move" then fall out of the world.
startx=-10 startz=-10 endx=10 endz=10 ID=0
The Block at land's center(x=0 z=0 y=1) is air.
So when someone use "/land move 0", he will be tp to 0,0,1. Then he will fall out of the world.

**Comment by dog194** [comment]
BTW here is another enhancement request.
Maybe the owner be allowed to set people cannot use "land move" to move in his/her land.

**Comment by dog194** [comment]
ヽ(*。>Д<)o゜.I cannot find "DeviceBan" in Github.Sooooooooooooo, Here is a bug about "DeviceBan".

 [Server thread/CRITICAL]: "Could not pass event 'pocketmine\event\player\PlayerPreLoginEvent' to 'DeviceBan v1.1': Undefined index: clientId on onebone\deviceban\DeviceBan
[Server thread/NOTICE]: ArrayOutOfBoundsException: "Undefined index: clientId" (E_NOTICE) in "/DeviceBan_v1.1.phar/src/onebone/deviceban/DeviceBan" at line 85

Used "PocketMine-MP_1.6dev-51_mcpe-0.13_2ddc4455_API-1.13.0.phar" from http://jenkins.pocketmine.net/job/PocketMine-MP-Bleeding/51/

**Comment by onebone** [comment]
@dog194 First of all, I'm surprised that DeviceBan was in use.
I have a file that bug fixed, I will upload it to my website in a few hours. Thanks :D

**Comment by ChalkPE** [comment]
@onebone you're always too late LOL

**Comment by dog194** [comment]
@onebone  XD. I think DeviceBan is really a good way to deal with some really bad guys.
But, do you forget to put a "Bug label" or “enhancement” for the Bug in EconomyLand i reported.

**Comment by dashi18** [comment]
I can't get the app to wok help me plz

**Comment by onebone** [comment]
@dog194 @ChalkPE :+1:

**Comment by dog194** [comment]
Bug fixed. Then just waiting for enhancement. (　ﾟ∀ﾟ) ﾉ♡
