### ISSUE TITLE
Help Economy land!!!

### ISSUE THREAD

**Issue by astersx** [onebone/EconomyS#226]
There are players who bought land in my land :| ,  and i cant see players land if they bought 1 block,  /land here will no work.  So how can i edit from config to show like this wen try to edit a land
"Cannot edit land.  Land owner :Name.  Land number: number

Becouse i try from language properites,  land number %2,  but is empty.

**Comment by dog194** [comment]
XD. This bug has been fixed now. But the new vision will not come soon. You can download  EconomyLand form github to replace the old one to solve your problem.

**Comment by astersx** [comment]
ok thx!!

**Comment by jazzwhistle** [comment]
I tried that but get an "incompatible API version" error on recent PM dev builds

**Comment by dog194** [comment]
@jazzwhistle EconomyLand?

**Comment by jazzwhistle** [comment]
All the github Economy plugins

**Comment by onebone** [comment]
@jazzwhistle EconomyS in github is now compatible with API 2.0.0, which is using PHP7.
It could not work on PHP5 (API <= 1.13.1).
