### ISSUE TITLE
Economy Property doesn't work

### ISSUE THREAD

**Issue by HimbeersaftLP** [onebone/EconomyS#228]
If I type '/property pos1' nothing happens, there will by no message in chat. But I have the Permission and I did't change anything in the config.

**Comment by onebone** [comment]
Already fixed.
https://github.com/onebone/EconomyS/commit/1977d27a06d535abb0ecf970012a9b29781046d5

**Comment by HimbeersaftLP** [comment]
Where can I download the phar?

**Comment by HimbeersaftLP** [comment]
?
