### ISSUE TITLE
EconomyAPI issue -your bank credit has been increased

### ISSUE THREAD

**Issue by zhangzhy2000** [onebone/EconomyS#23]
In my server, a player can always receive the bank credit, but other players can't. His name is wanhao, not an op. Last time I empty the economyapi folder, but he still can get the credit after depositing some money into the bank!

**Comment by onebone** [comment]
Has the time passed by set value?

**Comment by zhangzhy2000** [comment]
Yes,but even if I added the time a lot. Other players still can't get credit.
