### ISSUE TITLE
Economy property

### ISSUE THREAD

**Issue by cian0204** [onebone/EconomyS#233]
/property pos1 pos2 하고 /property make 5000 하면 알수없는 오류라고 떠요 api버전은 1.13.1이고요 원래 버전이 않맞다고 떠서 property를 2.0.0을 1.13.1로 바꿔서 적용했는데 이래요 안바꾸면 버전이 않맞다고 뜨고 빨리고쳐주세요.

**Comment by onebone** [comment]
API 를 억지로 바꿔서 적용시키지 말아주세요
