### ISSUE TITLE
에러가 났어요...

### ISSUE THREAD

**Issue by ttoo0123** [onebone/EconomyS#234]
안녕하세요? 앞에서 보니까 영어를 잘하시나봐요~ 영어도 있고 한국어도 있는데 저는 영어를 몰라서 여기까지 오는데 많이 힘들었습니다;;
[16:22:21] [Server thread/CRITICAL]: Exception: "Unable to open database: unable to open database file" (EXCEPTION) in "/EconomyProperty_v2.0.6.phar/src/onebone/economyproperty/EconomyProperty" at line 69
[16:22:21] [Server thread/INFO]: Disabling EconomyProperty v2.0.6

Fatal error: Call to a member function close() on null in phar://D:/Users/TG/Desktop/Radio/Game/▒▒▒▒ũ▒▒▒▒Ʈ/Minecraft PE/Server/PocketMine-MP/plugins/EconomyProperty_v2.0.6.phar/src/onebone/economyproperty/EconomyProperty.php on line 102

Call Stack:
    0.0270     446144   1. {main}() D:\Users\TG\Desktop\Radio\Game\▒▒▒▒ũ▒▒▒▒Ʈ\Minecraft PE\Server\PocketMine-MP\PocketMine-MP.phar:0
    0.0300     441368   2. require('phar://D:/Users/TG/Desktop/Radio/Game/▒▒▒▒ũ▒▒▒▒Ʈ/Minecraft PE/Server/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php') D:\Users\TG\Desktop\Radio\Game\▒▒▒▒ũ▒▒▒▒Ʈ\Minecraft PE\Server\PocketMine-MP\PocketMine-MP.phar:1
    0.3010     583808   3. pocketmine\Server->__construct() phar://D:/Users/TG/Desktop/Radio/Game/▒▒▒▒ũ▒▒▒▒Ʈ/Minecraft PE/Server/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php:466
    2.6001   16692784   4. pocketmine\Server->enablePlugins() phar://D:/Users/TG/Desktop/Radio/Game/▒▒▒▒ũ▒▒▒▒Ʈ/Minecraft PE/Server/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server__32bit.php:1699
    2.9612   17003624   5. pocketmine\Server->enablePlugin() phar://D:/Users/TG/Desktop/Radio/Game/▒▒▒▒ũ▒▒▒▒Ʈ/Minecraft PE/Server/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server__32bit.php:1881
    2.9612   17003624   6. pocketmine\plugin\PluginManager->enablePlugin() phar://D:/Users/TG/Desktop/Radio/Game/▒▒▒▒ũ▒▒▒▒Ʈ/Minecraft PE/Server/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server__32bit.php:1895
    2.9652   17019232   7. pocketmine\plugin\PluginManager->disablePlugin() phar://D:/Users/TG/Desktop/Radio/Game/▒▒▒▒ũ▒▒▒▒Ʈ/Minecraft PE/Server/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/PluginManager.php:568
    2.9652   17019336   8. pocketmine\plugin\PharPluginLoader->disablePlugin() phar://D:/Users/TG/Desktop/Radio/Game/▒▒▒▒ũ▒▒▒▒Ʈ/Minecraft PE/Server/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/PluginManager.php:636
    2.9662   17023680   9. pocketmine\plugin\PluginBase->setEnabled() phar://D:/Users/TG/Desktop/Radio/Game/▒▒▒▒ũ▒▒▒▒Ʈ/Minecraft PE/Server/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/PharPluginLoader.php:138
    2.9662   17023672  10. onebone\economyproperty\EconomyProperty->onDisable() phar://D:/Users/TG/Desktop/Radio/Game/▒▒▒▒ũ▒▒▒▒Ʈ/Minecraft PE/Server/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/PluginBase.php:88

[16:22:21] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[16:22:21] [Server thread/EMERGENCY]: Please upload the "D:\Users\TG\Desktop\Radio\Game\▒▒▒▒ũ▒▒▒▒Ʈ\Minecraft PE\Server\PocketMine-MP\CrashDump_Fri_Jan_15-16.22.21-AWST_2016.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
이렇게 오류가 뜨는데
EconomyProperty 이 플로그인을 삭제하니 오류는 없고 접속이 되더라고요
어떻게하나요? 도와주세요!

**Comment by HerO-0110** [comment]
로컬로 열면 그렇습니다.

**Comment by 64FF00** [comment]
@HerO-0110 ...

**Comment by HerO-0110** [comment]
@64FF00 ?

**Comment by onebone** [comment]
PocketMine 폴더가 있는 경로에 한글이 있는 것 같네요.
