### ISSUE TITLE
Whats the name to download the plugin?

### ISSUE THREAD

**Issue by Galicy** [onebone/EconomyS#235]
Whats the plugin name to download the plugin? 

/plugins install ?

**Comment by dog194** [comment]
what？

**Comment by Galicy** [comment]
You know this by mcpe /plugins install ?  What do i need to put there to download the economyapi?

**Comment by dog194** [comment]
To download EconomyS you can goto https://github.com/onebone/EconomyS/releases/tag/v5.7  to download EconomyS (EconomyApi is included)
But if you wanna the latest version, Just download the code from github and pack to pahr by youself.

**Comment by Galicy** [comment]
But you have by mcpe this /plugins install (keyword)
Whats ghe keyword from the plugin

**Comment by Galicy** [comment]
I just want the keyword from : /plugins install (keyword)

**Comment by Galicy** [comment]
.?.?

**Comment by Galicy** [comment]
Becaus i have only the app plug pocket mine and not on the computer and on the app you need to say 
/plugins install (and then the keyword from this plugin) and idk what the keyword is?

**Comment by dog194** [comment]
EconomyAPI
EconomyLand
EconomyShop
...an so on

**Comment by Galicy** [comment]
Doesnt work

**Comment by dog194** [comment]
oh, i dont know other method

**Comment by Galicy** [comment]
Doesnt matter
