### ISSUE TITLE
"$" character - airport.yml

### ISSUE THREAD

**Issue by Conankun17** [onebone/EconomyS#24]
First, I'm a Japanese so I'm sorry if my English is unnatural...

In the airport.yml file,I saw "$" character (Line 7).
Is that Okay?
I saw "%MONETARY_UNIT%" sentence in the language.properties files.
It is strange if monetary units is different, isn't it?

If it isn't problem, I'm sorry...

**Comment by onebone** [comment]
Oops, I missed it. Thank you for reporting.
