### ISSUE TITLE
Suggestion: Money per login 

### ISSUE THREAD

**Issue by RocoWayne** [onebone/EconomyS#241]
Love the plugin.

Can i add a suggestion? Maybe a feature to give to players an amount of coins in the first login each day. So, the players can go back to the server and play.

**Comment by blah123454321** [comment]
Just use the plugins VoteReward and have your players vote for money each day

**Comment by RocoWayne** [comment]
Yes. I test it but is does not work well ..

**Comment by blah123454321** [comment]
Maybe it's because your are not editing it in the config.yml correctly

**Comment by RocoWayne** [comment]
maybe, i will try again, but i dont wanna have too many plugins working. 

however I think it's a good work for Economy

**Comment by Tolo0** [comment]
![screenshot_2016-02-22-14-10-32-1](https://cloud.githubusercontent.com/assets/13458191/13220461/35543e36-d96e-11e5-9320-b138e0402fe6.png)

**Comment by Tolo0** [comment]
That's with vote reward.

**Comment by blah123454321** [comment]
Thx for that
