### ISSUE TITLE
Suggestion: Allow buying overlapping Land when same owner

### ISSUE THREAD

**Issue by markkrueg** [onebone/EconomyS#247]
One big problem with Land has been players trying to buy land next to their existing land. The Land code checks to make sure new land purchases don't overlap existing land, and it tries to leave a one block gap.

Change this to check land owners of any overlapping land. If the owners of any overlapping land are the same as the buyer, then allow it.

This way players could extend their land by buying overlapping land. Most players would be OK with paying twice for some blocks in order to extend their land safely.

**Comment by dog194** [comment]
What is the version of Eland you using? The version from github now does not have this problem. People can buy two lands without any block gap.

**Comment by markkrueg** [comment]
You are correct; my apologies. I am running 2.0.9, but source from a while back. It does allow land purchases with no block gap. 

I still think it would be nice to allow owners to overlap their own land. It would make doing a lot of land purchases easier. You wouldn't have to line up perfectly, or buy many small parcels to make the shape you want.
