### ISSUE TITLE
이코노미 Pshop 무한구매

### ISSUE THREAD

**Issue by Matunserver** [onebone/EconomyS#25]
마턴이(오피아님)라는 계정으로 pshop을설치한다할때 아이템클라우드에 돌 10개를 업로드하고 pshop 1 1 1 로개설하엿습니다 그리고 마턴즈라는 계정으로 표지판을 누루면 무한정사집니다 마턴즈가 돌을 100개사도 마턴이라는계정에들어가서 itemcloud list 치면 돌 10개라고 그대로뜹니다

**Comment by qazplmwsxok86** [comment]
r

**Comment by 64FF00** [comment]
@Matunserver 인툰서버 생각나는건 기분탓인가요 
ㅜㅜㅜ

**Comment by Matunserver** [comment]
기분탓일거에요 ㅋㅋㅋㅋ
