### ISSUE TITLE
UPDATE

### ISSUE THREAD

**Issue by toastedsandwhich** [onebone/EconomyS#250]
Plz update it to 0.13.2 i can not get the plugin

**Comment by onebone** [comment]
Are you using plugin from GitHub repo?

**Comment by toastedsandwhich** [comment]
Im useing plug pocketmine ios

**Comment by toastedsandwhich** [comment]
No pc

**Comment by onebone** [comment]
Sorry, I cannot test the plugin on iOS.

What PocketMine version are you using?

**Comment by toastedsandwhich** [comment]
1.14.0 or 1.6.28 i think 1.14.0 might be other one

**Comment by onebone** [comment]
API version is 1.14.0? I haven't seen PocketMine with API 1.14.0.

**Comment by toastedsandwhich** [comment]
Then its the other one

**Comment by toastedsandwhich** [comment]
I dint no how to find it it might be the other one

**Comment by toastedsandwhich** [comment]
Dont

**Comment by onebone** [comment]
I need your PocketMine API version.
