### ISSUE TITLE
Low tps EconomyLand (PlayerInteractEvent, BlockBreakEvent)

### ISSUE THREAD

**Issue by andris155** [onebone/EconomyS#253]
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/13034354/38e8e2cc-d333-11e5-89c5-fa3aa441df45.PNG)

**Comment by onebone** [comment]
I am going to optimize the plugin, but I have to rewrite the database to do that which results in deletion of the old database.
I am looking for a better choice.

**Comment by astersx** [comment]
Please dont delete old database T.T
