### ISSUE TITLE
outdated

### ISSUE THREAD

**Issue by Morphos2** [onebone/EconomyS#254]
i use the plug pocketmine server host program, but it says that your plugin is outdated. please update it, than i can get rid of pocketmoney

**Comment by blah123454321** [comment]
Are you using pocketmine on iOS if so you can use it but if you are on PC then you need to upgrade to the development build

**Comment by Morphos2** [comment]
yes but why i cant use the plugin

**Comment by onebone** [comment]
@Morphos2 I think your server is using old version of PocketMine. I can't explain how to update because I am not iOS user though.
