### ISSUE TITLE
bank,  debt

### ISSUE THREAD

**Issue by astersx** [onebone/EconomyS#256]
Hi! Does economyApi have this yet?
Becouse i hate ideea,  players can take debt on 10 usernames and transfer to 1 username.
I mean players will make more than 10 accounts to take debt from bank,  and transfer to his main account.

**Comment by onebone** [comment]
Debt and bank system was removed a long ago.
And for transferring money to main account, I'm sorry that I can't do anything with that.

You should use plugin which forces player to have only one account or by your server rules.

**Comment by astersx** [comment]
Is cool,  no problem,  becouse new players get only 100$(i set in config)  not big deal :+1: 
Thx for your cool plugins 😍😄😍
