### ISSUE TITLE
EconomyAPI php7 error

### ISSUE THREAD

**Issue by andris155** [onebone/EconomyS#258]
20.02 16:57:07 [Server] CRITICAL RuntimeException: "Threaded members previously set to Threaded objects are immutable, cannot overwrite topList" (EXCEPTION) in "/EconomyAPI_v2.0.9.phar/src/onebone/economyapi/task/SortTask" at line 36
20.02 16:57:07 [Server] CRITICAL Could not execute asynchronous task SortTask: Task crashed

**Comment by Tolo0** [comment]
Same error 😩

**Comment by onebone** [comment]
Are you using plugin from GitHub repository?

**Comment by andris155** [comment]
I used: https://forums.pocketmine.net/plugins/%E2%82%AC%C2%A2onom%C2%A5.30/

**Comment by onebone** [comment]
That plugin is not for PHP7, get the plugin from this repository and your error will be gone.
