### ISSUE TITLE
Nothing happens when players or OP try to buy items from shop or sell

### ISSUE THREAD

**Issue by tnpxxsheepdog** [onebone/EconomyS#264]
I can make the shops fine, however when we try to buy items, nothing happens. No text on the screen or anything. The plugin works because it will say "Shop created" when making  shop. Neither OP or normal players can interact with the shops. 

API, EconomyShop and EconomySell are the only economy plugins we have.

Thanks!

**Comment by Tolo0** [comment]
Sounds like the signs haven't registered. After making a shop sign. Try doing command /reload 
And see if it works.

**Comment by tnpxxsheepdog** [comment]
They register but after a few server reloads the signs don't work anymore.

**Comment by jostie123** [comment]
hello!

i got exactly the same problem here

everything works fine...

until i restart de server  from that moment on the signs don't work anymore.

looked into the shops.yml file but there's nothing inside!

i'have tried the reload command didn't work 

also made a new sign after the reload still the same problem

any ideas for fixing it?

**Comment by tnpxxsheepdog** [comment]
Have the signs stayed permanently?

**Comment by jostie123** [comment]
Yes they did fixed the problem for all my signs

So just place the signs as instructed. 
And every time you are finished placing signs use the /reload command.
Then all the signs get saved in de plugin en then when you restart the server the sign still work.

also worked for me for the airport signs!

**Comment by DiegoGTRatty** [comment]
Okay. That explains why my shops.yml randomly gets erased for no reason. :v
