### ISSUE TITLE
왜 빚 이자 같은 시스템이 없어진거죠,,?

### ISSUE THREAD

**Issue by ebebebeb** [onebone/EconomyS#266]
바쁘신데 괜히 시간낭비 해드려서 죄송한데,, 진짜 뻘글같은 글 올린점 매우 죄송한지만,, 전 버전에는 빚 시스템이 있는데 업데이트하면서 없애시는 이유가 궁금해서 글을 씁니다..

**Comment by 64FF00** [comment]
이자가 너무 많이 붙어서

**Comment by onebone** [comment]
여러 플레이어들이 합심해서 한 계정에 돈을 모으고 은행에 돈을 넣어서 이자를 엄청 크게 불리는 등 여러가지 방면으로 악용될 여지가 많은 기능이었기에 삭제되었습니다.
이 문제 때문에 나온 플러그인이 유저끼리 대출 받기가 가능한 EconomyUsury 입니다.
