### ISSUE TITLE
Incompatible api when using latest economy property plugin

### ISSUE THREAD

**Issue by kabluinc** [onebone/EconomyS#267]
I'm using ImagicalMine php7 and  economy property plugin does not load and say incompatible api. Maybe its not for php7?. The economy api plugin also had this issue at first but I found the php7 version of it from one of the issue tickets someone made.

Please could I have a economy property plugin which is php7 compatible

Thanks,

**Comment by Tolo0** [comment]
Use this on the plugin. 
http://pmt.mcpe.me/api2/

**Comment by kabluinc** [comment]
Its saying "API version 2.0.0 is already declared"

**Comment by Tolo0** [comment]
Do on the server. /version 
And see what API the build ur using supports.

**Comment by kabluinc** [comment]
It says 1.14.0 so I chose 1.14.0 instead of 2.0.0 on the website link u gave me but even then still when I start the server its saying incompatible api version

**Comment by kabluinc** [comment]
After using the php5 version of economy property from the official pocket mine site and then using your link to change it to 1.4 api it worked. Weird thing is that other php7 plugins work fine.

Thanks a lot for your help

**Comment by AndroidHackPro** [comment]
@kabluinc I could send the file?
