### ISSUE TITLE
Set Shop

### ISSUE THREAD

**Issue by roberto12b** [onebone/EconomyS#268]
Brother, type 've searched a lot , but I found this plugin anywhere I are looking for a shop to set plugin.
Type / setshop [player name ]
there the other player typed / shop [player name ]
I think it's a very simple plugin with only 3 commands ,
/ setshop
/ shop
/ delshop
type it would be nice to your pshop plugin, like a privilege for VIPs , and each vip could have only one shop ..... Brother if you have to bring will be very grateful ....

**Comment by onebone** [comment]
What? I can't understand.
