### ISSUE TITLE
update €¢onom¥$ to API 1.14.0 so ios can use €¢onom¥$

### ISSUE THREAD

**Issue by toastedsandwhich** [onebone/EconomyS#274]
Can you update this plugin to 1.14.0 i would like to use this plugin

**Comment by toastedsandwhich** [comment]
Can you please update this plugin to ios i can not use it please

**Comment by dog194** [comment]
Do you use the code from github? Or use the phar from Onebone's website? If from website. then try to use the code from github

**Comment by toastedsandwhich** [comment]
No I did /plugins install EcinomyS
On my served and it said out dated

**Comment by toastedsandwhich** [comment]
Server

**Comment by toastedsandwhich** [comment]
The api is 1.14.0 not the vershon
