### ISSUE TITLE
€¢onom¥$ for 1.6dev (API 2.0.0)

### ISSUE THREAD

**Issue by Rickytornadus** [onebone/EconomyS#277]
Goodmorning everyone.
I have installed the version of 1.6dev PocketMine and the plug-in €¢onom¥$ on PocketMine site is not compatible. Can you tell me if there is a version of this plug-in compatible and, if so, also a link to download the file .phar?
Thanks so much.

**Comment by dog194** [comment]
Just download the code from github. and use devtool to use or pack it.

**Comment by Bidou0418** [comment]
we need a .phar

**Comment by Rickytornadus** [comment]
Hello.
What it said dog194 is actually very simple . You just have to download from GitHub all the Economys files and place them in the plugins folder Pocketmine.
Then go to this site to download DevTools: https://github.com/PocketMine/DevTools/releases/download/v1.11.0/DevTools_v1.11.0.phar
Also put this in the plugin folder and start the server. If it does not display any error type plugin . If you're receiving economys type makeplugin Economys.
Once you have completed close the server and go to plugins / DevTools.
There is the Economys .phar file.
Delete the folder that you had downloaded and replace that with the .phar file.
Done. The plugin is ready.
If you have problems replace this comment.

**Comment by Bidou0418** [comment]
works now
i will have to redo all my shop signs unfortunately

**Comment by Bidou0418** [comment]
Rickytornadus, nothing happens 
would be much easier to update to use with pocketmine 1.6+api 2.0

**Comment by Rickytornadus** [comment]
Try to download the correct version of the Economys from here: https://onedrive.live.com/redir?resid=870FEB30A76A367C!32117&authkey=!AF3LBweCtrAuVjg&ithint=file%2czip

**Comment by Bidou0418** [comment]
works perfect!
thank you

**Comment by Bidou0418** [comment]
anybody have a link for itemcasePe api 2.0?
