### ISSUE TITLE
Update the API to 1.13.1 on the pocketmine website 

### ISSUE THREAD

**Issue by toastedsandwhich** [onebone/EconomyS#278]
I have been waiting for a long time to ise this plugin i use ios not pc not android and the plugin is out dated plz update

**Comment by onebone** [comment]
What is PocketMine version?

**Comment by toastedsandwhich** [comment]
The api is 1.13.1 and the version is plug pocketmine 1.5

**Comment by jasonwynn10** [comment]
On @pmmp PocketMine-MP the new API is `3.0.0-ALPHA1`

**Comment by Kyokuneko** [comment]
Please, can you update EconomyPShop, sell and job in 3.0.0 Alpha 6, i can't do shop in my server without correct plugin.
Ill tested all shop plugins
-ChestShop
-SignShop
-EconomyShop
-Command Shop
No work on api6 :/ and DevTools no work for this plugins....
Im so sad ;-;
(Sorry for my english, im french)
