### ISSUE TITLE
EconomyProperty오류요ㅠㅠ

### ISSUE THREAD

**Issue by ebebebeb** [onebone/EconomyS#28]
음 다른 shop이나 sell, casino는 다 정상적으로 로드가 되는데.. property는 로드가 안되요 계속~~삭제했다가 다시 설치해보고 최신버전도 다써봤는데 오류 뜨네요ㅠㅠㅠ

**Comment by onebone** [comment]
Land 가 설치돼있나요?

**Comment by 64FF00** [comment]
@ebebebeb 무슨 오류?
