### ISSUE TITLE
Lllegal earning way

### ISSUE THREAD

**Issue by vardoOTORI** [onebone/EconomyS#283]
You can earn the EconomyMoney when you use “tree-cutter” in the EconomyJob or the land was bought by the third person

**Comment by SalmonGER** [comment]
@vardoOTORI Yes you can earn money as a tree cutter. But why is it not legal?

**Comment by onebone** [comment]
This cannot be fixed fundamentally because EconomyJob only ignores already cancelled event when Job is handling event
