### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by XShockinFireX** [onebone/EconomyS#286]
[Server thread/CRITICAL]: "Could not pass event 'pocketmine\event\entity\EntityTeleportEvent' to 'EconomyShop v2.0.7': Call to a member function getFolderName() on null on onebone\economyshop\EconomyShop
[Server thread/CRITICAL]: Error: "Call to a member function getFolderName() on null" (EXCEPTION) in "/EconomyShop_v2.0.7.phar/src/onebone/economyshop/EconomyShop" at line 197

**Comment by onebone** [comment]
I can't reproduce your error.

**Comment by XShockinFireX** [comment]
This error occurs on server startup.

**Comment by onebone** [comment]
Could you give me Shops.yml?
