### ISSUE TITLE
Economy Property Error

### ISSUE THREAD

**Issue by JohnTdex** [onebone/EconomyS#287]
Genisys Crash Dump Fri May 13 05:24:47 UTC 2016

Error: Cannot use pocketmine\nbt\tag\String as String because 'String' is a special class name
File: /EconomyProperty_v2.0.6.phar/src/onebone/economyproperty/EconomyProperty
Line: 38
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
此次出错由插件引起

Code:
[29] use pocketmine\level\Level;
[30] use pocketmine\level\Position;
[31] use pocketmine\math\Vector3;
[32] use pocketmine\block\SignPost;
[33] use pocketmine\block\Air;
[34] use pocketmine\tile\Sign;
[35] use pocketmine\block\Block;
[36] use pocketmine\item\Item;
[37] use pocketmine\nbt\tag\Compound;
[38] use pocketmine\nbt\tag\String;
[39] use pocketmine\nbt\tag\Int;
[40] use pocketmine\tile\Tile;
[41] 
[42] use onebone\economyapi\EconomyAPI;
[43] 
[44] use onebone\economyland\EconomyLand;
[45] 
[46] class EconomyProperty extends PluginBase implements Listener{
[47] 	/**
[48] 	 * @var \SQLite3

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Genisys version: 1.1dev #337 [Protocol 60; API 2.0.0]
uname -a: Linux localhost 3.4.67 #17 SMP PREEMPT Fri Apr 10 20:15:52 CST 2015 armv7l
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, android

Loaded plugins:
加载的插件:
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyAuction 2.0.2 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
VoteBan 1.0.3 by GmWM for API(s) 1.12.0
Nick 1.0.1 by AryToNeX for API(s) 1.12.0
iProtector 3.1b by LDX for API(s) 1.9.0, 2.0.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
PurePerms 1.3.7 by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
VIPSlots 0.0.4 by iJoshuaHD for API(s) 1.12.0
MSpawns 1.5 by EvolSoft for API(s) 1.11.0
SimpleAuthHelper 2.0.4 by aliuly for API(s) 1.12.0
ServerLoveMCPE 3.2.1 by TheDeibo, ratchetgame98, and, The Plugin Community! for API(s) 2.0.0
EconomyCasino 2.0.2 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
SexyMOTD 1.0.0 by hoyinm14mc for API(s) 1.14.0, 2.0.0
ItemCloud 1.3 by onebone for API(s) 1.4.0
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyLand 2.0.9 by onebone for API(s) 1.12.0

Pls fix the error,I already submitted a report on the plugin.....I love the plugin so pls fix it =]

**Comment by dog194** [comment]
use the lastest version from github.
