### ISSUE TITLE
permissions

### ISSUE THREAD

**Issue by jynxyboy** [onebone/EconomyS#29]
MINE WONT LET ME IT JUST SAYS YOU DONT HAVE THE PERMISSIONS TO MAKE A SHOP

**Comment by 64FF00** [comment]
@jynxyboy O_o

**Comment by onebone** [comment]
Check if you are OP or your permissions if you have permission plugin.

**Comment by 64FF00** [comment]
@onebone 둘 다 안되면 어떻게 해요

**Comment by jynxyboy** [comment]
ok hanks

**Comment by jynxyboy** [comment]
thanks

**Comment by jynxyboy** [comment]
what happens if u press deop?

**Comment by jynxyboy** [comment]
onebone what do you mean by 'or your permissions if u have the permissions plugin'?

**Comment by 64FF00** [comment]
@jynxyboy Plugin Permissions. http://wiki.bukkit.org/Understanding_Permissions

**Comment by jynxyboy** [comment]
Guys i need to ask u something. Do u know how to turn off safe mode and restart blocklauncher?
