### ISSUE TITLE
2 things...

### ISSUE THREAD

**Issue by MhikeiMPC** [onebone/EconomyS#290]
i need a phar, i tried to use pemapmodder website to turn the zip files into a phar, but it didnt work.
and does the plugins support api 2.0.0? i would like to use it on my mcpe 0.14.2 server because pocketmoney sucks.

**Comment by onebone** [comment]
Plugin on this repository only on API 2.0.0.

What is your problem?

**Comment by MhikeiMPC** [comment]
Ok thanks I need a prebuilt .phar now.

**Comment by NGGNewGen** [comment]
Yea I tried to go to pmt.mcpe.me and convert the .zip files to a .phar file and it doesn't work.. could you please add a .phar file?

**Comment by jasonwynn10** [comment]
did you try to download the entire repo and convert it into a phar?

**Comment by MhikeiMPC** [comment]
I have pre-built phars they are in the zip just drag it into the plugins folder. i also included itemcloud which is required for EconomyS to work

http://adf.ly/1arLFP

**Comment by jasonwynn10** [comment]
just get the plugin off of forums.pocketmine.net

**Comment by MhikeiMPC** [comment]
Those ones are probably outdated

**Comment by jasonwynn10** [comment]
those ones are for PocketMine API 1.13.1

**Comment by MhikeiMPC** [comment]
Which wont work for Genisys or ImagicalMine. They use PHP7 and API 2.0.0. The ones in the zip is for API 2.0.0 and PHP7 so if you have Genisys or ImagicalMine use those. For ClearSky the ones on pocketmine will probably work.

**Comment by jasonwynn10** [comment]
thats the type of server I use

**Comment by MhikeiMPC** [comment]
The phars in the zip should work
