### ISSUE TITLE
Economy SHOP mod

### ISSUE THREAD

**Issue by Bidou0418** [onebone/EconomyS#293]
@onebone 
Please add POTIONS to the shop section.
Here is an example of what someone did; EconomyPotionShop on github
https://github.com/HelloWorld017/EconomyPotionShop

It works fine but he has no support and his shop gives you the effect versus the actual potion.
I am sure you could come up with something better.
I prefer using 1 plugin, with support.

**Comment by Bidou0418** [comment]
?

**Comment by onebone** [comment]
I thought potions were item.

**Comment by Bidou0418** [comment]
OMG had the answer right in front of me..
thanks for the reminder
I had tried before but it didnt work.
thank you again

**Comment by Bidou0418** [comment]
@onebone 
Now i know why it did not work at first
Genisys potion id's are different than from Minecraft
some are the same but not all
I reported this on the Genisys github issues.

**Comment by onebone** [comment]
:D
