### ISSUE TITLE
EconomyPShop

### ISSUE THREAD

**Issue by IsraAtGamings** [onebone/EconomyS#296]
Player cant make pshop i have give that player permision make pshop
But it cant make it
Not respone
It write like this
pshop
1
1
1
No respone.
Soory if bad english :D

**Comment by dog194** [comment]
version?
PHP7? PHP5?
and make sure you install the right plugin (EconomySHOP  EconomyPshop)

**Comment by IsraAtGamings** [comment]
Owh i know now it must use Itemcloud and one questions?
How to make first line pshop change to player name?

**Comment by dog194** [comment]
Pshop does not provide this function.

**Comment by IsraAtGamings** [comment]
XFury server? In first line pshop it showing player name?

**Comment by IsraAtGamings** [comment]
@onebone  how to change it [PShop] to Player name?

**Comment by jasonwynn10** [comment]
in the XFury Server there is a different economy plugin @IsraAtGamings

**Comment by IsraAtGamings** [comment]
Ok :(

**Comment by jasonwynn10** [comment]
if you want a good player shops plugin, i recommend the ChestShops Plugin

**Comment by onebone** [comment]
Pshop doesn't support that function.
And it is strange that it is not responding. Can you provide more information?
