### ISSUE TITLE
`String` special class name in EconomyProperty.php on line 38

### ISSUE THREAD

**Issue by ur2qt2b4got10** [onebone/EconomyS#299]
Getting error when starting up my server: 

Fatal error: Cannot use pocketmine\nbt\tag\String as String because 'String' is a special class name in phar://E:/MCPE/ImagicalMine/plugins/EconomyProperty_v2.0.6.phar/src/onebone/economyproperty/EconomyProperty.php on line 38

[CrashDump_Sat_Jun_4-23.01.15-EAST_2016.txt](https://github.com/onebone/EconomyS/files/299186/CrashDump_Sat_Jun_4-23.01.15-EAST_2016.txt)

**Comment by ur2qt2b4got10** [comment]
Not sure if this issue should go here, IMagicalMine is being sunset TODAY and I would love to use it on the server I spent a week tweaking for me and my kids...

**Comment by onebone** [comment]
You are using PHP7 as your PHP build, but you are using plugin from the forums, which doesn't support PHP7. You should download from this repository and then it'll work.
