### ISSUE TITLE
shop isnt working

### ISSUE THREAD

**Issue by MhikeiMPC** [onebone/EconomyS#300]
i do this:

shop
0
50
64

and its not making the shop. i need this so i can make mining easier also admin shop isnt working either! only pshop works but it keep saying i dont have an itemcloud account when i made one and put in my shop items in it! please fix it!!!!!!

**Comment by dog194** [comment]
plugins version
server version

**Comment by MhikeiMPC** [comment]
EconomyAPI v2.0.9
EconomyAuction v2.0.2
EconomyCasino v2.0.2
EconomyJob v2.0.4
EconomyLand v2.0.9
EconomyProperty v2.0.6
EconomyPShop v2.0.2
EconomySell v2.0.7
EconomyShop v2.0.7
EconomyTax v2.0.3
EconomyUsury v1.0.1

server version Genisys #422 0.14.3

**Comment by dog194** [comment]
For Genisys php7, You need to re-download the lastest version from github. And use new way to creat a admin shop/sell.
and for PSHOP, you need to download itemclound.phar

**Comment by MhikeiMPC** [comment]
i do have itemcloud but it keep saying i dont have an itemcloud account when i registered already

**Comment by onebone** [comment]
New version of EconomyShop doesn't support creating shop with signs.
Use
/shop create
command instead.

**Comment by MhikeiMPC** [comment]
Ok thanks is this how i can create admin shops too?
