### ISSUE TITLE
EconomyProperty PHP7 version doesn't work with PHP7 (EconomyProperty PHP7 버전 플러그인 PHP7 미작동 오류)

### ISSUE THREAD

**Issue by Johnmacrocraft** [onebone/EconomyS#305]
EconomyProperty PHP7 version (I downloaded it from onebone.me) doesn't work on PHP7, it shows "Cannot use Float as string name because it's special name" (Actually forgot message but it was just like it) and server crashes. Sorry for no screenshot. Tested on PocketMine-MP for Android (Custom user put php7) using Genisys core.
EconomyProperty PHP7 버전 (onebone.me에서 다운로드)이 PHP7 버전에서 작동하지 않습니다. 사용하려고 하면 Float 오류 (위 영어 본문 참조)가 발생하면서 서버가 크래시됩니다. 스크린샷이 없는 점은 양해 부탁드립니다. PocketMine-MP 안드로이드 버전 (직접 넣은 PHP7 버전)에서 Genisys 코어로 테스트되었습니다.

**Comment by dog194** [comment]
I donot know the version on onebone.me . But download the version from guihub and has a test are recommended.

**Comment by MattWAnderson** [comment]
More than likley same issue as here: https://github.com/onebone/EconomyS/issues/311
