### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Sandertv** [onebone/EconomyS#307]
Hi!
This plugin (or these actually) is really cool and unmissable in a server. I got a suggestion for one more addon plugin which could make it even cooler. Maybe you could make an addon so people can 'buy commands'. So this would mean they basically need a certain amount of money when you tap a sign and a command get's executed if you have enough money to buy this command.
I hope you could take this in consideration and hopefully integrate it!

**Comment by onebone** [comment]
Unfortunately, I don't have plan to create more plugin for this package.
