### ISSUE TITLE
[Question] is the new display style for shop permanent?

### ISSUE THREAD

**Issue by Thunder33345** [onebone/EconomyS#308]
personally i like the old style
EDIT1:
what i mean by new style i mean now it is displaying on a block? where you tap a block to buy

**Comment by onebone** [comment]
Yes, it is permanent. If you want old style, just designate sign for shop block for now.

**Comment by Thunder33345** [comment]
hmm so you now cannot just have two together?
and it kinds of suck how you cant break the shop block (for advance users they may know what they are doing add a perm node to bypass anti break (default:false) one for advance users)
