### ISSUE TITLE
EcconomyProperty <make> creates blank floating sign

### ISSUE THREAD

**Issue by CRBairdUSA** [onebone/EconomyS#312]
After I use /property make x   All I get is a blank sign floating. over where the property should be. Cannot interact past that. Any help is appreciated. 

Using Economy$ 5.7 and genisys. 
Downloaded Phar through MultiCraft plugin system

**Comment by laurobeleche** [comment]
I had the same problem , however when the server restarted the signs appeared normal and the plugin again function normally. I direct download here the repository .
