### ISSUE TITLE
Economy Land bug

### ISSUE THREAD

**Issue by laurobeleche** [onebone/EconomyS#313]
If the player is outside the protected area and touch in a chest or break a block, the action is not canceled. It is to fix it?

**Comment by SleepSpace9** [comment]
In this case you have to use the "white-world-protection". Then every player first needs to buy the land before it can be changed by him.
But I think chests aren't protected though, please correct me if I'm wrong. There are other plugins for this purpose (e.g. https://github.com/MinecrafterJPN/PocketGuard).

**Comment by laurobeleche** [comment]
The chests give protected yes, but with this bug , it has to be in the middle of the protected area out of reach of those outside the protected area.

**Comment by SleepSpace9** [comment]
Ahh ok, I understand.

**Comment by onebone** [comment]
I don't understand what you are meaning.

**Comment by laurobeleche** [comment]
When a player protects the area, there is also a protection for onInteract event just , but if the onInteract is used in a chest inside the protected area , however , the player is clicking is outside the protected area , it can interact normally is as if the protection does not exist or did not affect the onInteract how it affects the onBreak .

**Comment by onebone** [comment]
Are you sure your permission are set correctly?

**Comment by laurobeleche** [comment]
Do not set up the permissions , is the standard that came .

**Comment by onebone** [comment]
I have tried it now, it protects chest even if the player is outside of protected area. What version of EconomyLand are you using?

**Comment by laurobeleche** [comment]
2.0.9

I downloaded here 2 months ago.

**Comment by onebone** [comment]
Strange. Have you tried re-downloading?

**Comment by laurobeleche** [comment]
I tried yes , I will make a video reproducing the bug so that you can see

**Comment by jasonwynn10** [comment]
what server software?

**Comment by laurobeleche** [comment]
Genesys

**Comment by jasonwynn10** [comment]
where is the video?

**Comment by laurobeleche** [comment]
I downloaded again and this time did not find problems, sorry for the inconvenience.

**Comment by jasonwynn10** [comment]
then this issue can be closed?
