### ISSUE TITLE
Pshop/itemcloud

### ISSUE THREAD

**Issue by Infernus101** [onebone/EconomyS#317]
Why cant you reproduce error? Whats the problem?

**Comment by onebone** [comment]
My PShop works properly: I can buy items, ItemCloud works properly.
Try re-downloading ItemCloud from https://github.com/onebone/ItemCloud

**Comment by Infernus101** [comment]
And how to stop players from putting signs for shop in a world?

**Comment by Infernus101** [comment]
is there any permission for that?

**Comment by Infernus101** [comment]
How does sign permissions work?

**Comment by onebone** [comment]
Also, you can manage it by permission.

**Comment by Infernus101** [comment]
THANKS BRO!!!
