### ISSUE TITLE
오류제보 

### ISSUE THREAD

**Issue by Matunserver** [onebone/EconomyS#32]
/land invitee 하면 1 , 1, 1, 1이나오고

/land invite r: 명령어도 플레이어가 초대되지않앗슺니드 라고뜾니더 분명초대가되어잇는대말이죠

**Comment by 64FF00** [comment]
@Matunserver ???

**Comment by Matunserver** [comment]
@64FF00 PurePer플긴아주잘쓰고잇어요 ㅋㅋ
