### ISSUE TITLE
Economy Land bug.

### ISSUE THREAD

**Issue by Tolo0** [onebone/EconomyS#320]
Hey onebone. they is a bug that lets players claim unlimited amount of land. i have it set for players to only be able to claim 2 plots of land but if a player changes hes name with capitals then he can claim another 2 plots. then he can change a different leter in hes name and claim again. 

Example.

I claim 2 plots of land with "Tolo".
then i change my name to "TolO" and claim another 2 plots.
then change my name to "ToLO" and so on.

**Comment by Kyokuneko** [comment]
go to your plugin files in config and change the max amount of land per player
