### ISSUE TITLE
Land Ownership Case Sensitive

### ISSUE THREAD

**Issue by markkrueg** [onebone/EconomyS#322]
Land ownership should not be case sensitive. Player names in Pocketmine have never paid attention to case.

Example: Player name bob = BoB = bOb

If player name bob buys some land, but then changes his name to BoB, then he no longer owns the land. But BoB and bob should be the same. 

The EconomyS code should ignore case when checking land ownership.

I believe this is related to issue #320

**Comment by jasonwynn10** [comment]
what if there are two different players with BoB as one and BOB as another? then they would both own the same property and there would be an issue

**Comment by Tolo0** [comment]
jasonwynn10 that isnt a problem. no one can have the same name it doesn't matter if its Bob or bob its still the same name and counts as 1 account. what  markkrueg sed is a problem.  on my server i have it set to 2 land claims only but players change capitals and abuse it by claiming more than 2 times.

**Comment by jasonwynn10** [comment]
The easiest fix for that would be to use the strtolower function every time the economy system deals with player names, but it's a very trivial thing to find and adjust all the mentions of player names in the plugins

**Comment by JacquelineJohnson39** [comment]
I have a bunch of virus on my Facebook and phone don't know what I'm doing
