### ISSUE TITLE
EconomyProperty Doesn't work in clearsky 1.1-php7

### ISSUE THREAD

**Issue by Mathshyun** [onebone/EconomyS#323]
EconomyProperty Doesn't work in clearsky 1.1-php7
there is a crashdump

ClearSky Crash Dump Mon Aug 29 19:53:00 AWST 2016

Error: Cannot use pocketmine\nbt\tag\String as String because 'String' is a special class name
File: /plugins/EconomyProperty_v2.0.6.phar/src/onebone/economyproperty/EconomyProperty
Line: 38
Type: E_COMPILE_ERROR

**Comment by SalmonGER** [comment]
I think u don't use the latest version of EconomyS
