### ISSUE TITLE
Nukkit / EconomyProperty error

### ISSUE THREAD

**Issue by jdongel2004** [onebone/EconomyS#327]
원본님.. 누킷 사용증인 힌국인입니다.. main 뭐라뭐라 하면서 textcontainer 파일을 바꿔야한다는거 같은데, 어떻게 해야라나요  자바는 아직 못다뤄서.. 부탁드립니다..제발..

**Comment by onebone** [comment]
https://jenkins.onebone.me/job/EconomyProperty/lastSuccessfulBuild/artifact/target/economyproperty-1.0.0-42.jar

덧붙여서 여기는 Nukkit 용 이코노미의 버그 리포트를 하는 곳이 아닙니다.
다음부터는 https://github.com/EconomyS/ 에서 리포트 해주세요.
