### ISSUE TITLE
mysql bug

### ISSUE THREAD

**Issue by SuperAlecs** [onebone/EconomyS#339]
Warning: mysqli::ping(): Couldn't fetch mysqli in /root/lobby/plugins/EconomyAPI_1/src/onebone/economyapi/task/MySQLPingTask.php on line 37 
after i start the server the console say this, but mysql status is active, please fix this bug

**Comment by onebone** [comment]
I think this is a bug of mysqli, I will add auto reconnecting.

**Comment by SuperAlecs** [comment]
ok thanks so much!

**Comment by SuperAlecs** [comment]
when you update? I urgently needed

**Comment by onebone** [comment]
Though it is not tested since I cannot reproduce the error, it will work. Tell me if it doesn't work.

**Comment by SuperAlecs** [comment]
the money work well but the console say again the same message
