### ISSUE TITLE
ECONOMY API 소스코드 오류

### ISSUE THREAD

**Issue by KIKIIIRI** [onebone/EconomyS#342]
이상하게 ECONOMY API한글화가 안되가지고
ATOM으로 소스코드를 살펴봤는데

소스코드 9번줄과
소스코드 1863번줄에서 한국어 코드가 다른게 발견되었습니다
PMMP에서 몇번이나 태스트했으나 게속 변환이 안되길레
9번줄의 ko를 kr로 고친뒤 저장 및 다시 서버재실행했는데
API를 인식 못하더라고요
이부분 수정 부탁드립니다

**Comment by onebone** [comment]
9번째 줄은 라이센스 주석일테고 1863줄은 존재하지 않는데 뭐가 다르다는 건지 설명해주실 수 있으신가요

**Comment by KIKIIIRI** [comment]
ATOM 으로 API 분해해보면
9번쨰 줄이 language : ko 로 되있고
한국어 명령어가 나열되고

1863번쨰 줄에는 kr -> 한국어 라고 되있거든요?

(ATOM 으로 확인해주시기바랍니다 라느걸로 봐서 안뜨는것일수도 있네요)
PHAR파일 직접 열어서 확인한겁니다 확인부탁드립니다

**Comment by KIKIIIRI** [comment]
사진을 보내드리면 이해되실것같은데 사진 보낼방법이 없네요

**Comment by onebone** [comment]
수정하신 9번째 줄은 아무 곳에서도 쓰이지 않아서 어차피 별 영향을 주지 않을텐데 수정하신 의미가 있으신가요?

**Comment by KIKIIIRI** [comment]
그 서버구동상태에서
API언어 설정할때
한국어로하면 설정이 먹히지않거든요?
알아보니까 저 2개가 같아야되는데 달라가지고 그러더라고요
혹시나 하고 수정하면 무조건 API 인식불능되버리니 이거 해결가능하시다면해주시기바랍니다

**Comment by KIKIIIRI** [comment]
setlang 명령어를 사용해서 한국어 설정해도
한국어로 바뀌었다는 응답은 나오나 여전히 영어로만 출력됩니다

**Comment by onebone** [comment]
다른 언어도 시도해보셨나요?

**Comment by KIKIIIRI** [comment]
이제 되네요 감사합니다
해결됬어요
