### ISSUE TITLE
Incompatible API

### ISSUE THREAD

**Issue by GoldCodes** [onebone/EconomyS#343]
I am not able to use this plugin on my server.

**Comment by onebone** [comment]
Please provide your what version of server you are using, and version of the plugin.

**Comment by GoldCodes** [comment]
It is the new pocketmine with the latest release

**Comment by onebone** [comment]
Please provide the output of `/version` and `/plugins` command.

**Comment by GoldCodes** [comment]
api version 2.1.0 Pocketmine-MP 1.6.1dev#103

**Comment by onebone** [comment]
Do you get error when using the plugin?

**Comment by GoldCodes** [comment]
I fixed it!

**Comment by onebone** [comment]
Great :D

**Comment by fmonera** [comment]
How did you fixed it? I am having the same problem:

This server is running PocketMine-MP version 1.6.2dev "Unleashed" (API 3.0.0-ALPHA3)
Economy plugin downloaded from Jarvis as of 4th February 2017.
