### ISSUE TITLE
누킷버전 Economy.API 버그입니다!

### ISSUE THREAD

**Issue by anto0423** [onebone/EconomyS#345]
누킷으로서버를 열고 이코노미를 API 플러그인을 사용합니다.
다름이 아니라, Topmoney를 치면 돈순위가 낮은사람부터 뜨고 pay 기능이 되지 않습니다.
수정요청해봅니다. 감사합니다.

**Comment by onebone** [comment]
누킷 버전은 https://github.com/EconomyS/EconomyAPI/issues 에 등록해두세요
