### ISSUE TITLE
You have some mistakes!

### ISSUE THREAD

**Issue by RottenBread** [onebone/EconomyS#349]
한쿸인이니 한국말로 씁니다
사실 저도 수정할수는 있지만 

그냥 귀찮아서 이러는거 절대 아니에요 쿨럭

이번에 올라온 API 3.0.0 에서 아직 친절히 베타버젼이라고
3.0.0-ALPHA1 로 작성을 하셔야 정상작동을 한다고 하더라고요

그래서 수정 요청합니다 일부 중요한 파일은 제가 고쳐놓을께요

**Comment by onebone** [comment]
3.0.0 ALPHA1 은 지원 계획이 없습니다.

3.0.0 을 미리 PR 받아둔 건 제가 그 PR 을 언제 받을지 모르는 불확실성에 의해서 받은 거라고 보시면 됩니다.

**Comment by RottenBread** [comment]
엙 그렇군요 답변 감사합니다
