### ISSUE TITLE
이코노미 상점 오류

### ISSUE THREAD

**Issue by qazplmwsxok86** [onebone/EconomyS#35]
shop
1
1
1
이거 맞나요?? 터치해도 안주는 때 설마 권한 주는 명령어가 있어요??

**Comment by qazplmwsxok86** [comment]
참고로 상점 만든고 사는 권한 명령어도 있나요.

**Comment by onebone** [comment]
상점을 만들 때 필요한 권한은 있습니다.
economyshop.shop.create
상점 제거:
economyshop.shop.remove

퍼미션 플러그인이 없으신 경우엔 OP 가 지급될 경우 자동적으로 권한이 지급되니 신경 안쓰셔도 됩니다.
