### ISSUE TITLE
EconomyShop and sell (Not Working On Many 1.0 Forks)

### ISSUE THREAD

**Issue by SirOptic** [onebone/EconomyS#353]
Hey onebone economy has been one of my most favorite plugins.I have used it from 0.16.0 and down.Recently I just opened a server in 1.0 the shop signs and shop sell signs stopped working.I use Tesseract and Elywing may you please find the reason why shop signs and sell signs aren't working.Thats the only issue I have and by the way the plugins load perfectly fine.

**Comment by XFizzer** [comment]
Works with elywing fine

**Comment by onebone** [comment]
Doesn't it send any message?

**Comment by isoz** [comment]
not working for me either, no errors, i place the sign down and its not recognizing the lines.

**Comment by isoz** [comment]
02:10:59 | thread:INFO > Enabling EconomyShop v2.0.7
02:10:59 | thread:NOTICE > [EconomyShop] Data provider was set to: Yaml

Notice: Undefined offset: 9 in /home/plugins/EconomyShop/src/onebone/economyshop/EconomyShop.php on line 79

Notice: Undefined offset: 3 in /home/plugins/EconomyShop/src/onebone/economyshop/EconomyShop.php on line 80

Notice: Undefined offset: 3 in /home/plugins/EconomyShop/src/onebone/economyshop/EconomyShop.php on line 81

Notice: Undefined offset: 3 in /home/plugins/EconomyShop/src/onebone/economyshop/EconomyShop.php on line 81

Notice: Undefined offset: 0 in /home/plugins/EconomyShop/src/onebone/economyshop/EconomyShop.php on line 83

Notice: Undefined offset: 1 in /home/plugins/EconomyShop/src/onebone/economyshop/EconomyShop.php on line 83

Notice: Undefined offset: 2 in /home/plugins/EconomyShop/src/onebone/economyshop/EconomyShop.php on line 83

Notice: Undefined offset: 3 in /home/plugins/EconomyShop/src/onebone/economyshop/EconomyShop.php on line 83

Notice: Undefined offset: 9 in /home/plugins/EconomyShop/src/onebone/economyshop/EconomyShop.php on line 85

Notice: Undefined offset: 9 in /home/plugins/EconomyShop/src/onebone/economyshop/EconomyShop.php on line 86
02:10:59 | thread:CRITICAL > pocketmine\utils\LevelException: "Undefined Level reference" (EXCEPTION) in "/src/pocketmine/level/Position" at line 90

**Comment by tytot** [comment]
I have the same problem, I can't create shops even when I follow the correct format...

**Comment by isoz** [comment]
It works when I do /shop create but the format inside the shops.yml is different and everything, is this how its suppose to be now? this is not cool :s

**Comment by isoz** [comment]
Ok it works again for me by downloading the EconomyAPI.phar from the JENKINS server and using my old EconomyShop

**Comment by dterweij** [comment]
Was looking for newer versions of plugins because newer API requirements. I can confirm that the shop does not working. What has changed? What the new yml file structure needs to be? 
Got a few plugins working, but still need a lot new updated plugins :( Not always a API version change in plugin.yml is doing the trick :(

```
Notice: Undefined offset: 3 in /home/danny/minecraft-pe/plugins/EconomyShop/src/onebone/economyshop/EconomyShop.php on line 83
PHP Notice:  Undefined offset: 9 in /home/danny/minecraft-pe/plugins/EconomyShop/src/onebone/economyshop/EconomyShop.php on line 85

Notice: Undefined offset: 9 in /home/danny/minecraft-pe/plugins/EconomyShop/src/onebone/economyshop/EconomyShop.php on line 85
PHP Notice:  Undefined offset: 9 in /home/danny/minecraft-pe/plugins/EconomyShop/src/onebone/economyshop/EconomyShop.php on line 86
```

**Comment by onebone** [comment]
@dterweij @isoz @tytot Could you provide me your Shops.yml?
