### ISSUE TITLE
Drop invisible (mcpe-1.0) problem economy shop and sell

### ISSUE THREAD

**Issue by Andrew1481432** [onebone/EconomyS#354]
### Issue description

In version 1.0 there was the problem became drop becomes invisible after 5 minutes (sorry my english bad)

Reported: https://github.com/pmmp/PocketMine-MP/issues/257

**Comment by Muqsit** [comment]
#duplicate
You are not allowed to create multiple threads for the same issue.
It won't get you more attention ;)

**Comment by onebone** [comment]
Does this really happen to EconomyShop or Sell? I think you are talking about item despawn, but EconomyShop and Sell doesn't use PocketMine's built-in Item entity.

**Comment by Bazilio-sun** [comment]
I confirm the problem: item disappear after 5 minutes. It remains only a shadow.
Mr. Onebone do you plan to fix this issue? 
Or, maybe you return plates, as before?
Best regards, Bazilio :)

**Comment by Bazilio-sun** [comment]
For Andrew1481432: please, contact to me by email: github.com@bazilio.ru.

**Comment by Andrew1481432** [comment]
Fix?
