### ISSUE TITLE
I cannot buy / sell !

### ISSUE THREAD

**Issue by RottenBread** [onebone/EconomyS#356]
08:47:46 | Elywing thread:CRITICAL > Unhandled exception exe|cuting command '구매 1' in 구매: Call to a member function getMoney() on null                                                                  
08:47:46 | Elywing thread:CRITICAL > Error: "Call to a member function getMoney() on null" (EXCEPTION) in "/plugins/EconomyAPI_v2.0.9.phar/src/onebone/economyapi/EconomyAPI" at line168                                                     
            
I used CreativeEconomy , EconomyPShop and  EconomyShop/Sel.
But I can't buy and Sell!

php ver : 7.0.3
API : 3.0.0-ALPHA1 ( used PluginForceLoader )
EconomyAPI ver : 2.0.9

**Comment by onebone** [comment]
Please provide your config.yml
