### ISSUE TITLE
Add new items

### ISSUE THREAD

**Issue by TheClimbing** [onebone/EconomyS#359]
Hi @onebone so PocketMine-MP has changed a lot and we need the best Economy plugin but it doesn't have all new items.And I was wondering if you can help us?

**Comment by onebone** [comment]
EconomyS uses PocketMine's built-in item list. It must have all items which PocketMine has.

**Comment by TheClimbing** [comment]
Hmm ok but does this apply to forkes because they have their built-in item lists too but I don't have every item ?

**Comment by onebone** [comment]
Even if there is no item in the fork, it must be able to sell item. Item name will be something like Air, though.

**Comment by TheClimbing** [comment]
I'm running Genisys and when I try to sell let's say enchantment table it say that block 116 is not supported on EconomySell
