### ISSUE TITLE
이코노미 랜드 땅소지개수 오류

### ISSUE THREAD

**Issue by Matunserver** [onebone/EconomyS#36]
이코노미의 콘픽파일을 수정해서 NaN을 2로 바꿧지만 땅은 2개가아니라 무한대로사집니다.

**Comment by onebone** [comment]
저에게는 그 문제가 발생하지 않네요. 최신 버젼을 사용하고 계신가요?

**Comment by 64FF00** [comment]
좋은거 아닌가요 무한대로 사지면 ㅋㅋㅋ

**Comment by Matunserver** [comment]
@onebone 프로펄티를 통해사면 무한대로 사집니다
