### ISSUE TITLE
Exchange rate algorithm

### ISSUE THREAD

**Issue by SOF3** [onebone/EconomyS#361]
I'm aware that you have no exchange rate implementation yet, but in case you are ever adding, I'd like to point out an issue in your algorithm as of v4.7

In your old algorithm: https://github.com/onebone/EconomyS/blob/v4.7/EconomyShopPlus.php#L67, I simplify it into this line:

```php
$price = round($oldPrice * (1 + rand(~$maxChange, $maxChange) / 100), 2);
```

This algorithm will have a tendency of decrease in price. Since the equation `y = (1 + x%) * (1 - (x + 1)%)` (I convert `~$x` into `-$x - 1`) has a slope of 0 <= m <= 1 (see [this curve](https://www.desmos.com/calculator/nfsserp7am): x is the maximum exchange rate and y is the median exchange ratio every time; as you can see, the mean exchange ratio is below 1, i.e. it would decrease every time), in the long term, the prices will decrease.

Since `rand()` returns a linearly random number, it is recommended that:

1. A symmetric randomness centered at x=0 should be used. Therefore, instead of using the tilde (binary NOT) operator `~`, use `-` for the minimum: `$rand = rand(-$maxChange, $maxChange);`
2. A function where `f(x) * f(-x) = 1` should be used. The exponential function `pow` is a good example.

For example, this algorithm:

```php
const EXCHANGE_COEFFICIENT = 1.01;
// According to the law log_m(x) = k log_n(x), EXCHANGE_COEFFICIENT can be any numbers greater than 1 
// to produce a sensible range of exchange-degree and will only enlarge or diminish
// the curve along the y-axis

$max = $config["exchange-degree"];
$rand = -$max + lcg_value() * 2 * $max;
$price *= pow(EXCHANGE_COEFFICIENT, $rand);
```

(In short, the algorithm suggested above is to generate a random number of times that the price has increased by 1% or undone an increase of 1%)

P.S. Why I suddenly remembered this: I was on the bus sleeping, then the old EconomyS signs suddenly caught me and I suddenly remembered the existence of exchange rate, and then I suddenly wanted to know if this algorithm was correct.

**Comment by onebone** [comment]
Oh, at that time, maybe I didn't know ~$x equals -$x - 1

Well, I don't have plan to add more plugin from now, though, thank you for having interest!
