### ISSUE TITLE
Sort Task crashing

### ISSUE THREAD

**Issue by TheClimbing** [onebone/EconomyS#362]
Whenever I use topmoney SortTask crashes with the following error:
`[Asynchronous Worker #2 thread/CRITICAL]: RuntimeException: "Threaded members previously set to Threaded objects are immutable, cannot overwrite topList" (EXCEPTION) in "/EconomyAPI3.0.phar/src/onebone/economyapi/task/SortTask" at line 36
[22:23:45] [Asynchronous Worker #2 thread/DEBUG]: #0 (): pocketmine\scheduler\AsyncTask->run(boolean)
[22:23:45] [Server thread/CRITICAL]: Could not execute asynchronous task SortTask: Task crashed
`
Running Genisys 1.0.0.16 php 7.0.15

**Comment by onebone** [comment]
Are you using latest version from GitHub?

**Comment by TheClimbing** [comment]
Yes

**Comment by onebone** [comment]
Could you provide me how to reproduce this error?

**Comment by ClanEmo** [comment]
Try removing Economy Property

**Comment by dylancobiness** [comment]
Thank you sooooo much!!!!
