### ISSUE TITLE
Buy Sign Doesn't work on new release

### ISSUE THREAD

**Issue by epicslendyz** [onebone/EconomyS#363]
I have install the latest version of Economy API
And Economy Shop. I create a sign that goes like
"shop
25
Grass
0"
But it doesn't work
No message appear can someone help me to fix this?

**Comment by Tolo0** [comment]
i think the sign feature was removed with the latest version. theys a new method now

**Comment by epicslendyz** [comment]
oks thanks for the info, so how to make it?

**Comment by Tolo0** [comment]
its now like 
usage: /shop <create|remove|list> [item[:damage]] [amount] [price] [side]

**Comment by epicslendyz** [comment]
its said that the command doesnt exist when i use in game

**Comment by Tolo0** [comment]
try
/shop create 1 10 100

that would be 
Shop
stone
10
$100

**Comment by epicslendyz** [comment]
"touch where you want to create" what does this mean

**Comment by epicslendyz** [comment]
Warning: include(phar://C:\Users\Touch\Desktop\Minecraft\plugins\EconomyShop (2).phar/src\onebone\economyshop\event\ShopCreationEvent.php): failed to open stream: phar error: Cannot open phar archive "C:/Users/Touch/Desktop/Minecraft/plugins/EconomyShop (2).phar" for reading in phar://C:/Users/Touch/Desktop/Minecraft/Genisys_86c5cf0.phar/src/spl/BaseClassLoader.php on line 128

Warning: include(): Failed opening 'phar://C:\Users\Touch\Desktop\Minecraft\plugins\EconomyShop (2).phar/src\onebone\economyshop\event\ShopCreationEvent.php' for inclusion (include_path='.;.\ext') in phar://C:/Users/Touch/Desktop/Minecraft/Genisys_86c5cf0.phar/src/spl/BaseClassLoader.php on line 128
[19:28:15] [Server thread/CRITICAL]: "Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'EconomyShop v2.0.7': Class onebone\economyshop\event\ShopCreationEvent not found on onebone\economyshop\EconomyShop
[19:28:15] [Server thread/CRITICAL]: ClassNotFoundException: "Class onebone\economyshop\event\ShopCreationEvent not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 131

this load up

**Comment by Tolo0** [comment]
touch a glass block and it should create a shop

**Comment by epicslendyz** [comment]
any possible way to sell them?

**Comment by Tolo0** [comment]
same method with economy sell i guess

**Comment by RocoWayne** [comment]
en pocketmine 1.0.5 it does not work anymore (the sings) And the other way neither

**Comment by RocoWayne** [comment]
any news?

**Comment by Tolo0** [comment]
You must be doing something wrong because it works fine.

**Comment by RocoWayne** [comment]
I try the 2 things: creating a sign and try by command like you says early and does not work (the command says that not exists)

**Comment by Tolo0** [comment]
whats ur server ip n port il log on and try if u want

**Comment by onebone** [comment]
Sign shop was removed in the latest version, I will re-implement shop again soon.

**Comment by KairusDarkSeeker** [comment]
@onebone you should use NBT tags for the sign shop

**Comment by onebone** [comment]
@KairusDarkSeeker As I know, I do not need to directly access NBT if I am just modifying sign text.

**Comment by RocoWayne** [comment]
@onebone i hope so!

**Comment by KairusDarkSeeker** [comment]
@onebone For the sign shop data not for the text lol

**Comment by DerddyDert** [comment]
So the sign shops coming back? That would be great.
