### ISSUE TITLE
Bug in economyapi (you can win and spend money from other users)

### ISSUE THREAD

**Issue by RocoWayne** [onebone/EconomyS#367]
If you dont login (im using serverauth in my server) you can move around and play minigames, Win and spend money. You can change your name and spend money of any player without even login to the server.

**Comment by DerddyDert** [comment]
Just block the command at the spawn if you are using an bad auth plugin

**Comment by onebone** [comment]
EconomyS blocks spending money with permissions. It seems that ServerAuth doesn't block permission before login, please ask them to block permissions before logging in.
