### ISSUE TITLE
Um entities just fall on ground in front of shop?

### ISSUE THREAD

**Issue by derddy** [onebone/EconomyS#370]
Thats a horrible waste of resources and counter intuitive if you clean up entities. Besides they just randomly disappear and you cant put them in glass. Anyone else experience this or come up with a fork/workaround to pull out the entities feature? Id rather not fix this if someone else has...

**Comment by onebone** [comment]
EconomyShop and EconomySell has argument to prevent item from displayed.

`/shop <create|remove|list> [item[:damage]] [amount] [price] [side]`

Just provide side with '-1'.
