### ISSUE TITLE
Shop and sell

### ISSUE THREAD

**Issue by DerddyDert** [onebone/EconomyS#371]
I apologize but since there is no documentation on the new shop and sell procedures would you please explain all the [side] options? Is there a way to put a shop or sell item into either a frame or glass? Thanks!

**Comment by onebone** [comment]
Side decides where to put item relative to position of the shop.

Unfortunately, it does not support putting items on frame.
To put item in a glass, you should provide side as -1 or "sell" (or "shop").

You can also provide side as 
"up", "down", "north", "east", "west", "south", "sell" (or "shop"), "none".
