### ISSUE TITLE
Shop items wort work until relog

### ISSUE THREAD

**Issue by DerddyDert** [onebone/EconomyS#373]
(this was for the signshop version on jenkins) If I buy food in a shop I cannot eat it until relog. If I buy a shovel in the shop, I can not break dirt or sand with it until relog. Other things I can break with the shovel but not its intended blocks. Same for axe, no chopping wood until relog etc...

**Comment by edwinyoo44** [comment]
Fix it .
In #390

**Comment by edwinyoo44** [comment]
Fix it .
In #390
