### ISSUE TITLE
MCPE-1.1

### ISSUE THREAD

**Issue by Enrick3344** [onebone/EconomyS#377]
We need an update compatible with API 3.0.0-ALPHA5 and ALPHA6 please. theres some stuff that are not correct in the code with the new version in EconomyAPI and EconomyShop

**Comment by Letboes** [comment]
Do you have the same Problem that EconomyAPI will deactivated in 1.1.0?

**Comment by onebone** [comment]
It is now compatible with ALPHA7 in the latest commit.
