### ISSUE TITLE
EconomyAPI Colors?

### ISSUE THREAD

**Issue by XDqrkneZ** [onebone/EconomyS#380]
How do i add colors? i've tried the things i know but none of them worked

mymoney-mymoney: 'Â§aBalanceÂ§7: %MONETARY_UNIT%%1'

mymoney-mymoney: '§aBalance§7: %MONETARY_UNIT%%1'

mymoney-mymoney: '&aBalance&7: %MONETARY_UNIT%%1'

**Comment by onebone** [comment]
§ must work. Did you change language to 'user-define'?
