### ISSUE TITLE
Can't Remove Shops

### ISSUE THREAD

**Issue by XElectricX** [onebone/EconomyS#382]
Like the title says. I downloaded the plugin and put a few shops for testing purposes, but they refuse to be deleted. I did /shop remove and it gives me the confirmation in chat that the shop was removed, but it does not go away. I even went to Shops.yml to delete them from there and the file just repopulates itself on the next restart.

On a related note: Any way to still make shops via signs? Was much simpler and didn't cost me my sanity.

**Comment by SourSmirnoff** [comment]
lol man same the struggle is real with creating signs thru commands lmao

**Comment by XElectricX** [comment]
I still have floating stones and a flower shop I can't delete. 😢

**Comment by slowfozzy** [comment]
For now:
1. Stop the server
2. Remove shop(s) from Shops.yml
3. Restart server, you can now break the block you assigned the shop to.

**Comment by servantthought** [comment]
Tried it the shop info refills after restarting the data
