### ISSUE TITLE
compatibility for pmmp api3/blocks branch

### ISSUE THREAD

**Issue by optimusprime338** [onebone/EconomyS#383]
Hey can you please make plugins compatible with pmmp api3/blocks branch please.. I tried to fix everything . plugins loads perfectly. but for example shop signs are not working . I change SIGN_POST to STANDING_SIGN too!!

**Comment by dktapps** [comment]
api3/blocks is an in-dev branch and as such you should not expect plugin developers to provide support for it, especially since the changes might not ever be merged to the main branch.

**Comment by optimusprime338** [comment]
ok! thanks
