### ISSUE TITLE
Crash E_COMPILE_ERROR - EconomyAPI: Dev build #12

### ISSUE THREAD

**Issue by teracube** [onebone/EconomyS#384]
Hi, 
server refused to start

Tested :
EconomyAPI: Dev build #12
with
PocketMine-MP_1.6.2dev-311_7d777510_API-3.0.0-ALPHA7.phar

CrashDump :

PocketMine-MP Crash Dump Wed Jul 26 09:15:32 CEST 2017
Error: Declaration of onebone\economyapi\command\MyMoneyCommand::execute(pocketmine\command\CommandSender $sender, $label, array $params) must be compatible with pocketmine\command\Command::execute(pocketmine\command\CommandSender $sender, string $commandLabel, array $args)
File: EconomyAPI.phar/src/onebone/economyapi/command/MyMoneyCommand
Line: 39
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: EconomyAPI v5.7.1-dev1

Code:
[30] 
[31] 		if($sender instanceof Player){
[32] 			$money = $this->plugin->myMoney($sender);
[33] 			$sender->sendMessage($this->plugin->getMessage("mymoney-mymoney", [$money]));
[34] 			return true;
[35] 		}
[36] 		$sender->sendMessage(TextFormat::RED."Please run this command in-game.");
[37] 		return true;
[38] 	}
[39] }
[40] 
[41] 
[42] 
[43] 
[44] 
[45] 
[46] 
[47] 
[48] 
[49] 

Backtrace:

PocketMine-MP version: 1.6.2dev #311 [Protocol 113; API 3.0.0-ALPHA7]
Git commit: 7d777510c5cee564bdd9f6d1e55d2d6c04e7de16
uname -a: Linux ns3023271.ip-151-80-230.eu 4.4.19-mod-std-ipv6-64 #1 SMP Mon Aug 22 13:05:01 CEST 2016 x86_64
PHP Version: 7.0.17
Zend version: 3.0.0
OS : Linux, linux

Loaded plugins:
PurePerms 1.4.1-dev1 by 64FF00 & ProjectInfinity for API(s) 3.0.0-ALPHA7
BlockPets 1.1.0 by BlockHorizons for API(s) 3.0.0-ALPHA7
ItemCasePE 1.1.0-dev1 by aliuly for API(s) 3.0.0-ALPHA7
FactionsPro 1.4.4-dev1 by Tethered_, HostingItAll.com for API(s) 3.0.0-ALPHA7
EconomyAPI 5.7.1-dev1 by onebone for API(s) 3.0.0-ALPHA7
SignPortal 1.1.3-dev1 by 99leonchang for API(s) 3.0.0-ALPHA7
AlwaysSpawn 2.2.3-dev1 by Philip Shilling for API(s) 3.0.0-ALPHA7
Cameraman 1.1.0-dev by ChalkPE for API(s) 3.0.0-ALPHA7
TreasureChest 1.2.1 by Awzaw for API(s) 3.0.0-ALPHA7
PureEntitiesX 0.2.2_dev by milk0417, RevivalPMMP for API(s) 3.0.0-ALPHA7
SimpleAuth 1.8.1-dev1 by PocketMine Team, shoghicp, awzaw for API(s) 3.0.0-ALPHA7
SimpleAuthHelper 2.0.5-dev1 by aliuly for API(s) 3.0.0-ALPHA7
HotBlock 1.0.3 by  for API(s) 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7
PiggyCustomEnchants 1.0.2 by DaPigGuy for API(s) 3.0.0-ALPHA7
essentialsTP 1.1.1-dev2 by  for API(s) 3.0.0-ALPHA7
ChatToDiscord 1.1.0 by eDroid for API(s) 3.0.0, 3.0.0-ALPHA6, 3.0.0-ALPHA7
Parkour 1.5.3 by jdcraft for API(s) 3.0.0-ALPHA7

**Comment by onebone** [comment]
Are you using the latest commit?

**Comment by teracube** [comment]
I used this download link

https://poggit.pmmp.io/r/8536/EconomyAPI.phar

**Comment by onebone** [comment]
Try https://jenkins.onebone.me/job/EconomyS/

They messed up their API.
