### ISSUE TITLE
EconomyAPI Error

### ISSUE THREAD

**Issue by Matunserver** [onebone/EconomyS#39]
이코노미 API 에서 Money.yml의크기가 40KB를 초과하면 이코노미 API가 비활성화됩니다 서버에는 많으사람들이잇어서 40KB는 넘어야하는대 이것때문에 현재 서버운영이 비정상적으로이루어집니다

**Comment by Matunserver** [comment]
50KB정도로실험해보시명 댈꺼같습니다

**Comment by Matunserver** [comment]
Money.yml 파일입니다 계속 귀찮게해드려서 죄송합니다 ㅠ    
https://db.tt/aTt5BBV3

**Comment by 64FF00** [comment]
money.yml의 크기가 그정도까지 되려면 얼마나 걸리나요?

**Comment by onebone** [comment]
플러그인의 문제가 아니라 수정된 PocketMine 를 사용하고 계셔서 호환성 때문에 생긴 오류입니다.
