### ISSUE TITLE
Some errors for Shop and sell?

### ISSUE THREAD

**Issue by ghost** [onebone/EconomyS#393]
i got some errors in my console by Sell and Shop. Its triggerd by clicken on them. Here is a pastebin with the errors:
https://pastebin.com/5nCsCeVr

Nothing is modified, and i use Pocketmine API 3.0.0-ALPHA7

**Comment by optimusprime338** [comment]
I am getting same error!

**Comment by optimusprime338** [comment]
try to use @poggit-orphanage repo @Yvar192

**Comment by kabluinc** [comment]
@optimusprime338 what sell shop plugin do you use for your server and where from?

**Comment by optimusprime338** [comment]
Go to poggit website and search it .use one from poggit orphage

**Comment by optimusprime338** [comment]
https://poggit.pmmp.io/p/EconomyAPI

**Comment by kabluinc** [comment]
Thanks
