### ISSUE TITLE
TaskCrash

### ISSUE THREAD

**Issue by xXNiceYT** [onebone/EconomyS#394]
It crash

Code:

Threaded members previously set to threade objects are immutable, cannot overwrite topList"(EXCEPTION) in "/EcononmyAPI_2.0.9.phar/src/onebone/econonmyapi/task/SortTask" at line 36
Could not execute asynchronous task SortTask: Task crashed.

**Comment by optimusprime338** [comment]
provide plugin version and what server software are you using with version too!! @xXNiceAssasinl0

**Comment by optimusprime338** [comment]
https://poggit.pmmp.io/p/EconomyAPI/5.7.1-2.alpha8
