### ISSUE TITLE
EconomyLand Error

### ISSUE THREAD

**Issue by Android0inko** [onebone/EconomyS#397]
Error: Declaration of onebone\economyland\EconomyLand::onCommand(pocketmine\command\CommandSender $sender, pocketmine\command\Command $cmd, string $label, array $param): bool must be compatible with pocketmine\command\CommandExecutor::onCommand(pocketmine\command\CommandSender $sender, pocketmine\command\Command $command, $label, array $args)
File: /plugins/EconomyLand_v2.0.9-37b9c050.phar/src/onebone/economyland/EconomyLand
Line: 43
Type: E_COMPILE_ERROR

**Comment by optimusprime338** [comment]
Use this:- https://poggit.pmmp.io/p/EconomyAPI/5.7.1-2.alpha8
