### ISSUE TITLE
A bug

### ISSUE THREAD

**Issue by xxddff** [onebone/EconomyS#40]
There's a bug , the server sometimes crashed. Please fix it.here is the log: 
----
[CRITICAL] Could not pass event pocketmine\event\player\PlayerQuitEvent to EconomyAPI v2.0.4: Undefined index: kkkk on onebone\economyapi\EconomyAPI
 [NOTICE] ArrayOutOfBoundsException: "Undefined index: kkkk" (E_NOTICE) in "/EconomyAPI_v2.0.4.phar/src/onebone/economyapi/EconomyAPI" at line 844

-------------
I use PocketMine Beta Build#936

**Comment by Matunserver** [comment]
EconomyAPI 2.0.5 Use please

**Comment by xxddff** [comment]
![image](https://cloud.githubusercontent.com/assets/11043135/6261032/8cdc4bf2-b823-11e4-8668-7b37926518e3.png)
can't find EconomyAPI 2.0.5
I use €¢onom¥$ 5.3

**Comment by onebone** [comment]
Oops, my mistake sorry!

Use this one :
https://www.dropbox.com/s/2w2ifzxxn7l2xn5/EconomyAPI_v2.0.5.phar?dl=0
