### ISSUE TITLE
Language Error

### ISSUE THREAD

**Issue by DrakerZR** [onebone/EconomyS#406]
Hi. When I change the language in the console it don't works. (It appears that it was changed, but nothing happens.)

And I tried to change it forn conf.yml but It didn't works.
Help

**Comment by onebone** [comment]
Fixed from https://github.com/onebone/EconomyS/commit/f9eb2425c3e13d1f9cf8bd13911fbea25f25a2c8, issue from 2 years ago though, thanks!
