### ISSUE TITLE
Indonesian Language

### ISSUE THREAD

**Issue by NewAdithRC** [onebone/EconomyS#41]
Can you please support Indonesian Language ;)

Indonesian Need This Plugin

**Comment by 64FF00** [comment]
@NewAdithRC Translate https://github.com/onebone/EconomyS/blob/master/EconomyAPI/resources/lang_def.json to your language, rename it to lang-id.json, and then please create a Pull Request for him.

**Comment by onebone** [comment]
Exactly what @64FF00 said, I'm not the Indonesian speaker so cannot support that language.
Other languages were sent by other native speakers, too. If you want EconomyAPI to support Indonesian, please send the modified 'language.properties'.
