### ISSUE TITLE
Deprecated API Version

### ISSUE THREAD

**Issue by Philipp97714** [onebone/EconomyS#415]
Please update the API Version
(plugin requires one of: 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13, 3.0.0-ALPHA14, 3.0.0-ALPHA15)

**Comment by onebone** [comment]
Use branch pm4
