### ISSUE TITLE
ArrayOutOfBoundsException

### ISSUE THREAD

**Issue by mming** [onebone/EconomyS#42]
09:13:10 [INFO] mming[/116.77.130.116:46850] logged out due to Kicked by admin. Reason: already logged in
09:13:13 [CRITICAL] Could not pass event pocketmine\event\player\PlayerQuitEvent to EconomyAPI v2.0.4: Undefined index: mming on onebone\economyapi\EconomyAPI
09:13:13 [NOTICE] ArrayOutOfBoundsException: "Undefined index: mming" (E_NOTICE) in "/EconomyAPI_v2.0.4.phar/src/onebone/economyapi/EconomyAPI" at line 844

**Comment by onebone** [comment]
It is already have been fixed.
