### ISSUE TITLE
help

### ISSUE THREAD

**Issue by mikeygio10** [onebone/EconomyS#433]
09.06 13:54:03 [Server] Server thread/CRITICAL ErrorException: "yaml_parse(): end of stream reached without finding document 0" (EXCEPTION) in "src/pocketmine/utils/Config" at line 181
09.06 13:54:03 [Server] Server thread/DEBUG #0 (): pocketmine\utils\Utils::errorExceptionHandler(integer 2, string yaml_parse(): end of stream reached without finding document 0, string phar:///PMMP-Latest-Stable.phar/src/pocketmine/utils/Config.php, integer 181, array Array())
09.06 13:54:03 [Server] Server thread/DEBUG #1 src/pocketmine/utils/Config(181): yaml_parse(string )
09.06 13:54:03 [Server] Server thread/DEBUG #2 src/pocketmine/utils/Config(113): pocketmine\utils\Config->load(string /plugin_data/EconomyAPI/Money.yml, integer 2, array Array())
09.06 13:54:03 [Server] Server thread/DEBUG #3 plugins/EconomyAPI.phar/src/onebone/economyapi/provider/YamlProvider(44): pocketmine\utils\Config->__construct(string /plugin_data/EconomyAPI/Money.yml, integer 2, array Array())
09.06 13:54:03 [Server] Server thread/DEBUG #4 plugins/EconomyAPI.phar/src/onebone/economyapi/EconomyAPI(377): onebone\economyapi\provider\YamlProvider->open()
09.06 13:54:03 [Server] Server thread/DEBUG #5 plugins/EconomyAPI.phar/src/onebone/economyapi/EconomyAPI(306): onebone\economyapi\EconomyAPI->initialize()
09.06 13:54:03 [Server] Server thread/DEBUG #6 src/pocketmine/plugin/PluginBase(123): onebone\economyapi\EconomyAPI->onEnable()
09.06 13:54:03 [Server] Server thread/DEBUG #7 src/pocketmine/plugin/PluginManager(587): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
09.06 13:54:03 [Server] Server thread/DEBUG #8 src/pocketmine/Server(1993): pocketmine\plugin\PluginManager->enablePlugin(onebone\economyapi\EconomyAPI object)
09.06 13:54:03 [Server] Server thread/DEBUG #9 src/pocketmine/Server(1979): pocketmine\Server->enablePlugin(onebone\economyapi\EconomyAPI object)
09.06 13:54:03 [Server] Server thread/DEBUG #10 src/pocketmine/Server(1773): pocketmine\Server->enablePlugins(integer 1)
09.06 13:54:03 [Server] Server thread/DEBUG #11 src/pocketmine/PocketMine(266): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
09.06 13:54:03 [Server] Server thread/DEBUG #12 (1): require(string phar:///PMMP-Latest-Stable.phar/src/pocketmine/PocketMine.php)
09.06 13:54:03 [Server] Server thread/INFO Disabling EconomyAPI v5.7.2
09.06 13:54:03 [Server] Server thread/CRITICAL Error: "Call to a member function setAll() on null" (EXCEPTION) in "plugins/EconomyAPI.phar/src/onebone/economyapi/provider/YamlProvider" at line 142
09.06 13:54:03 [Server] Server thread/DEBUG #0 plugins/EconomyAPI.phar/src/onebone/economyapi/EconomyAPI(337): onebone\economyapi\provider\YamlProvider->save()
09.06 13:54:03 [Server] Server thread/DEBUG #1 plugins/EconomyAPI.phar/src/onebone/economyapi/EconomyAPI(328): onebone\economyapi\EconomyAPI->saveAll()
09.06 13:54:03 [Server] Server thread/DEBUG #2 src/pocketmine/plugin/PluginBase(125): onebone\economyapi\EconomyAPI->onDisable()
09.06 13:54:03 [Server] Server thread/DEBUG #3 src/pocketmine/plugin/PluginManager(673): pocketmine\plugin\PluginBase->setEnabled(boolean )
09.06 13:54:03 [Server] Server thread/DEBUG #4 src/pocketmine/plugin/PluginManager(594): pocketmine\plugin\PluginManager->disablePlugin(onebone\economyapi\EconomyAPI object)
09.06 13:54:03 [Server] Server thread/DEBUG #5 src/pocketmine/Server(1993): pocketmine\plugin\PluginManager->enablePlugin(onebone\economyapi\EconomyAPI object)
09.06 13:54:03 [Server] Server thread/DEBUG #6 src/pocketmine/Server(1979): pocketmine\Server->enablePlugin(onebone\economyapi\EconomyAPI object)
09.06 13:54:03 [Server] Server thread/DEBUG #7 src/pocketmine/Server(1773): pocketmine\Server->enablePlugins(integer 1)
09.06 13:54:03 [Server] Server thread/DEBUG #8 src/pocketmine/PocketMine(266): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
09.06 13:54:03 [Server] Server thread/DEBUG #9 (1): require(string phar:///PMMP-Latest-Stable.phar/src/pocketmine/PocketMine.php)

**Comment by onebone** [comment]
It seems Money.yml file is somehow corrupted

**Comment by mikeygio10** [comment]
this is not me this is also other people too
i saw it happen to someone else too

**Comment by provsnoobgaming** [comment]
you realise the repo owner is gone right
your issue will not be dized in a pr
only a fork
