### ISSUE TITLE
Compatibility with 1.12

### ISSUE THREAD

**Issue by EduGH7** [onebone/EconomyS#437]
In the plugins of economy the server have an internal error because a change of the protocols of pocketmine

**Comment by BrownUlcer** [comment]
yes have errors on version 1.12 like economy shop and sell
what should we do for fix it?

**Comment by onebone** [comment]
This seems duplicated with your last issue. You may use EconomyShop and EconomySell from poggit and that will work. EconomyShop and EconomySell is now scheduled for rewrite thus have no plan to update for the new API. Thanks!
