### ISSUE TITLE
users cant connect after shop made

### ISSUE THREAD

**Issue by snipernubz** [onebone/EconomyS#439]
users cant connect to server after attempting to create a shop

[server.log](https://github.com/onebone/EconomyS/files/4261660/server.log)

**Comment by onebone** [comment]
This error seems to occur because the plugin uses outdated PocketMine API. I am currently planning to rewrite EconomyShop though it is being delayed for a while. Please use the version from the Poggit which has this error fixed.

**Comment by snipernubz** [comment]
what version would that be?

**Comment by onebone** [comment]
It seems it is the latest version of EconomyShop. Though it is being delayed for a while, I am planning to rewrite EconomyShop plugin. Until the rewrite ends I will provide the quick fix for the latest PocketMine.
