### ISSUE TITLE
where can I download economyapi 2.0.5

### ISSUE THREAD

**Issue by mming** [onebone/EconomyS#44]
I can't open it in china... https://www.dropbox.com/s/2w2ifzxxn7l2xn5/EconomyAPI_v2.0.5.phar?dl=0

anyother download link?

**Comment by 64FF00** [comment]
https://github.com/onebone/EconomyS/releases

**Comment by 64FF00** [comment]
@onebone :+1:

**Comment by onebone** [comment]
@64FF00 :+1:
