### ISSUE TITLE
Dont work on latest update of pocketmine

### ISSUE THREAD

**Issue by yinxo16** [onebone/EconomyS#440]
Can you please update the plugins, they dont work with Pocketmine on the last version, i will love to have all of this plugins working to play with  friends.

**Comment by karas6058** [comment]
maybe you should remain bug's description or log file

**Comment by yinxo16** [comment]
this is the log [Server thread/ERROR]: Could not load plugin 'EconomyJob': Incompatible API version (plugin requires one of: 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11)

**Comment by onebone** [comment]
What version of plugin are you using? The supporting API of the plugin is at least declared as 3.9.0.
