### ISSUE TITLE
Add "OldMoney" Value into MoneyChangedEvent

### ISSUE THREAD

**Issue by Thunder33345** [onebone/EconomyS#443]
This is so developers can get create a differences of a change

**Comment by onebone** [comment]
Refer to https://github.com/onebone/EconomyS/blob/3.x/EconomyAPI/src/onebone/economyapi/EconomyAPI.php#L448-L451, https://github.com/onebone/EconomyS/blob/3.x/EconomyAPI/src/onebone/economyapi/EconomyAPI.php#L519-L522, https://github.com/onebone/EconomyS/blob/3.x/EconomyAPI/src/onebone/economyapi/EconomyAPI.php#L591-L594 and you will see getMoney() in MoneyChangedEvent returns old money value. New value could be got with 'myMoney()'. I will add documentation to the method to avoid future confusion.
