### ISSUE TITLE
/shop command not working

### ISSUE THREAD

**Issue by parker499** [onebone/EconomyS#448]
whenever i type /shop, nothing comes up at all. i'm using aternos for the server and it on 3.14.2. i maybe thought it was the server's fault, so i made a new one with all the same plugins and it still doesnt work. i dont have any plugins that should be interfering with the plugin, so i'm very confused. any help is appreciated :D

**Comment by onebone** [comment]
What is your version of EconomyShop and EconomyAPI? Is there any error message during plugin load?

**Comment by parker499** [comment]
for EconomyAPI its 5.7.2, for Shop its 2.0.11. latest versions for both! theres been no error message or anything indicating stuff is wrong. i load up the server and its just like i never downloaded Shop before. EconomyAPI works fine for me, however. it's just EconomyShop that wont work. 
(thank you for responding so quickly!!)

**Comment by onebone** [comment]
It seems that your version is from poggit, which is not maintained by me. I think you can get help at issue tracker at EconomyS repository of Poggit.
