### ISSUE TITLE
How to use Economy Job

### ISSUE THREAD

**Issue by AlaBala-glitch** [onebone/EconomyS#451]
I searched about how to use Economy Job, I get that I can customize jobs in the plugin data, but I don't know how to join a job. Also the commands job join, job me, job retire, and job list does not work. I tried to type /job join tree_cutter , broke down a whole tree but I did not get the specified moneys. Someone can help me?

**Comment by onebone** [comment]
I think you mistyped "tree-cutter". I have tested it right now, it seems to be working. If it doesn't work please let me know the messages you have seen.
