### ISSUE TITLE
/pay Command

### ISSUE THREAD

**Issue by Dimaa0786** [onebone/EconomyS#46]
I want to pay to another player with command /pay
ex : I Have 1000
/pay example 1000 
    After that, Money 1000 that I send it,and the money didn't receive by Example
But, my money now is 0 
  Please, fix it, sorry for may bad english, I From Indonesian

**Comment by onebone** [comment]
I thougjt this bug was fixed. What version are you in?

**Comment by Dimaa0786** [comment]
VoteReward v2.1, WorldMonitor v2.0.0.000.0, SimpleWarp v1.3, EssentialsPE v1.0.2, SimpleAuth v1.6.0, EconomyAPI v2.0.0, SignPortal v1.1.2, xPermsMgr v1.7.0, PurePerms v1.0.7, AlwaysSpawn v2.1.3, ServerMail v0.0.1, Pundler v1.3, FactionsPro v1.0.1, KeepInventory v1.2.0, iProtector v2.0, MSpawns v1.4, SignShop v0.9.0, EconomyJob v2.0.0, essentialsTP v1.0.9, PvPWorlds v1, MoreCommands v1.0.1, PocketGuard v2.1, BanItem v2.1, EconomyLand v2.0.0, PureChat v1.2.3, BattleKits v1.0.3

**Comment by 64FF00** [comment]
@Dimma0786 Wow this guys still using xPermsMgr xD

**Comment by 64FF00** [comment]
@Dimaa0786*

**Comment by Dimaa0786** [comment]
Tell me, How to fix it ? :3

**Comment by onebone** [comment]
@Dimaa0786 Update the plugin!
