### ISSUE TITLE
Signs not appearing after server restart

### ISSUE THREAD

**Issue by Rspuds** [onebone/EconomyS#47]
sign shops don't appear after I restart my server. They still work if I click where they would be but you can't see them. I'm not sure if this is a problem with the plugin or my server but thought I would let u know in case its a bug

**Comment by Rspuds** [comment]
I did a little more to try to figure out what exactly was causing it and discovered the signs only don't appear after the server was closed either by a crash or in game with /stop. I think the only way to prevent it is stop it from server because all other ways I get this message which seems to be causing it.
[Server] zend_mm_heap corrupted
[PocketMine] Server was stopped.
I have found that if after this happens I load in a backup all the signs will still be visable. I don't know what is happening but I hope this information will help you to figure it out.

**Comment by Rspuds** [comment]
Just went back and tested it and using /stop didn't cause it again. The one thing I know for sure causes it is sometimes when I destroy a sign and place and other where it was it will kick me out of the sign editing screen and then when I try to break the sign I can. If I click on the sign it crashes my game but not the server. It is after I log back on that it crashes if I remember right. I have been about to make this reoccurs multiple times but haven't been able to figure out what exactly to do to cause it. Hope this helps

**Comment by onebone** [comment]
Did you have permission when you were placing or breaking the signs?

**Comment by Rspuds** [comment]
Yes

**Comment by Rspuds** [comment]
I have noticed signs not appearing may not be a problem causes by this plugin because this happens to all signs not just sign shops. Although the crash is still an issue and is one of the causes of the signs disappearing so I should be looked into. I posted the problem with signs in the general pocket mine page and am waiting for an result.

**Comment by 64FF00** [comment]
@Rspuds Ya, I'm sure this is not because of EconomyS, just a PocketMine-MP issue

**Comment by Rspuds** [comment]
I don't even know anymore. The more I think I know the more I realize I have no idea what's happening other then sometimes when I shut down the server and start it back up the sign's are still physically there but u can't see them. They still function though. I'm starting to think its not a problem with your plugin because now its doing it even without crashes. I Posted the problem on the general pocket mine page. I don't think it has anything to do with this plugin
