### ISSUE TITLE
EconomyAirport 

### ISSUE THREAD

**Issue by mming** [onebone/EconomyS#51]
16:10:39 [CRITICAL] Could not pass event pocketmine\event\player\PlayerInteractEvent to EconomyAirport v2.0.2: Undefined index: targetX on onebone\economyairport\EconomyAirport
16:10:39 [NOTICE] ArrayOutOfBoundsException: "Undefined index: targetX" (E_NOTICE) in "/EconomyAirport_v2.0.2.phar/src/onebone/economyairport/EconomyAirport" at line 129

and,I have another question: how can i use the pshop plugin？i‘v install clouditem. download psho from gitub? how to use it.  sorry for my bad english.

**Comment by onebone** [comment]
It is already fixed.
