### ISSUE TITLE
정말로 중요합니다 !!!!!! 꼭 보셔야해요

### ISSUE THREAD

**Issue by Matunserver** [onebone/EconomyS#53]
최근 테러가 일어나고있습니다 이유를 알아본결과 원본님이Money.yml 또는 Land.yml 에 ':' 가들어가면 랜두나 API가 비활성화 된다고 하셧눈대 /land invite 번호 ':' 이렇개 하면 비활성화대면서 보호가 풀립니다

**Comment by onebone** [comment]
일단 수정을 하겠습니다.

혹시라도 ':' 가 들어간 닉네임을 가지신 분들이 있다면, 그 분들은 플러그인에 대한 불이익을 받으실 수도 있습니다.

그리고 PMMP 는 웬만하면 공식적인 것을 이용해주세요.

**Comment by Matunserver** [comment]
@onebone 감사합니다 새로받겠습니다 !
