### ISSUE TITLE
제발 봐주세요ㅠㅠ

### ISSUE THREAD

**Issue by SkYDX** [onebone/EconomyS#56]
상점에 첫째줄 [SHOP] 둘째줄 $가격 셋째줄 아이템 이름 넷째줄 Amount : 양 했는데 두번 클릭해도 아무 반응이 안일어나요ㅠㅠ 돈이 없는것도 아닌데ㅠㅠ
              제발 도와주세요ㅠ

**Comment by onebone** [comment]
사용법을 다시 읽어주세요.

**Comment by SkYDX** [comment]
어떻게 해요ㅠ

**Comment by onebone** [comment]
[SHOP]
....
은 플러그인이 바꿔줍니다
"shop
1
1
1" 같이 써주세요.

**Comment by 64FF00** [comment]
@onebone :O

**Comment by SkYDX** [comment]
감사합니다 해결됬어요~~~~~
