### ISSUE TITLE
이코노미 Land 오류

### ISSUE THREAD

**Issue by ruddn0101** [onebone/EconomyS#58]
땅을구매하고 다른타유저가 부실려고 시도시 크래시덤프파일이나오면서 서버가다운댐

**Comment by Matunserver** [comment]
@ruddn0101 저는 그런상황이 발생하지않는대요.... 이코노미 API 와 Land 만넣어서 시도해보세요

**Comment by 64FF00** [comment]
크래시덤프 파일 내용도 같이 첨부해주시기 바랍니다.

**Comment by onebone** [comment]
@64FF00 님 말대로 하시고 다시 이슈를 열어주세요.

**Comment by ruddn0101** [comment]
파일첨부법좀 알려주실수잇나요 맷날 메일로보내서

**Comment by 64FF00** [comment]
여기다 그냥 복붙 ㄱ
