### ISSUE TITLE
Error while loading plugin

### ISSUE THREAD

**Issue by FraKa729** [onebone/EconomyS#60]
Always if starting Server, the EconomysAPI doesn't start!
Here's the Error...
[Server] 15:42:52 [INFO] Enabling EconomyAPI v2.0.5
[Server] 15:42:52 [NOTICE] [EconomyAPI] Auto save has been set to interval : 10 min(s)
[Server] 15:42:52 [INFO] [EconomyAPI] Checking for updates... It may be take some while.
[Server] 15:42:58 [WARNING] RuntimeException: "yaml_parse(): end of stream reached without finding document 0" (E_WARNING) in "/EconomyAPI_v2.0.5.phar/src/onebone/economyapi/EconomyAPI" at line 196
[Server] 15:42:58 [INFO] Disabling EconomyAPI v2.0.5

The server goe's on starting, but without EconomyAPI. If I type /help all the economy commands are listed, but if I type them, nothing happens...

The EconomyShop works fine, but if i sell something I don't get any money.... Maybe it hast to do with it?

PS: Sorry my very very bad english!

**Comment by onebone** [comment]
Please open economy.properties and change
 check-update=on
to
check-update=off

**Comment by FraKa729** [comment]
yay it worked :-)  thanks alot!
