### ISSUE TITLE
버그제보 합니다! (한국인 맞으시죠?)

### ISSUE THREAD

**Issue by JungHyun3459** [onebone/EconomyS#64]
오류 플러그인:
이코노미API

******************************************************************************************************************************

오류 메시지:
[WARNING] RuntimeException: "yaml_parse(): parsing error encountered during parsing: did not find expected key (line 588, column 10), context while parsing a block mapping (line 4, column 3)" (E_WARNING) in "/src/pocketmine/utils/Config" at line 138
가 뜨며 이코노미 api가 비활성화 되더군요!
하지만 다른이코노미 연관 플러그인은 그다음에 비활성화 되지않고 잘 작동합니다!

******************************************************************************************************************************

오류 상황:
적용플러그인 - Trampoline 1.2; InvenSave 1.0; Farms 1.1-alpha; GiveMeTheMoney 2.0-alpha; WorldEditArt 1.0.0_beta_dev_#045; PvPWorlds 1; Babel 1.0-alpha; SignPortal 1.1.2; PurePerms 1.0.6; SignCommand 1.1-alpha; AnnouncePro 1.1-alpha; GoodSPAWN 0.2-alpha; EconomyAPI 2.0.5; SimpleAuth 1.6.0; OneHitKill 1.0.1; timezoneFix 1.0-alpha; NydusCanal 1.5-alpha; PocketGuard 2.0.1; EconomyShop 2.0.4; EconomySell 2.0.4; EconomyLand 2.0.5
운영체제 - 리눅스 우분투 14.04 x64
크래쉬덤프 - 생성안됨.
PM버전 - PocketMine-MP 1.4.1dev-968

****************************************************************************************************************************

해결방법:
money.yml 을 삭제하니 제대로 돌아가더군요!

****************************************************************************************************************************

항상 좋은플러그인 만들어주시는 원본님 감사합니다!

Always make a good plugin gives wonbon Thank you sir!

**Comment by onebone** [comment]
혹시 ':' 가 들어간 닉네임을 가지고 있는 플레이어가 들어온적이 있나요?

**Comment by JungHyun3459** [comment]
, : ; ' " 닉네임이 들어간분은 Money.yml 파일에서 돈정보, 이름을 삭제했는데도 계속 오류가 나더군요!

**Comment by onebone** [comment]
혹시 아직 오류가 발생했을 때의 데이터 파일을 가지고 계신가요?
