### ISSUE TITLE
이코노미 API 오류

### ISSUE THREAD

**Issue by ruddn0101** [onebone/EconomyS#65]
[Server] 15:27:14 [CRITICAL] Could not execute task Callback#SimpleArea\SimpleArea::autoSave: yaml_parse(): scanning error encountered during parsing: could not find expected ':' (line 95, column 4), context while scanning a simple key (line 94, column 3)
[Server] 15:27:14 [WARNING] RuntimeException: "yaml_parse(): scanning error encountered during parsing: could not find expected ':' (line 95, column 4), context while scanning a simple key (line 94, column 3)" (E_WARNING) in "/src/pocketmine/utils/Config" at line 138
[Server] 15:27:23 [INFO] Elia online:[관리자]<0Hello0> 와파,,
[Server] 15:27:29 [CRITICAL] Unhandled exception executing command 'mystatus' in mystatus: Division by zero
[Server] 15:27:29 [WARNING] RuntimeException: "Division by zero" (E_WARNING) in "/EconomyAPI_v2.0.3.phar/src/onebone/economyapi/commands/MyStatusCommand" at line 39
[Server] 15:27:40 [INFO] 0Hello0: Teleported 0Hello0 to msms213
[Server] 15:27:46 [INFO] Elia online:[G.O.I]<msms213> ㅋㅋ
[Server] 15:29:07 [CRITICAL] Unhandled exception executing command 'takedebt' in takedebt: Undefined variable: cmd
[Server] 15:29:07 [NOTICE] UndefinedVariableException: "Undefined variable: cmd" (E_NOTICE) in "/EconomyAPI_v2.0.3.phar/src/onebone/economyapi/commands/TakeDebtCommand" at line 37
[Server] 15:29:19 [CRITICAL] Could not execute task Callback#SimpleArea\SimpleArea::autoSave: yaml_parse(): scanning error encountered during parsing: could not find expected ':' (line 95, column 4), context while scanning a simple key (line 94, column 3)
[Server] 15:29:19 [WARNING] RuntimeException: "yaml_parse(): scanning error encountered during parsing: could not find expected ':' (line 95, column 4), context while scanning a simple key (line 94, column 3)" (E_WARNING) in "/src/pocketmine/utils/Config" at line 138
[Server] 15:29:20 [INFO] logged in with entity id 44 at (Elia online, 75.2179, 95.6108, 334.8668)
[Server] 15:29:20 [INFO] There are 3/255 players online:
[Server] 15:29:20 [INFO] msms213, 0Hello0, ha_nl
[Server] 15:29:21 [INFO] ha_nl joined the game
[Server] 15:29:24 [INFO] Elia online:[부어드민]<ha_nl> ㅇㅅㅇ
[Server] 15:29:38 [INFO] Elia online:[G.O.I]<msms213> 렌드포기설
[Server] 15:29:40 [INFO] HwanE[/182.222.210.145:45710] logged out due to Server is white-listed
[Server] 15:29:40 [INFO] There are 3/255 players online:
[Server] 15:29:40 [INFO] msms213, 0Hello0, ha_nl
[Server] 15:30:06 [WARNING] msms213 moved wrongly!
[Server] Fetching position of CuboidSpace...
[Server] Constructing position 73,91,332Constructing position 73,91,333Constructing position 73,91,334Constructing position 73,91,335Constructing position 73,91,336Constructing position 74,91,332Constructing position 74,91,333Constructing position 74,91,334Constructing position 74,91,335Constructing position 74,91,336Constructing position 75,91,332Constructing position 75,91,333Constructing position 75,91,334Constructing position 75,91,335Constructing position 75,91,336Constructing position 76,91,332Constructing position 76,91,333Constructing position 76,91,334Constructing position 76,91,335Constructing position 76,91,336

Pocketmine 최신버전 사용중
[Server] Completed: 25 instances
[Server] 15:30:44 [INFO] ha_nl has left the game
[Server] 15:30:44 [INFO] 
[Server] 15:30:45 [INFO] There are 2/255 players online:
[Server] 15:30:45 [INFO] msms213, 0Hello0
[Server] 15:30:51 [WARNING] msms213 moved wrongly!
[Server] 15:31:26 [CRITICAL] Could not execute task Callback#SimpleArea\SimpleArea::autoSave: yaml_parse(): scanning error encountered during parsing: could not find expected ':' (line 95, column 4), context while scanning a simple key (line 94, column 3)
[Server] 15:31:26 [WARNING] RuntimeException: "yaml_parse(): scanning error encountered during parsing: could not find expected ':' (line 95, column 4), context while scanning a simple key (line 94, column 3)" (E_WARNING) in "/src/pocketmine/utils/Config" at line 138
[Server] 15:31:47 [INFO] jimraner2[/59.152.164.253:54181] logged out due to Server is white-listed
[Server] 15:31:47 [INFO] There are 2/255 players online:
[Server] 15:31:47 [INFO] msms213, 0Hello0
[Server] 15:31:57 [INFO] Elia online:[G.O.I]<msms213> ㅇㅋ
[Server] 15:31:59 [INFO] Elia online:[G.O.I]<msms213> 영역팔앗다
[Server] 15:32:21 [INFO] Elia online:[G.O.I]<msms213> 거기아무도없슈?
[Server] 15:32:29 [INFO] Elia online:[관리자]<0Hello0> 없슈
[Server] 15:32:30 [INFO] Elia online:[관리자]<0Hello0> ㅋㅋ
[Server] 15:32:33 [INFO] Elia online:[G.O.I]<msms213> 뭐햐유?
[Server] 15:32:42 [INFO] Elia online:[관리자]<0Hello0> 광산지어유
[Server] 15:32:47 [INFO] Elia online:[G.O.I]<msms213> 어딘지알듯
[Server] 15:33:11 [INFO] Elia online:[G.O.I]<msms213> 똑똑똑
[Server] 15:33:16 [INFO] Elia online:[G.O.I]<msms213> 광산태스터입니다
[Server] 15:33:29 [CRITICAL] Could not execute task Callback#SimpleArea\SimpleArea::autoSave: yaml_parse(): scanning error encountered during parsing: could not find expected ':' (line 95, column 4), context while scanning a simple key (line 94, column 3)
[Server] 15:33:29 [WARNING] RuntimeException: "yaml_parse(): scanning error encountered during parsing: could not find expected ':' (line 95, column 4), context while scanning a simple key (line 94, column 3)" (E_WARNING) in "/src/pocketmine/utils/Config" at line 138
[Server] 15:33:35 [INFO] Elia online:[관리자]<0Hello0> ㅋㅋㅋ
[Server] 15:33:42 [INFO] Elia online:[G.O.I]<msms213> 검사하러왓는대요
[Server] 15:33:47 [INFO] Elia online:[관리자]<0Hello0> 들어오고싶슈ㅠ??
[Server] 15:33:50 [INFO] Elia online:[G.O.I]<msms213> ㅇㅇ
[Server] 15:33:55 [INFO] Elia online:[G.O.I]<msms213> 내가예연해볼?
[Server] 15:34:00 [INFO] Elia online:[관리자]<0Hello0> ㅇㅋ
[Server] 15:34:03 [INFO] Elia online:[G.O.I]<msms213> 이안은
[Server] 15:34:07 [INFO] Elia online:[G.O.I]<msms213> 동굴보다는
[Server] 15:34:11 [INFO] Elia online:[G.O.I]<msms213> 개미소굴처럼되잇다
[Server] 15:34:14 [INFO] Elia online:[관리자]<0Hello0> ,,,,,
[Server] 15:34:17 [INFO] Elia online:[G.O.I]<msms213> 드가면 왼쪽오른쪽
[Server] 15:34:20 [INFO] Elia online:[G.O.I]<msms213> 나눠지겟지뭐
[Server] 15:34:25 [INFO] Elia online:[관리자]<0Hello0> 어케암?
[Server] 15:34:27 [INFO] Elia online:[관리자]<0Hello0> ㅎㄷㄷ

**Comment by onebone** [comment]
버그 리포트는 최신 버젼인지 확인 후 해주세요.

**Comment by ruddn0101** [comment]
@onebone 최신버전 사용중입니다 이코노미APL 5.4
