### ISSUE TITLE
EconomyCasino 오류 - 2차

### ISSUE THREAD

**Issue by cloud9350** [onebone/EconomyS#66]
pastebin 사이트가 안되는 관계로 CrashDump 파일을 복붙.

PocketMine-Soft Crash Dump Sat Mar 14 10:51:35 UTC 2015

Error: Call to undefined method onebone\economyapi\EconomyAPI::monetaryUnit()
File: /plugins/EconomyCasino_v2.0.1.phar/src/onebone/economycasino/EconomyCasino
Line: 274
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: EconomyCasino v2.0.1

Code:
[265] 					$sender->sendMessage("Usage: ".$command->getUsage());
[266] 					break;
[267] 				}
[268] 				$this->api->reduceMoney($sender, $money);
[269] 				$rand = rand(0, $this->config->get("jackpot-winning"));
[270] 				if($rand === 0){
[271] 					$this->api->addMoney($sender, $money);
[272] 					$sender->sendMessage("You've wined jackpot! You've got ".$this->api->monetaryUnit()."$money");
[273] 				}else{
[274] 					$sender->sendMessage("You've failed your jackpot! You've lost ".$this->api->monetaryUnit()."$money");
[275] 				}
[276] 				break;
[277] 		}
[278] 		return true;
[279] 	}
[280] }
[281] 
[282] 
[283] 
[284] 

Backtrace:
#0 (): pocketmine\Server->crashDump()

PocketMine-MP version: 1.4.1dev #0 [Protocol 20; API 1.11.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux localhost.localdomain 2.6.32-504.3.3.el6.x86_64 #1 SMP Wed Dec 17 01:55:02 UTC 2014 x86_64
PHP Version: 5.6.6
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
WorldGM 3 by Exxarion for API(s) 1.10.0
ItemConsume 1.2-alpha by hm for API(s) 1.4.1
Farms 1.0-non-alpha by hm for API(s) 1.4.1
MCG76_WorldEdit 0.2.4 by minecraftgenius76 for API(s) 1.8.0
SubnetBan 1.0.0 by  for API(s) 1.0.0
FixCrafting 1.0.0 by 우유맛비누 for API(s) 1.6.0
AntiTower 1 by xpyctum for API(s) 1.0.0
essentialsTP 1.0.9 by  for API(s) 1.0.0
EconomyJob 2.0.3 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
SimpleAuth 1.6.0 by PocketMine Team, shoghicp for API(s) 1.8.0
BanItem 2.1 by LDX for API(s) 1.0.0
WorldInventory DeBe by DeBe for API(s) 1.6.0
BigBrother 1.5.0-beta by shoghicp for API(s) 1.10.0
KeepInventory 1.2.0 by boybook for API(s) 1.0.0
RealTime 2.1 by Guillaume351 for API(s) 1.0.0
ChestGuard 1.1-alpha by hm for API(s) 1.4.1
TimerBan 2.1 by onebone for API(s) 1.2.0, 1.2.1
LevelChat 0.0.1 by iJoshuaHD for API(s) 1.9.0
GreenBelt 1.0-alpha by hm for API(s) 1.4.1
AntiSpam 1.0 by ns827 for API(s) 1.7.0
CustomChat 1.3.9 by Array for API(s) 1.7.1
AlwaysSpawn 2.1.3 by Comedyman937 for API(s) 1.0.0
PurePerms 1.0.7 by 64FF00 for API(s) 1.9.0
KillBounty 1.0.1.5 by  for API(s) 1.0.1.5
GoodMorning 1.0-alpha by hm for API(s) 1.4.1
VoteReward 2.1 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0
illuminate 1.5-alpha by hm for API(s) 1.4.1
BlockLog 1.2 by onebone for API(s) 1.6.0
EssentialsPE 1.1.0 Beta 5 by LegendsOfMCPE Team for API(s) 1.9.0
placebo 1.0-alpha by hm for API(s) 1.4.1
PvPWorlds 1 by  for API(s) 1.0.0
TreeChopper 1.0-alpha by hm for API(s) 1.9.0
SignStatus 1.1 by xpyctum for API(s) 1.0.0
SimpleHome 1.2 by Dutok for API(s) 1.0.0
EconomyAPI 2.0.5 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyAuction 2.0.1 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
lineSign 1 by FHAM for API(s) 1.6.0
FurnaceIndicator 1.0 by onebone for API(s) 1.6.0
GameModeKick 1.0-alpha by hm for API(s) 1.4.1
mcg76_SimplePortal 1.1.0 by minecraftgenius76 for API(s) 1.0.0
MoreCommands 1.0.2 by  for API(s) 1.4.0, 1.6.0, 1.7.0, 1.9.0, 1.10.0
EconomyTax 2.0.2 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomySell 2.0.4 by onebone for API(s) 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyAirport 2.0.3 by onebone for API(s) 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyShop 2.0.4 by onebone for API(s) 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyCasino 2.0.1 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyLand 2.0.6 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyProperty 2.0.3 by onebone for API(s) 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

발생 조건 : EconomyCasino 플러그인중 /casino start 명령어를 입력하였을경우
결과 : 위 내용의 CrashDump를 생성하며 서버종료

**Comment by cloud9350** [comment]
http://github.com/onebone/EconomyS/issues/16

이 문제도 아직 발생합니다.

**Comment by onebone** [comment]
#54
