### ISSUE TITLE
/topmoney error

### ISSUE THREAD

**Issue by peepzandmeepz** [onebone/EconomyS#71]
Hi there,

This error has been persistent in almost all the Economy API versions and it involves the /topmoney command.

If you do /topmoney [LAST PAGE], the server will halt. (It wont allow players on but will still execute commands on console)
It will only crash when you do the absolute last page. ( Ex. Page 249 of 249)
All other pages are fine and don't cause errors, only the absolute last page no matter the number of the last page.

It is still doing this in the latest Economy API version.

**Comment by MegaSamNinja** [comment]
I have a similar problem

It will crash my server when someone does /topmoney
because it loads over Page 2000

*I have disable this on my server

**Comment by onebone** [comment]
I'm trying to make the thread to handle the sorting, but maybe it will take some time.

**Comment by peepzandmeepz** [comment]
Take your time :+1:
