### ISSUE TITLE
I customized language.properties...

### ISSUE THREAD

**Issue by Conankun17** [onebone/EconomyS#75]
(Of course I saved the file.)
But after restarting PM-MP, there was original English language.properties.
I couldn't change language.
Let me know if I'm wrong...
Must I customize resources-lang_def.json?

Sorry for Consecutive posting...

**Comment by onebone** [comment]
僕のサーバーには正常的に作動します。economy.propertiesのdefault-langがuser-defineに設定しているか確認してください。


Ah, yeah, I like Japanese. If you didn't understand:
It works in my server properly. Please check if your 'default-lang' setting is set to 'user-define'.

**Comment by Conankun17** [comment]
日本語が好きと聞いて嬉しく思います。
Your words made me happy :)
実は、他の日本人の方からこの問題について質問されました。
Actually, I received query by Japanese about this problem..
僕も試してみましたが、やはり正しく動作しなかったのであなたに質問しました。
I tried changing language, but couldn't, either.
So I sent question to you.
economy.propertiesのdefault-langはuser-defineになっています。
Already set to user-define.
なぜできないのでしょう…
Why we couldn't change language...

**Comment by onebone** [comment]
変ですね。
それとも、あなたの個人の言語設定が基本に設定してそうなるかもしれません。
コンソールで/setlang user-defineコマンドを実行して試してみてください。
それでも正常的に動作しないと下のリンクで僕のデーターファイルを使ってみてください。
https://db.tt/TGCZPtKc
このファイルにMoney.ymlとBank.ymlファイルはないからあなたのデーターを使ってください。

That's strange. Or your individual setting can be the problem. Execute command '/setlang user-define' then please check if it works.
If not, please download and apply my data file into your server.
https://db.tt/TGCZPtKc
As 'Money.yml' and 'Bank.yml' is excluded, please use your data.

**Comment by Conankun17** [comment]
どちらも試してみました。
でも、やはりできませんでした...
PM-MPをリロードすると 必ず 英語のファイルになってしまいます。
I tried both way now.
But I couldn't change language.properties...
When I reloaded PM-MP, Necessarily it changed into English file.

**Comment by onebone** [comment]
EconomyAPIが最新バージョンか確認することを頼んでもいいですか？
EconomyAPIの最新バージョンは2.0.6でございます。

**Comment by Conankun17** [comment]
バージョンは最新です。

**Comment by onebone** [comment]
EconomyAPI以外のプラグインを排除して試してみてください。

**Comment by Conankun17** [comment]
EconomyAPIしか入っていませんlol

**Comment by onebone** [comment]
え。。。そうならこれで確かめてみてください
https://db.tt/zzesA4Sp

**Comment by Conankun17** [comment]
できませんでした... :(

**Comment by onebone** [comment]
そんな状況は聞いたことがありません、あなたのEconomyAPIのデーターを提供することができますか？

**Comment by Conankun17** [comment]
僕はサーバーを開いていないので、特有の変化はありません。
ダウンロードしたデータから何も変更なく、language.propertiesのみ編集しただけです。
default-languageは最初からuser-defineになっていました。
language.propertiesを編集しても、PM-MPの起動と同時に元に戻ってしまうのだと思います。

**Comment by onebone** [comment]
それ本当に変なバグですね。
EconomyAPIにはどこでもユーザーが編集した設定を変わるコードはありません。
/setlang koをして韓国語が出るか試してください。

**Comment by Conankun17** [comment]
今やってみました！
「 Your language have been set to ko」.....
本当なら韓国語になるはずですよね...？
逆に、編集した設定を適用させるコードはありますか？

**Comment by onebone** [comment]
そんなコードがあるわけがないです。
あなたの状況は非常に不思議なんです。

**Comment by Conankun17** [comment]
resourcesのlang-def.jsonを個人で変更してもいいですか？

**Comment by onebone** [comment]
もちろんです

**Comment by Conankun17** [comment]
では、resourcesのlang-def.jsonを個人で変更するということでこの件を終了していいでしょうか。

**Comment by Conankun17** [comment]
解決しました！！！
今まで、編集したデータの文字コードをUTF-8で保存していませんでした！

**Comment by onebone** [comment]
おめでとう!
