### ISSUE TITLE
EconomyAPI_v2.0.6 <- unserialize() 손상문제

### ISSUE THREAD

**Issue by HmHmmHm** [onebone/EconomyS#76]
![1511](https://cloud.githubusercontent.com/assets/8337568/6910295/1a38289a-d78c-11e4-880c-3db35ab24243.png)

( 에러발생 정황 )
CentOS에서 작동 중인 EconomyAPI 파일들을
파일질라로 Windows7 로 옮겨와서 테스팅 하면 발생함.

다행히도 원래의 경제시스템인 CentOS에서는 정상적으로 읽어들이고 있으며
운영체제가 바뀔때 인코딩이 서로 다른문제가 있을경우
unserialize 문제로 파일이 인식되지않는 문제가 있는 것으로 보입니다

**Comment by ChalkPE** [comment]
@onebone 고쳐진... 건가요?
