### ISSUE TITLE
EconomyLand corrupted land.yml file

### ISSUE THREAD

**Issue by predawnia** [onebone/EconomyS#81]
Anyone can corrupt the land.yml file and disable the plugin by inviting any player name, for example, if you type /land invite playername"  the land.yml file will be corrupted and the plugin will not load on next restart. I have players typing in /land invite playername:r  because they got the command wrong and it writes playername:r as an invitee in the land.yml file and the plugin cannot load.

When this happens, all claimed land are unclaimed and the server becomes ruined. So if you want to screw up someone's server, just do this command :p

**Comment by onebone** [comment]
Oh, sorry about that. You could remove that name from the invitee list by hand and it will be fixed temporary. I will fix that by the next version. Thank you for reporting.

**Comment by predawnia** [comment]
No problem, glad to have found this bug. You need to add a filter to only allow alphabets and numbers :) I have temporarily fixed the file by hand as the console showed which line was affected. Hopefully no other idiots make another typo and screw up the file again. Can you release a hot fix? This is really a big deal, because the affected servers could be griefed to oblivion.

**Comment by onebone** [comment]
Okay, I will release a hot fix as soon as possible.

**Comment by predawnia** [comment]
Okay great! I hope it will be soon

**Comment by predawnia** [comment]
Oops I pressed wrong button... lol

**Comment by predawnia** [comment]
I hope it will be resolved soon.

**Comment by onebone** [comment]
This was resolved in commit 4ef4eb62c9bd5f14032f4737039fa80b7944af32
