### ISSUE TITLE
[CRITICAL] ClassNotFoundException: "Class onebone\economyapi\EconomyAPI not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

### ISSUE THREAD

**Issue by Ishannaik** [onebone/EconomyS#83]
[CRITICAL] ClassNotFoundException: "Class onebone\economyapi\EconomyAPI not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144
please help

**Comment by onebone** [comment]
Make sure you have put EconomyAPI to plugins folder.
