### ISSUE TITLE
plshelp

### ISSUE THREAD

**Issue by ppgamer** [onebone/EconomyS#84]
[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] 13:51:12 [INFO] Starting Minecraft: PE server version v0.10.5 alpha
[Server] 13:51:12 [INFO] Loading pocketmine-soft.yml...
[Server] 13:51:12 [INFO] Loading pocketmine.yml...
[Server] 13:51:12 [INFO] Loading server properties...
[Server] 13:51:13 [INFO] Starting remote control listener
[Server] 13:51:13 [INFO] RCON running on 0.0.0.0:19132
[Server] 13:51:13 [INFO] Advanced cache enabled
[Server] 13:51:13 [INFO] Starting Minecraft PE server on 0.0.0.0:19132
[Server] 13:51:13 [INFO] This server is running PocketMine-Soft version 1.4.1-240 "絶好(Zekkou)ケーキ(Cake)" (API 1.11.0)
[Server] 13:51:13 [INFO] PocketMine-Soft is distributed under the LGPL License
[Server] 13:51:15 [INFO] Loading SimpleAuth v1.6.0
[Server] 13:51:15 [INFO] Loading SimpleWarp v1.4
[Server] 13:51:15 [INFO] Loading EconomyAPI v2.0.6
[Server] 13:51:16 [INFO] Loading EconomyAuction v2.0.1
[Server] 13:51:16 [INFO] Loading EconomyCasino v2.0.1
[Server] 13:51:16 [INFO] Loading EconomyJob v2.0.3
[Server] 13:51:16 [INFO] Loading EconomyLand v2.0.6
[Server] 13:51:16 [INFO] Loading EconomyProperty v2.0.3
[Server] 13:51:16 [INFO] Loading EconomySell v2.0.4
[Server] 13:51:16 [INFO] Loading EconomyShop v2.0.4
[Server] 13:51:16 [INFO] Loading EconomyTax v2.0.2
[Server] 13:51:16 [INFO] Loading ItemCloud v1.1
[Server] 13:51:16 [INFO] Loading ChatBubbles v1.1.7
[Server] 13:51:16 [INFO] Loading RandomItem v4.2
[Server] 13:51:16 [INFO] Loading PeacefulSpawn v2.4
[Server] 13:51:16 [INFO] Loading iControlU v1.3
[Server] 13:51:16 [INFO] Loading BanItem v2.1
[Server] 13:51:16 [INFO] Loading EconomyAirport v2.0.3
[Server] 13:51:16 [INFO] Loading EconomyPShop v2.0.0
[Server] 13:51:17 [INFO] Enabling SimpleAuth v1.6.0
[Server] 13:51:18 [INFO] [SimpleAuth] Everything loaded!
[Server] 13:51:20 [INFO] Preparing level "mc epic"
[Server] 13:51:20 [INFO] Enabling SimpleWarp v1.4
[Server] array(0) {
[Server] }
[Server] 13:51:21 [INFO] Enabling EconomyAPI v2.0.6
[Server] 13:51:21 [INFO] [EconomyAPI] Language set to User Defined by onebone
[Server] 13:51:21 [WARNING] RuntimeException: "yaml_parse(): end of stream reached without finding document 0" (E_WARNING) in "/src/pocketmine/utils/Config" at line 138
[Server] 13:51:21 [INFO] Disabling EconomyAPI v2.0.6
[Server] 13:51:21 [WARNING] RuntimeException: "yaml_parse(): end of stream reached without finding document 0" (E_WARNING) in "/src/pocketmine/utils/Config" at line 138
[Server] 13:51:21 [INFO] Enabling EconomyAuction v2.0.1
[Server] 13:51:21 [WARNING] RuntimeException: "Invalid argument supplied for foreach()" (E_WARNING) in "/EconomyAuction_v2.0.1.phar/src/onebone/economyauction/EconomyAuction" at line 44
[Server] 13:51:21 [INFO] Disabling EconomyAuction v2.0.1
[Server] 13:51:21 [WARNING] RuntimeException: "Invalid argument supplied for foreach()" (E_WARNING) in "/EconomyAuction_v2.0.1.phar/src/onebone/economyauction/EconomyAuction" at line 55
[Server] 13:51:21 [INFO] Enabling EconomyCasino v2.0.1
[Server] 13:51:21 [INFO] Enabling EconomyJob v2.0.3
[Server] 13:51:21 [WARNING] RuntimeException: "yaml_parse(): end of stream reached without finding document 0" (E_WARNING) in "/src/pocketmine/utils/Config" at line 138
[Server] 13:51:21 [INFO] Disabling EconomyJob v2.0.3
[Server] 
[Server] Fatal error: Call to a member function save() on null in phar:///storage/sdcard0/PocketMine/plugins/EconomyJob_v2.0.3.phar/src/onebone/economyjob/EconomyJob.php on line 57
[Server] 13:51:21 [EMERGENCY] An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[Server] 13:51:21 [EMERGENCY] Please submit the "/storage/sdcard0/PocketMine/CrashDump_Sun_Apr_26-13.51.21-ICT_2015.log" file to the Bug Reporting page. Give as much info as you can.
[Server] 13:51:24 [EMERGENCY] The crash dump has been automatically submitted to the Crash Archive. You can view it on http://crash.pocketmine.net/view/539352 or use the ID #539352.
[Server] 13:51:24 [INFO] Disabling SimpleAuth v1.6.0
[Server] 13:51:24 [INFO] Disabling SimpleWarp v1.4
[Server] 13:51:24 [INFO] Disabling EconomyCasino v2.0.1
[Server] 13:51:24 [INFO] Unloading level "mc epic"

**Comment by 64FF00** [comment]
yaml_parse() errors are usually caused by wrong or corrupted config file. Please try checking it using www.yamllint.com

**Comment by ppgamer** [comment]
err... I don't understand so much english. can you tell me this easier ? Pls pls pls pls pls !!!

**Comment by ppgamer** [comment]
And... I use android.

**Comment by ChalkPE** [comment]
This issue is duplicate with #85
