### ISSUE TITLE
how to fix save on null in phar? pls help !!!

### ISSUE THREAD

**Issue by ppgamer** [onebone/EconomyS#85]
[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] 22:02:02 [INFO] Starting Minecraft: PE server version v0.10.5 alpha
[Server] 22:02:02 [INFO] Loading pocketmine-soft.yml...
[Server] 22:02:02 [INFO] Loading pocketmine.yml...
[Server] 22:02:02 [INFO] Loading server properties...
[Server] 22:02:02 [INFO] Starting remote control listener
[Server] 22:02:02 [INFO] RCON running on 0.0.0.0:19132
[Server] 22:02:03 [INFO] Advanced cache enabled
[Server] 22:02:03 [INFO] Starting Minecraft PE server on 0.0.0.0:19132
[Server] 22:02:03 [INFO] This server is running PocketMine-Soft version 1.4.1-240 "絶好(Zekkou)ケーキ(Cake)" (API 1.11.0)
[Server] 22:02:03 [INFO] PocketMine-Soft is distributed under the LGPL License
[Server] 22:02:05 [INFO] Loading SimpleAuth v1.6.0
[Server] 22:02:05 [INFO] Loading SimpleWarp v1.4
[Server] 22:02:05 [INFO] Loading EconomyAPI v2.0.6
[Server] 22:02:05 [INFO] Loading EconomyAuction v2.0.1
[Server] 22:02:05 [INFO] Loading EconomyCasino v2.0.1
[Server] 22:02:05 [INFO] Loading EconomyJob v2.0.3
[Server] 22:02:05 [INFO] Loading EconomyLand v2.0.6
[Server] 22:02:05 [INFO] Loading EconomyProperty v2.0.3
[Server] 22:02:05 [INFO] Loading EconomySell v2.0.4
[Server] 22:02:05 [INFO] Loading EconomyShop v2.0.4
[Server] 22:02:05 [INFO] Loading EconomyTax v2.0.2
[Server] 22:02:05 [INFO] Loading ItemCloud v1.1
[Server] 22:02:05 [INFO] Loading ChatBubbles v1.1.7
[Server] 22:02:05 [INFO] Loading RandomItem v4.2
[Server] 22:02:05 [INFO] Loading PeacefulSpawn v2.4
[Server] 22:02:05 [INFO] Loading iControlU v1.3
[Server] 22:02:05 [INFO] Loading BanItem v2.1
[Server] 22:02:05 [INFO] Loading EconomyAirport v2.0.3
[Server] 22:02:05 [INFO] Loading EconomyPShop v2.0.0
[Server] 22:02:05 [INFO] Loading BattleKits v1.0.3
[Server] 22:02:08 [INFO] Enabling SimpleAuth v1.6.0
[Server] 22:02:09 [INFO] [SimpleAuth] Everything loaded!
[Server] 22:02:10 [INFO] Preparing level "mc epic"
[Server] 22:02:10 [INFO] Enabling SimpleWarp v1.4
[Server] array(0) {
[Server] }
[Server] 22:02:10 [INFO] Enabling EconomyAPI v2.0.6
[Server] 22:02:10 [INFO] [EconomyAPI] Language set to User Defined by onebone
[Server] 22:02:10 [WARNING] RuntimeException: "yaml_parse(): end of stream reached without finding document 0" (E_WARNING) in "/src/pocketmine/utils/Config" at line 138
[Server] 22:02:10 [INFO] Disabling EconomyAPI v2.0.6
[Server] 22:02:10 [WARNING] RuntimeException: "yaml_parse(): end of stream reached without finding document 0" (E_WARNING) in "/src/pocketmine/utils/Config" at line 138
[Server] 22:02:10 [INFO] Enabling EconomyAuction v2.0.1
[Server] 22:02:10 [WARNING] RuntimeException: "Invalid argument supplied for foreach()" (E_WARNING) in "/EconomyAuction_v2.0.1.phar/src/onebone/economyauction/EconomyAuction" at line 44
[Server] 22:02:10 [INFO] Disabling EconomyAuction v2.0.1
[Server] 22:02:10 [WARNING] RuntimeException: "Invalid argument supplied for foreach()" (E_WARNING) in "/EconomyAuction_v2.0.1.phar/src/onebone/economyauction/EconomyAuction" at line 55
[Server] 22:02:10 [INFO] Enabling EconomyCasino v2.0.1
[Server] 22:02:10 [INFO] Enabling EconomyJob v2.0.3
[Server] 22:02:11 [WARNING] RuntimeException: "yaml_parse(): scanning error encountered during parsing: could not find expected ':' (line 17, column 6), context while scanning a simple key (line 16, column 1)" (E_WARNING) in "/src/pocketmine/utils/Config" at line 138
[Server] 22:02:11 [INFO] Disabling EconomyJob v2.0.3
[Server] 
[Server] Fatal error: Call to a member function save() on null in phar:///storage/sdcard0/PocketMine/plugins/EconomyJob_v2.0.3.phar/src/onebone/economyjob/EconomyJob.php on line 57
[Server] 22:02:11 [EMERGENCY] An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[Server] 22:02:11 [EMERGENCY] Please submit the "/storage/sdcard0/PocketMine/CrashDump_Sun_Apr_26-22.02.11-ICT_2015.log" file to the Bug Reporting page. Give as much info as you can.
[Server] 22:02:13 [EMERGENCY] The crash dump has been automatically submitted to the Crash Archive. You can view it on http://crash.pocketmine.net/view/593285 or use the ID #593285.
[Server] 22:02:13 [INFO] Disabling SimpleAuth v1.6.0
[Server] 22:02:13 [INFO] Disabling SimpleWarp v1.4
[Server] 22:02:13 [INFO] Disabling EconomyCasino v2.0.1
[Server] 22:02:13 [INFO] Unloading level "mc epic"

Pls help me

**Comment by ChalkPE** [comment]
This error also occurs in the desktop version? Mobile version might be the cause of this error
(Also config files may have been damaged, you should check them!)

**Comment by ppgamer** [comment]
I think my file is damaged becouse some of it are unopenable. How to fix them ? Reinstall it ? Or remove it ? (I am very newbie and my English is not good very much. I will thank so much if you understand me. Pls help !)

**Comment by ChalkPE** [comment]
@ppgamer After you removed damaged files, then plugins will re-generate them.

By the way, what is your phone's android version? (Some versions of Android have an sdcard access problem)

> It can be found at `Settings` -> `About phone` (or tablet) -> `Android version`

**Comment by onebone** [comment]
I think you have modified config files in a wrong way. Check if it works after removing data files.

**Comment by 64FF00** [comment]
NUUUUUUUUUUUUUUUUUUUUUUUUUUU

**Comment by ppgamer** [comment]
I use android and I rooted it. If you neet more data about my taplet I will tell it later

**Comment by ppgamer** [comment]
Er... Did it tell what file are wrong ?
And... Config file is config.yml ?
(I tell u I'm very newbie)

**Comment by ppgamer** [comment]
Oh my android are 4.2.2

**Comment by ppgamer** [comment]
Do I need to remove all of .yml file that conrupt or just config.yml file ?

**Comment by ChalkPE** [comment]
@ppgamer Try both ways!

**Comment by ppgamer** [comment]
I'l try

**Comment by ppgamer** [comment]
YAY!!! I't worked !!!! But I lost all server data :-(  And I got the bug !  when I set server to flat It doesn't flat but it default. HOW TO FIX ITTTTTTTTTTTTTTTTTTTT pls help

**Comment by ppgamer** [comment]
Here's a console
[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] 18:08:56 [INFO] Starting Minecraft: PE server version v0.10.5 alpha
[Server] 18:08:56 [INFO] Loading pocketmine-soft.yml...
[Server] 18:08:56 [INFO] Loading pocketmine.yml...
[Server] 18:08:56 [INFO] Loading server properties...
[Server] 18:08:56 [INFO] Starting remote control listener
[Server] 18:08:56 [INFO] RCON running on 0.0.0.0:19132
[Server] 18:08:56 [INFO] Advanced cache enabled
[Server] 18:08:56 [INFO] Starting Minecraft PE server on 0.0.0.0:19132
[Server] 18:08:56 [INFO] This server is running PocketMine-Soft version 1.4.1-240 "絶好(Zekkou)ケーキ(Cake)" (API 1.11.0)
[Server] 18:08:56 [INFO] PocketMine-Soft is distributed under the LGPL License
[Server] 18:08:57 [INFO] Loading SimpleAuth v1.6.0
[Server] 18:08:57 [INFO] Loading SimpleWarp v1.4
[Server] 18:08:57 [INFO] Loading EconomyAPI v2.0.6
[Server] 18:08:57 [INFO] Loading EconomyAuction v2.0.1
[Server] 18:08:57 [INFO] Loading EconomyCasino v2.0.1
[Server] 18:08:57 [INFO] Loading EconomyJob v2.0.3
[Server] 18:08:57 [INFO] Loading EconomyLand v2.0.6
[Server] 18:08:57 [INFO] Loading EconomyProperty v2.0.3
[Server] 18:08:57 [INFO] Loading EconomySell v2.0.4
[Server] 18:08:57 [INFO] Loading EconomyShop v2.0.4
[Server] 18:08:57 [INFO] Loading EconomyTax v2.0.2
[Server] 18:08:57 [INFO] Loading ItemCloud v1.1
[Server] 18:08:57 [INFO] Loading ChatBubbles v1.1.7
[Server] 18:08:57 [INFO] Loading RandomItem v4.2
[Server] 18:08:57 [INFO] Loading PeacefulSpawn v2.4
[Server] 18:08:57 [INFO] Loading iControlU v1.3
[Server] 18:08:57 [INFO] Loading BanItem v2.1
[Server] 18:08:57 [INFO] Loading EconomyAirport v2.0.3
[Server] 18:08:57 [INFO] Loading EconomyPShop v2.0.0
[Server] 18:08:57 [INFO] Loading BattleKits v1.0.3
[Server] 18:08:58 [INFO] Enabling SimpleAuth v1.6.0
[Server] 18:08:58 [INFO] [SimpleAuth] Everything loaded!
[Server] 18:08:59 [INFO] Preparing level "mc epic"
[Server] 18:08:59 [INFO] Enabling SimpleWarp v1.4
[Server] array(0) {
[Server] }
[Server] 18:08:59 [INFO] Enabling EconomyAPI v2.0.6
[Server] 18:08:59 [NOTICE] [EconomyAPI] Auto save has been set to interval : 10 min(s)
[Server] 18:08:59 [INFO] [EconomyAPI] Checking for updates... It may be take some while.
[Server] 18:09:00 [NOTICE] [EconomyAPI] EconomyAPI is currently up-to-date.
[Server] 18:09:00 [INFO] Enabling EconomyAuction v2.0.1
[Server] 18:09:01 [WARNING] RuntimeException: "Invalid argument supplied for foreach()" (E_WARNING) in "/EconomyAuction_v2.0.1.phar/src/onebone/economyauction/EconomyAuction" at line 44
[Server] 18:09:01 [INFO] Disabling EconomyAuction v2.0.1
[Server] 18:09:01 [WARNING] RuntimeException: "Invalid argument supplied for foreach()" (E_WARNING) in "/EconomyAuction_v2.0.1.phar/src/onebone/economyauction/EconomyAuction" at line 55
[Server] 18:09:01 [INFO] Enabling EconomyCasino v2.0.1
[Server] 18:09:01 [INFO] Enabling EconomyJob v2.0.3
[Server] 18:09:01 [INFO] Enabling EconomyLand v2.0.6
[Server] 18:09:01 [WARNING] RuntimeException: "Invalid argument supplied for foreach()" (E_WARNING) in "/EconomyLand_v2.0.6.phar/src/onebone/economyland/EconomyLand" at line 65
[Server] 18:09:01 [INFO] Disabling EconomyLand v2.0.6
[Server] 18:09:01 [WARNING] RuntimeException: "Invalid argument supplied for foreach()" (E_WARNING) in "/EconomyLand_v2.0.6.phar/src/onebone/economyland/EconomyLand" at line 110
[Server] 18:09:01 [INFO] Enabling EconomyProperty v2.0.3
[Server] 18:09:01 [INFO] Enabling EconomySell v2.0.4
[Server] 18:09:01 [INFO] Enabling EconomyShop v2.0.4
[Server] 18:09:01 [INFO] Enabling EconomyTax v2.0.2
[Server] 18:09:01 [INFO] Enabling ItemCloud v1.1
[Server] 18:09:01 [INFO] Enabling ChatBubbles v1.1.7
[Server] 18:09:01 [INFO] [ChatBubbles] ChatBubbles Loaded!
[Server] 18:09:01 [INFO] Enabling RandomItem v4.2
[Server] 18:09:01 [INFO] Enabling PeacefulSpawn v2.4
[Server] 18:09:01 [INFO] Enabling iControlU v1.3
[Server] 18:09:01 [INFO] Enabling BanItem v2.1
[Server] 18:09:01 [INFO] Enabling EconomyAirport v2.0.3
[Server] 18:09:01 [INFO] Enabling EconomyPShop v2.0.0
[Server] 18:09:01 [INFO] Enabling BattleKits v1.0.3
[Server] 18:09:01 [INFO] [BattleKits] Loaded EconomyS by onebone
[Server] 18:09:01 [INFO] [BattleKits] Loaded 1 kits.
[Server] 18:09:03 [INFO] Starting GS4 status listener
[Server] 18:09:03 [INFO] Setting query port to 19132
[Server] 18:09:03 [INFO] Query running on 0.0.0.0:19132
[Server] 18:09:03 [INFO] Default game type: SURVIVAL
[Server] 18:09:03 [INFO] Done (7.634s)! For help, type "help" or "?"

Here's it

**Comment by ppgamer** [comment]
Now I have another issues
[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] 19:01:42 [INFO] Starting Minecraft: PE server version v0.10.5 alpha
[Server] 19:01:42 [INFO] Loading pocketmine-soft.yml...
[Server] 19:01:42 [INFO] Loading pocketmine.yml...
[Server] 19:01:42 [INFO] Loading server properties...
[Server] 19:01:43 [INFO] Advanced cache enabled
[Server] 19:01:43 [INFO] Starting Minecraft PE server on 0.0.0.0:19132
[Server] 19:01:43 [INFO] This server is running PocketMine-Soft version 1.4.1-240 "絶好(Zekkou)ケーキ(Cake)" (API 1.11.0)
[Server] 19:01:43 [INFO] PocketMine-Soft is distributed under the LGPL License
[Server] 19:01:45 [INFO] Loading SimpleAuth v1.6.0
[Server] 19:01:45 [INFO] Loading SimpleWarp v1.4
[Server] 19:01:45 [INFO] Loading EconomyAPI v2.0.6
[Server] 19:01:45 [INFO] Loading EconomyAuction v2.0.1
[Server] 19:01:45 [INFO] Loading EconomyCasino v2.0.1
[Server] 19:01:45 [INFO] Loading EconomyJob v2.0.3
[Server] 19:01:45 [INFO] Loading EconomyLand v2.0.6
[Server] 19:01:45 [INFO] Loading EconomyProperty v2.0.3
[Server] 19:01:45 [INFO] Loading EconomySell v2.0.4
[Server] 19:01:45 [INFO] Loading EconomyShop v2.0.4
[Server] 19:01:45 [INFO] Loading EconomyTax v2.0.2
[Server] 19:01:45 [INFO] Loading ItemCloud v1.1
[Server] 19:01:45 [INFO] Loading ChatBubbles v1.1.7
[Server] 19:01:45 [INFO] Loading RandomItem v4.2
[Server] 19:01:45 [INFO] Loading PeacefulSpawn v2.4
[Server] 19:01:45 [INFO] Loading iControlU v1.3
[Server] 19:01:45 [INFO] Loading BanItem v2.1
[Server] 19:01:45 [INFO] Loading EconomyAirport v2.0.3
[Server] 19:01:45 [INFO] Loading EconomyPShop v2.0.0
[Server] 19:01:46 [INFO] Loading BattleKits v1.0.3
[Server] 19:01:46 [INFO] Enabling SimpleAuth v1.6.0
[Server] 19:01:46 [INFO] [SimpleAuth] Everything loaded!
[Server] 19:01:48 [ERROR] Could not load level "world": zlib_decode(): data error
[Server] 19:01:48 [WARNING] RuntimeException: "zlib_decode(): data error" (E_WARNING) in "/src/pocketmine/nbt/NBT" at line 124
[Server] 19:01:48 [EMERGENCY] No default level has been loaded
[Server] 19:01:48 [INFO] Disabling SimpleAuth v1.6.0
[Server] 19:01:48 [INFO] Stopping other threads
[PocketMine] Server was stopped.

Pls help

**Comment by ppgamer** [comment]
Oh...it isn't error by this plugin sorry
