### ISSUE TITLE
Error of EconomyPShop?

### ISSUE THREAD

**Issue by TheG4m3r831** [onebone/EconomyS#87]
18:00:29 [CRITICAL] Could not load plugin 'EconomyPShop': Unknown dependency
18:00:29 [CRITICAL] Could not load plugin 'EconomyPShop': Unknown dependency
18:00:29 [CRITICAL] Could not load plugin 'EconomyPShop': Unknown dependency
18:00:29 [CRITICAL] Could not load plugin 'EconomyPShop': Circular dependency detected

**Comment by vvzar** [comment]
You have to install plugin itemcloud for item db

**Comment by TheG4m3r831** [comment]
O ok thanks.
