### ISSUE TITLE
how to fix this problem ?????

### ISSUE THREAD

**Issue by ppgamer** [onebone/EconomyS#88]
[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] 19:01:42 [INFO] Starting Minecraft: PE server version v0.10.5 alpha
[Server] 19:01:42 [INFO] Loading pocketmine-soft.yml...
[Server] 19:01:42 [INFO] Loading pocketmine.yml...
[Server] 19:01:42 [INFO] Loading server properties...
[Server] 19:01:43 [INFO] Advanced cache enabled
[Server] 19:01:43 [INFO] Starting Minecraft PE server on 0.0.0.0:19132
[Server] 19:01:43 [INFO] This server is running PocketMine-Soft version 1.4.1-240 "絶好(Zekkou)ケーキ(Cake)" (API 1.11.0)
[Server] 19:01:43 [INFO] PocketMine-Soft is distributed under the LGPL License
[Server] 19:01:45 [INFO] Loading SimpleAuth v1.6.0
[Server] 19:01:45 [INFO] Loading SimpleWarp v1.4
[Server] 19:01:45 [INFO] Loading EconomyAPI v2.0.6
[Server] 19:01:45 [INFO] Loading EconomyAuction v2.0.1
[Server] 19:01:45 [INFO] Loading EconomyCasino v2.0.1
[Server] 19:01:45 [INFO] Loading EconomyJob v2.0.3
[Server] 19:01:45 [INFO] Loading EconomyLand v2.0.6
[Server] 19:01:45 [INFO] Loading EconomyProperty v2.0.3
[Server] 19:01:45 [INFO] Loading EconomySell v2.0.4
[Server] 19:01:45 [INFO] Loading EconomyShop v2.0.4
[Server] 19:01:45 [INFO] Loading EconomyTax v2.0.2
[Server] 19:01:45 [INFO] Loading ItemCloud v1.1
[Server] 19:01:45 [INFO] Loading ChatBubbles v1.1.7
[Server] 19:01:45 [INFO] Loading RandomItem v4.2
[Server] 19:01:45 [INFO] Loading PeacefulSpawn v2.4
[Server] 19:01:45 [INFO] Loading iControlU v1.3
[Server] 19:01:45 [INFO] Loading BanItem v2.1
[Server] 19:01:45 [INFO] Loading EconomyAirport v2.0.3
[Server] 19:01:45 [INFO] Loading EconomyPShop v2.0.0
[Server] 19:01:46 [INFO] Loading BattleKits v1.0.3
[Server] 19:01:46 [INFO] Enabling SimpleAuth v1.6.0
[Server] 19:01:46 [INFO] [SimpleAuth] Everything loaded!
[Server] 19:01:48 [ERROR] Could not load level "world": zlib_decode(): data error
[Server] 19:01:48 [WARNING] RuntimeException: "zlib_decode(): data error" (E_WARNING) in "/src/pocketmine/nbt/NBT" at line 124
[Server] 19:01:48 [EMERGENCY] No default level has been loaded
[Server] 19:01:48 [INFO] Disabling SimpleAuth v1.6.0
[Server] 19:01:48 [INFO] Stopping other threads
[PocketMine] Server was stopped.

**Comment by onebone** [comment]
This is NOT error of my plugin.

**Comment by ppgamer** [comment]
Oh...sorry
