### ISSUE TITLE
how to fix save on null in phar ???

### ISSUE THREAD

**Issue by ppgamer** [onebone/EconomyS#89]
[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] 12:17:08 [INFO] Loading pocketmine.yml...
[Server] 12:17:08 [INFO] Loading server properties...
[Server] 12:17:08 [INFO] Selected English (eng) as the base language
[Server] 12:17:08 [INFO] Starting Minecraft: PE server version v0.11.0 alpha build 7
[Server] 12:17:08 [INFO] Starting remote control listener
[Server] 12:17:08 [INFO] RCON running on 0.0.0.0:19132
[Server] 12:17:08 [NOTICE] The memory-limit setting has been deprecated.
[Server] 12:17:08 [NOTICE] There are new memory settings on pocketmine.yml to tune memory and events.
[Server] 12:17:08 [NOTICE] You can also reduce the amount of threads and chunks loaded control the memory usage.
[Server] 12:17:08 [INFO] Opening server on 0.0.0.0:19132
[Server] 12:17:08 [INFO] This server is running PocketMine-MP version 1.5dev-1094 "活発(Kappatsu)フグ(Fugu)" (API 1.12.0)
[Server] 12:17:08 [INFO] PocketMine-MP is distributed under the LGPL License
[Server] 12:17:10 [INFO] Loading SimpleAuth v1.6.0
[Server] 12:17:10 [INFO] Loading SimpleWarp v1.4
[Server] 12:17:10 [INFO] Loading EconomyAPI v2.0.6
[Server] 12:17:10 [INFO] Loading EconomyAuction v2.0.1
[Server] 12:17:10 [INFO] Loading EconomyCasino v2.0.1
[Server] 12:17:10 [INFO] Loading EconomyJob v2.0.3
[Server] 12:17:10 [INFO] Loading EconomyLand v2.0.6
[Server] 12:17:10 [INFO] Loading EconomyProperty v2.0.3
[Server] 12:17:10 [INFO] Loading EconomySell v2.0.4
[Server] 12:17:10 [INFO] Loading EconomyShop v2.0.4
[Server] 12:17:10 [INFO] Loading EconomyTax v2.0.2
[Server] 12:17:10 [INFO] Loading ItemCloud v1.1
[Server] 12:17:10 [INFO] Loading ChatBubbles v1.1.7
[Server] 12:17:10 [INFO] Loading RandomItem v4.2
[Server] 12:17:10 [INFO] Loading PeacefulSpawn v2.4
[Server] 12:17:10 [INFO] Loading iControlU v1.3
[Server] 12:17:10 [INFO] Loading BanItem v2.1
[Server] 12:17:10 [INFO] Loading EconomyAirport v2.0.3
[Server] 12:17:10 [INFO] Loading EconomyPShop v2.0.0
[Server] 12:17:10 [INFO] Loading BattleKits v1.0.3
[Server] 12:17:11 [INFO] Enabling SimpleAuth v1.6.0
[Server] 12:17:12 [INFO] [SimpleAuth] Everything loaded!
[Server] 12:17:12 [NOTICE] Level "mcepic" not found
[Server] 12:17:12 [INFO] Preparing level "mcepic"
[Server] 12:17:12 [NOTICE] Spawn terrain for level "mcepic" is being generated in the background
[Server] 12:17:15 [INFO] Enabling SimpleWarp v1.4
[Server] array(0) {
[Server] }
[Server] 12:17:15 [INFO] Enabling EconomyAPI v2.0.6
[Server] 12:17:15 [INFO] [EconomyAPI] Language set to User Defined by onebone
[Server] 12:17:15 [WARNING] RuntimeException: "yaml_parse(): end of stream reached without finding document 0" (E_WARNING) in "/src/pocketmine/utils/Config" at line 138
[Server] 12:17:15 [INFO] Disabling EconomyAPI v2.0.6
[Server] 12:17:15 [WARNING] RuntimeException: "yaml_parse(): end of stream reached without finding document 0" (E_WARNING) in "/src/pocketmine/utils/Config" at line 138
[Server] 12:17:15 [INFO] Enabling EconomyAuction v2.0.1
[Server] 12:17:15 [WARNING] RuntimeException: "Invalid argument supplied for foreach()" (E_WARNING) in "/EconomyAuction_v2.0.1.phar/src/onebone/economyauction/EconomyAuction" at line 44
[Server] 12:17:15 [INFO] Disabling EconomyAuction v2.0.1
[Server] 12:17:15 [WARNING] RuntimeException: "Invalid argument supplied for foreach()" (E_WARNING) in "/EconomyAuction_v2.0.1.phar/src/onebone/economyauction/EconomyAuction" at line 55
[Server] 12:17:15 [INFO] Enabling EconomyCasino v2.0.1
[Server] 12:17:15 [INFO] Enabling EconomyJob v2.0.3
[Server] 12:17:15 [WARNING] RuntimeException: "yaml_parse(): end of stream reached without finding document 0" (E_WARNING) in "/src/pocketmine/utils/Config" at line 138
[Server] 12:17:15 [INFO] Disabling EconomyJob v2.0.3
[Server] 
[Server] Fatal error: Call to a member function save() on null in phar:///storage/sdcard0/PocketMine/plugins/EconomyJob_v2.0.3.phar/src/onebone/economyjob/EconomyJob.php on line 57
[Server] 12:17:15 [EMERGENCY] An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[Server] 12:17:15 [EMERGENCY] Please upload the "/storage/sdcard0/PocketMine/CrashDump_Wed_Apr_29-12.17.15-ICT_2015.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
[Server] 12:17:17 [EMERGENCY] The crash dump has been automatically submitted to the Crash Archive. You can view it on http://crash.pocketmine.net/view/772846 or use the ID #772846.
[Server] 12:17:18 [INFO] Disabling SimpleAuth v1.6.0
[Server] 12:17:18 [INFO] Disabling SimpleWarp v1.4
[Server] 12:17:18 [INFO] Disabling EconomyCasino v2.0.1
[Server] 12:17:18 [INFO] Unloading level "mcepic"

I had this problem about every time. Pls help me !!!

**Comment by ppgamer** [comment]
Pls someone answer me

**Comment by ChalkPE** [comment]
Did you tried on PC?

**Comment by onebone** [comment]
Could you provide me your EconomyAPI data folder?

**Comment by 64FF00** [comment]
yaml_parse() error... Maybe he did something wrong with the config again?

**Comment by ppgamer** [comment]
@ChalkPE i use windows xp so i can't
@64FF00 my config file are about always broken. I don't know why.
@onebone how?

**Comment by 64FF00** [comment]
@ppgamer Are you using tabs instead of spaces to edit it?

**Comment by ppgamer** [comment]
You know ? Android's keyboard didn't had TAB button.

**Comment by onebone** [comment]
@ppgamer Zip EconomyAPI folder in plugins folder and send it to me by email or by clouds or by others.

**Comment by ppgamer** [comment]
My file are very easy to crashing. And now it crashed again -_-

**Comment by ChalkPE** [comment]
@ppgamer I think your error occurred because of your environment, not because of our plugin.


> Did you force-stop the server? Config files can be easily damaged when you stop the server not by the /stop command.
