### ISSUE TITLE
EconomyLand integration with pureperms and factionspro

### ISSUE THREAD

**Issue by vvzar** [onebone/EconomyS#92]
Is any possibility to make land owner a group from pureperms or faction from factionspro?
I cant sell land to a group of players.

**Comment by onebone** [comment]
You mean migrating data of land like 'EconomyLand -> FactionsPro'?

**Comment by vvzar** [comment]
Yes. Group account and group land list

**Comment by onebone** [comment]
That is not possible without something like "bridge" plugin.
