### ISSUE TITLE
property 오류 (land 오류도 의심)

### ISSUE THREAD

**Issue by ruddn0101** [onebone/EconomyS#95]
property 로 땅구매 표지판 생성후 구매 한후에 그 땅에 서가지고 
/land here 치면 주인이 없다뜹니다 분명 돈은 나갓는대

**Comment by onebone** [comment]
더 안쪽으로 가면 되나요?

**Comment by onebone** [comment]
전 작동하는데 Property 표지판을 잘못 설정하신거 아닌가요?

**Comment by ruddn0101** [comment]
아뇨 똑같이 뜨고 다하는대 주인이 없다뜹니다
