### ISSUE TITLE
Cant Install The Plugin For Cooked Porkchop Server

### ISSUE THREAD

**Issue by MichaelVierra** [onebone/EconomyS#96]
Hi One Bone I'm trying to set up a shop on my Factions server and I'm not quite sure how to install the zip file in my plugins folder, when I try to compress the whole economy folder as a zip and place it in my plugins folder Im not sure what to do from there. I believe there are many others that would like this fixed and I've looked around the Interwebs for a tutorial, but unfortunately could not find one, if you could get back to me ASAP with steps or a video on how to install the plugin Economy for my Cooked Porkchop Server that would be awesome, thank you for your time and patience. 
                                                                                                               Michael

**Comment by onebone** [comment]
It is hard for me to record a video.
I will explain it by character:
STEP1: Download zip file from forum.
STEP2: Extract the zip file.
STEP3: Copy phar files to /plugins folder.
STEP4: Restart your server.
STEP5: ...
STEP6: PROFIT!

**Comment by MichaelVierra** [comment]
Thank you OneBone for your patience,

  When I extract the zip file and have the economy folder all of the contents are more folders like economy auctions and airport and stuff and when I open those folders what I get are php files so when I extract the zip from the web where exactly are the .phar files at?
                    Thanks,
                            Michael

**Comment by ChalkPE** [comment]
@MichaelVierra You can create .phar file of the plugin folder by [DevTools](http://forums.pocketmine.net/plugins/devtools.208/)

**Comment by onebone** [comment]
@MichaelVierra I think you have got source code. Download binary files or download from forums.

**Comment by MichaelVierra** [comment]
Thanks I'll give it a try

**Comment by MichaelVierra** [comment]
So I've got economy API, auction, casino, and Job but the shop phar won't load is there something I need to do in order to make that load as well because that is the main thing I need? Thanks, Michael

**Comment by MichaelVierra** [comment]
I get an error message saying that the API is not Compatible. Btw

**Comment by MichaelVierra** [comment]
Nope just have a newer version fixed thanks for your help
